### PR TITLE
Fix sign error in examples.

### PR DESCRIPTION
**Pull request by sracaniere**

### CODE REVIEW

**Comment by gnecula** [comment]
Thanks for fixing this!

**Comment by gnecula** [comment]
@mattjj FYI, I assume this is what you meant. Let me know if this is not a mistake, and you actually wanted to demonstrate custom AD by using a different mathematical formula than the correct one.

**Comment by sracaniere** [comment]
Before my proposed change, there is nothing saying "Beware, we are using the wrong differential here".  We could add such a warning, but personally, I think we should avoid using the wrong differential, even with a warning message, because it's just weird and surprising. The "Example problems" section in the doc  shows how to avoid numerical issues by computing the correct gradient with a different, more stable formula. This is a very nice example (well done to whoever wrote that one), and it does show how to use custom AD.

**Comment by mattjj** [comment]
Thanks for the catch!

**Review by mattjj — APPROVED** [review]
LGTM, thanks for catching this bug!

**Pull request merged**
