### PR TITLE
Annotate nn.initializers

### PR DESCRIPTION
**Pull request by NeilGirdhar**
This was done to expose an Initializers type annotation that can be used
in other libraries.

### CODE REVIEW

**Comment by NeilGirdhar** [comment]
@jakevdp Would this fix the problems in https://github.com/google/jax/pull/9596 ?  I broadened two of the named-shape-annotated private functions.  The third seems to require `NamedShape` since it accesses `shape.total`.

**Review by jakevdp — APPROVED** [review]
Looks good; I think this should remedy the problems from the previous PR, but I'll run some tests to make sure. It will probably be early next week before I can get this merged.

**Comment by jakevdp** [comment]
Readthedocs failure looks unrelated to this.

**Comment by NeilGirdhar** [comment]
Thanks a lot!  No rush

**Pull request merged**
