### PR TITLE
Common Gotchas notebook and notebook fixes

### PR DESCRIPTION
**Pull request by levskaya**
This adds the "common gotchas" notebook for jax, it fixes the broken JSON in the "gufuncs" notebook, and adds jax and jaxlib install commands to two notebooks that lacked them for easy interactive colab use.  

I also added a README.md to the notebooks directory with links to interactive colabs.

### CODE REVIEW

**Comment by mattjj** [comment]
The 3D convolution images are awesome!

I have a few ideas for tweaks in the gotchas notebook. We could either merge now and I can help make these changes, or you could make them on this PR. Which do you prefer?

Ideas:
- mention that, under `@jit`, the update functions like `index_update` will execute in-place if the input value isn't ever reused
- could mention the other problems with the Mersenne Twister outlined in the [Parallel Random Numbers: As easy as 1, 2, 3 paper](https://www.thesalmons.org/john/random123/papers/random123sc11.pdf), e.g. it [fails the BigCrush test (Fig 2)](http://www.pcg-random.org/pdf/toms-oneill-pcg-family-v1.02.pdf), has a huge 2.5kB of state per thread, is [hard to initialize correctly](https://dl.acm.org/citation.cfm?id=1276928), and is generally slow. See also this [StackExchange answer](https://cs.stackexchange.com/a/53475).
- could mention that `while_loop` will be forward-mode differentiable soon, but not sure if we'll ever make it reverse-mode differentiable (it'd probably always be slow)
- the Python equivalent of `lax.scan` is actually a special case, since `lax.scan` will tree-map through nested container types, but we can just mention that in an example
- can we remove the "Functions with argument-VALUE-dependent array shapes and static_argnums" section now, or does it still have something that's not in the earlier section mentioning `static_argnums`?
- typo: "The convenience __lax.cond__, lax.cond_with_general_padding helper" -> The convenience `lax.conv`

**Comment by levskaya** [comment]
Added requested edits.  I've kept "Functions with argument-VALUE-dependent array shapes and static_argnums" because so many people run into the length-dependency problem even more often than control flow issues.  we need something of the sort

**Comment by levskaya** [comment]
Edited some redundancy down further around control flow and static argnums discussion.

**Comment by levskaya** [comment]
Q: Any more edits desired for this?

**Comment by mattjj** [comment]
To be honest, I thought we'd already merged this! (We did some reviewing/revising offline.) Thanks for the ping.

**Review by mattjj — APPROVED** [review]
I love this! It turned out super well. I can't believe how much content is in here. It's better than everything else we have (basically just the README and scattered, less clear comments on GitHub issues). And it was worth polishing hard because it'll become a standard reference. I suspect we'll be linking this to users quite frequently.

My only remaining suggestions:

- The author list should really just be levskaya@ because mattjj@ did <1% of the work here!
- I'm split again on how to mark the differentiability of `while_loop` and `fori_loop`. I think they both _could_ in principle be forward-mode differentiable, but it's a low priority for us to implement. We could mark them both as "could be forward-mode differentiable, but we're not working on it."

Given that I've been slow to review this already, I think it's best to merge this now and adjust those two comments in follow-up revisions.

**Pull request merged**
