### PR TITLE
Add a jax.profiler.StepTraceContext API.

### PR DESCRIPTION
**Pull request by jray319**

### CODE REVIEW

**Review by jekbradbury — APPROVED** [review]
I'm not a huge fan of the name `RootTraceContext` but I don't have any better ideas.

**Comment by jekbradbury** [comment]
The CI failure seems like a mypy bug (the `__init__` it's complaining about should be inherited from the C++ class, not from `object`); maybe you can silence it by using `super()`?

**Comment by jray319** [comment]
> I'm not a huge fan of the name `RootTraceContext` but I don't have any better ideas.

I initially named it as `StepTraceContext` but didn't want to say "step" at the JAX level.

> The CI failure seems like a mypy bug (the `__init__` it's complaining about should be inherited from the C++ class, not from `object`); maybe you can silence it by using `super()`?

That works! Thanks.

**Comment by jekbradbury** [comment]
Can you switch it to `StepTraceContext`? Even though it can be used for other purposes in JAX, and even though we leave training loop-type things up to Flax/Haiku/Trax/etc., the team believes it's a clearer name given that the profiler UI calls the units "steps".

I'm happy to merge it after that; sorry for letting the PR languish.

**Comment by jray319** [comment]
No problem. Changed the name. PTAL.

**Pull request merged**
