### PR TITLE
Add instructions for building with ROCM.

### PR DESCRIPTION
**Pull request by hawkinsp**
@rsanthanam-amd

### CODE REVIEW

**Comment by rsanthanam-amd** [comment]
LGTM.  Adding @jayfurmanek for further commentary.

**Comment by hawkinsp** [comment]
One question I have is: when is it necessary to use the AMD fork of TF? I'm toying with the idea of setting up a ROCM CI build (build only, we don't have the GPU hardware) and it would be very helpful if we could just use upstream TF.

**Comment by rsanthanam-amd** [comment]
Currently, JAX will not build with upstream TF so the AMD fork must be used.

I need to discuss a plan with my team to enable ROCm JAX to build with upstream TF.

**Comment by jayfurmanek** [comment]
> Currently, JAX will not build with upstream TF so the AMD fork must be used.

The fix is likely fairly simple. Getting it merged in TF is another story. We'd love to work mostly upstream but we have some difficulties getting getting approvals and merges unfortunately for various reason. For example the PR for ROCM5.2 support has been bouncing around since early July:
https://github.com/tensorflow/tensorflow/pull/56762]

That one will be needed if we want the CI to build on ROCM 5.2 or later.

**Comment by rahulbatra85** [comment]
I created an issue to track JAX ROCm CI development

**Pull request merged**
