### PR TITLE
add cond batching rule

### LINKED ISSUE #490: vmap support / batching rule for lax.cond
It would be great to have vmap support for `lax.cond` similar to the recently added vmap support for `lax.while_loop`. I know that I can use `np.where` as a workaround for some cases, but for computationally expensive if conditions a batched cond might be better.

### LINKED ISSUE #1120: Feature request: `vmap`-able boolean function options
I would like to write functions that take static options (associated with branching within the function) that are compatible with both `vmap` and `jit`. Some examples of things that currently work/don't work:

```python
def python_control_flow(x, option=False):
  return x**2 if option else x**3

vmap(python_control_flow)(np.arange(3))  # works
vmap(jit(python_control_flow))(np.arange(3))  # works
(lambda x: jit(python_control_flow)(x, True))(np.arange(3))  # doesn't work
vmap(jit(lambda x: python_control_flow(x, True)))(np.arange(3))  # works
vmap(python_control_flow, in_axes=(0, None))(np.arange(3), True)  # doesn't work

def cond_control_flow(x, option=False):
  return lax.cond(option, x, lambda x: x**2, x, lambda x: x**3)

cond_control_flow(np.arange(3))  # works
jit(cond_control_flow)(np.arange(3))  # doesn't work, https://github.com/google/jax/issues/1077
vmap(cond_control_flow)(np.arange(3))  # doesn't work
vmap(jit(cond_control_flow))(np.arange(3))  # doesn't work
vmap(cond_control_flow, in_axes=(0, None))(np.arange(3), True)  # doesn't work
```

It seems that for the best compatibility with `jit` the `lax.cond` control flow is preferable, perhaps with a wrapper, e.g.,
```python
@jit
def _cond_control_flow(x, option):
  return lax.cond(option, x, lambda x: x**2, x, lambda x: x**3)

def cond_control_flow(x, option=False):
  return _cond_control_flow(x, option)
```
to avoid https://github.com/google/jax/issues/1077, but no approach along these lines is currently compatible with a `vmap` down the line due to `NotImplementedError: Batching rule for 'cond' not implemented`.

### PR DESCRIPTION
**Pull request by jekbradbury**
Covers both the predication (batched condition) and unbatched condition cases.

Fixes #490; may also fix #1120.

### CODE REVIEW

**Review by mattjj — COMMENTED** [review]
Summary of a discussion we had offline: this implementation is raising everything into the batch tracer, which means for example that when computing per-example gradients we'd create `batch_size` copies of the parameters. More generally, this might cost a lot of memory!

The more conservative thing to do is not to raise everything into the batch tracer, but that means having to join the outputs of the two sides of the `cond`.

**Comment by shoyer** [comment]
What about batching via `lax.map`?

**Comment by jekbradbury** [comment]
Apparently the right kind of lattice join is already being invoked in the right place, so the updated implementation both (a) works and (b) raises to the batch tracer only when necessary, even though the actual batch rule doesn't do any raising at all. (Earlier, I was cargo-culting off of the `while_loop` batching rule, which does need to do these things because there's no generic lattice join being called in `while_loop` itself).

**Comment by mattjj** [comment]
Whoa! Do you mean the lattice join in [this code](https://github.com/google/jax/blob/a6ec5a916cae5b71e0232633b89e7490f77d81ef/jax/interpreters/partial_eval.py#L317) or elsewhere? How did you figure out that it wasn't doing any extra raising?

**Pull request closed without merging**
