### PR TITLE
apply is_stable=True to sort translation rules

### LINKED ISSUE #2779: Expose stable flag on XLA sort
XLA's sort HLOs have an "is_stable" attribute, which defaults to false; in practice, the sort used on CPU is stable but the one on GPU isn't. This means that e.g. this code will fail on GPU:
```python
x = onp.array([5, 1, 2, 6, 5, -2, 2, 0, 0, 1, 0, 4])
assert jnp.argsort(x) == onp.argsort(x)
```
and #2760 won't match NumPy behavior (ties to earliest) either.

### PR DESCRIPTION
**Pull request by mattjj**
fixes #2779

### CODE REVIEW

**Review by jekbradbury — APPROVED** [review]
Only thing I'd be afraid of is performance regressions, but honestly there's not much we can do to identify those until we have a good benchmark suite.

**Comment by mattjj** [comment]
Thank you, @jekbradbury ! And good point. We can add it as a parameter if needed.

Verified internal tests pass! Since that's a superset of Travis, I'll merge.

**Comment by hawkinsp** [comment]
You need to bump the minimum jaxlib version too since this is a backward incompatible change.

**Comment by mattjj** [comment]
Whoops, good catch. I forgot about doing that!

**Comment by mattjj** [comment]
Done in 6239e594.

**Comment by mattjj** [comment]
Except I forgot to update .travis.yml in that... fixed!

**Pull request merged**
