### PR TITLE
Update xmap guide - add jit/shard_map note

### PR DESCRIPTION
**Pull request by 8bitmp3**
Adds a note to the `xmap` guide:

> UPDATE: The recommended ways to do multi-device programming in JAX are using: 1) `jit` (automatic partitioning of computation and `jax.Array` sharding); and/or 2) `shard_map` (manual data sharding). Learn more in Why don’t `pmap` or `xmap` already solve this? in the `shard_map` JEP document.

### CODE REVIEW

**Comment by 8bitmp3** [comment]
@jakevdp

**Comment by jakevdp** [comment]
Content looks good, but there are documentation build warnings:
```
/home/docs/checkouts/readthedocs.org/user_builds/jax/checkouts/18022/docs/notebooks/xmap_tutorial.ipynb:10004: ERROR: Document or section may not begin with a transition. I think this comes from starting the section with an hline.
```

**Comment by 8bitmp3** [comment]
@jakevdp

**Review by jakevdp — CHANGES_REQUESTED** [review]
Looks good – thanks! Can you squash the changes into a single commit? Then we'll get this merged!

**Review by jakevdp — APPROVED** [review]
LGTM!

**Comment by jakevdp** [comment]
Oops, looks like the notebook and the md got out of sync. The easiest way to fix that is to run `pre-commit run jupytext`

**Pull request merged**
