### PR TITLE
Consolidation of hipsolver/cusolver APIs.

### PR DESCRIPTION
**Pull request by rsanthanam-amd**
/cc @jakevdp

### CODE REVIEW

**Review by jakevdp — APPROVED** [review]
Looks great!

Quick question - I'm looking into adding some wrappers for [cusolver-sparse](https://docs.nvidia.com/cuda/cusolver/index.html#cuSolverSP-intro). Does hipsparse implement those routines?

**Comment by jakevdp** [comment]
Also please rebase & fix conflicts. Thanks!

**Comment by rsanthanam-amd** [comment]
> Also please rebase & fix conflicts. Thanks!

Done!

**Comment by rsanthanam-amd** [comment]
> Looks great!
> 
> Quick question - I'm looking into adding some wrappers for [cusolver-sparse](https://docs.nvidia.com/cuda/cusolver/index.html#cuSolverSP-intro). Does hipsparse implement those routines?

My apologies but I am unable to correlate with hipsparse.  Perhaps, could you post a specific API call as an example?

**Comment by jakevdp** [comment]
Sure, for example does hipsparse have any equivalent of [csrlsvlu](https://docs.nvidia.com/cuda/cusolver/index.html#cusolver-lt-t-gt-csrlsvlu)?

**Comment by jakevdp** [comment]
Thanks for cleaning up the history. Could you rebase your changes into a single commit? (See https://jax.readthedocs.io/en/latest/contributing.html#single-change-commits-and-pull-requests)

**Comment by rsanthanam-amd** [comment]
> Thanks for cleaning up the history. Could you rebase your changes into a single commit? (See https://jax.readthedocs.io/en/latest/contributing.html#single-change-commits-and-pull-requests)

I think I did it correctly this time.

**Comment by rsanthanam-amd** [comment]
> 

Unfortunately, we do not ATM.

**Comment by rsanthanam-amd** [comment]
> Sure, for example does hipsparse have any equivalent of [csrlsvlu](https://docs.nvidia.com/cuda/cusolver/index.html#cusolver-lt-t-gt-csrlsvlu)?

Unfortunately, we do not ATM.

**Pull request merged**
