### PR TITLE
chore: move configurations to `pyproject.toml`

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
Similar to:

* https://github.com/google/flax/pull/2960 <- (https://github.com/google/flax/pull/2955)

### CODE REVIEW

**Comment by jakevdp** [comment]
Thanks! It looks like the settings are not being correctly applied in the case of the mypy pre-commit job. Is this something you know how to fix?

**Comment by SauravMaheshkar** [comment]
Thanks for the prompt reply, I think fb2cad20a855692fb618707105b49d322f709054 should fix it. I had accidentally placed all modules under the `ignore_missing_imports` section, whereas some of them were `ignore_errors`.

**Comment by jakevdp** [comment]
Looks like some more iteration is necessary. FYI you can run the pre-commits locally with
```
pip install pre-commit
pre-commit run mypy --all-files
```
That might make for quicker iteration on the fix.

**Comment by SauravMaheshkar** [comment]
903cffe41416d530361fcfddf2bbf1a97737eb6c should fix it

**Comment by jakevdp** [comment]
Thanks! Looks like everything passes now. Last thing: would you mind squashing your changes into a single commit? (see https://jax.readthedocs.io/en/latest/contributing.html#single-change-commits-and-pull-requests) it helps keep the commit history clean. Thanks!

**Comment by SauravMaheshkar** [comment]
Squashed 👍🏽

**Review by jakevdp — APPROVED** [review]
Thanks!

**Pull request merged**
