### PR TITLE
Make jax `wraps` preserve signatures

### PR DESCRIPTION
**Pull request by romanngg**
Currently when using the below sample in Colab
```
import jax

def f(x):
  return x

f_jit = jax.jit(f)
```

the signature of `f_jit` and similar wrappers is `f_jit(*args, **kwargs)`. This change should propagate the signature from `f` to `f_jit`. This is python3-only

### CODE REVIEW

**Comment by shoyer** [comment]
Do you know why we can't just use functools.wraps here?

**Comment by mattjj** [comment]
I can't remember! Maybe there was an issue with `functools.wraps` handling `functools.partial` instances? But perhaps we should try replacing this with `functools.wraps` and see if anything breaks...

In particular, we could try something like

```python
@curry
def wraps(wrapped, fun, namestr="{fun}", docstr="{doc}", **kwargs):
  f = functools.wraps(wrapped)(fun)
  try:
    ... # use namestr, docstr
  finally:
    return f
```

**Comment by mattjj** [comment]
@romanngg you up for trying to replace most of this functionality with a call to `functools.wraps`? I'm cautiously optimistic that it'll work because we're all Py3 now.

**Comment by romanngg** [comment]
Thank you for the suggestions! I've updated the code, a few comments:

1) `functools.wraps` does not seem to transfer the signature, but rather only transfers some attributes like the ones you are transferring currently in the code. Therefore I still suggest to add the signature transfer line, but perhaps I'm misunderstanding something about it...

2) The code currently (prior to this PR) does not use `functools.wraps` potentially because it is designed to mutate an existing object, see the call here: https://github.com/google/jax/blob/28e802c6f15d7ed87fee9bee6270137423b9967c/jax/api.py#L1428

3) I've also made the `util.partial` have the correct signature as well through inspections. Prior it was using a `functools.wraps` and `_bound_arg` attribute which I'm not sure is being used anywhere? Correct me if I'm wrong.

4) In Pycharm there's still an issue with resolving the signature of a jitted function, but I think it's their bug: https://youtrack.jetbrains.com/issue/PY-40548

**Comment by shoyer** [comment]
> * `functools.wraps` does not seem to transfer the signature, but rather only transfers some attributes like the ones you are transferring currently in the code. Therefore I still suggest to add the signature transfer line, but perhaps I'm misunderstanding something about it...

`functools.wraps` sets the `__wrapped__` attribute, which indicates the original wrapped function providing the function signature. The utilities in `inspect` know how to follow this, and in my experience it seems to be sufficient for IDEs (e.g., we now use it on nearly every function in in NumPy).

It seems relatively harmless, but I'm not sure what benefit we get from explicitly setting `__signature__`.

**Comment by romanngg** [comment]
Thanks Stephan, I'm curious, what IDEs do you have in mind? I'm using Colab and Pycharm/IntelliJ, and neither seem to properly treat this code:
```
import functools
def f(x): return x

@functools.wraps(f)
def g(*args, **kwargs):
  return f(*args, **kwargs)
```
each hinting at the signature of `g` as `g(*args, **kwargs)`...

**Comment by shoyer** [comment]
Interesting, you're right that Colab doesn't do this (but IPython does). I filed Google internal bug b/149327475 about this.

**Comment by romanngg** [comment]
Thanks, I've copied your report to IntelliJ too: https://youtrack.jetbrains.com/issue/PY-40569

**Comment by jakevdp** [comment]
I believe the intent of this was fixed by #5680

**Pull request closed without merging**
