### PR TITLE
(hopefully) fix broken link

### PR DESCRIPTION
**Pull request by jamestwebber**
Removed extra bracket

### CODE REVIEW

**Comment by jamestwebber** [comment]
@googlebot I signed it!

**Comment by jakevdp** [comment]
Thanks! The same change will have to be made in the markdown version (see https://jax.readthedocs.io/en/latest/developer.html#syncing-notebooks)

**Comment by jamestwebber** [comment]
Okay, because this was so tiny I just synced it via an edit in github (I haven't cloned the repo locally).

**Review by jakevdp — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
