### PR TITLE
Address nan issue in zeta

### LINKED ISSUE #3758: jax.scipy.special zeta sometimes returns NaN
For large values of z, `jax.scipy.special.zeta` returns NaN when it should instead return 0.:

`jax.scipy.special.zeta(1e5, q=1.)`  # Return NaN.

Note: I suspect TF and Scipy have this same issue:

`sp.zeta(1e19, 40.)`   # Returns NaN in Scipy. I have to use a large value because Scipy is using internal float64 calculations.

`tf.math.zeta(1e10, q=30.)`  # Returns NaN in TF

### PR DESCRIPTION
**Pull request by fehiepsi**
Fixes #3758.

### CODE REVIEW

**Comment by hawkinsp** [comment]
@srvasude would you mind taking a look? Thanks!

**Comment by jakevdp** [comment]
This seems like a reasonable fix to me. One question: should we add a similar fix for large negative values? for example:
```python
>>> from jax.scipy.special import zeta
>>> zeta(-100.0, 1.0)
/usr/local/lib/python3.6/dist-packages/jax/scipy/special.py:205: RuntimeWarning: overflow encountered in float_scalars
  I = lax.div((a + N) ** (dtype(1) - s), s - dtype(1))
/usr/local/lib/python3.6/dist-packages/jax/scipy/special.py:206: RuntimeWarning: overflow encountered in float_scalars
  T0 = (a + N) ** -s
DeviceArray(nan, dtype=float32)
```

**Comment by fehiepsi** [comment]
I think the implement here only takes care of `x > -15` (according the reference, it is only valid when (s + 2M - 1 > 0)) and scipy only deals with case `x >= 1`. The negative domain is not of interest I guess.

**Review by jakevdp — APPROVED** [review]

**Comment by jakevdp** [comment]
OK, thanks! Looks good to me. @hawkinsp any objection to merging?

**Review by hawkinsp — APPROVED** [review]

**Pull request merged**
