### PR TITLE
Update jax.scipy.special.gamma and gammasgn to return NaN for negativ…

### PR DESCRIPTION
**Pull request by hawkinsp**
…e integer inputs.

Change to match upstream scipy: https://github.com/scipy/scipy/pull/21827.

### CODE REVIEW

**Comment by jakevdp** [comment]
Looks good, but also looks like some unrelated changes snuck in?

**Comment by hawkinsp** [comment]
> Looks good, but also looks like some unrelated changes snuck in?

I don't think so? I'm now using `packaging.Version` for a version test.

**Comment by jakevdp** [comment]
> I don't think so? I'm now using `packaging.version` for a version test.

Is that necessary? In several other places we use the `jtu.parse_version` utility for that: https://github.com/jax-ml/jax/blob/65f9c7855e25f21935f00bed8c4e899d7be808ba/tests/lax_scipy_test.py#L39

**Comment by hawkinsp** [comment]
> > I don't think so? I'm now using `packaging.version` for a version test.
> 
> Is that necessary? In several other places we use the `jtu.parse_version` utility for that:
> 
> https://github.com/jax-ml/jax/blob/65f9c7855e25f21935f00bed8c4e899d7be808ba/tests/lax_scipy_test.py#L39

I think we can/should delete that utility, but ok let's save that for another change.

**Review by jakevdp — APPROVED** [review]

**Pull request merged**
