### PR TITLE
Retry connection errors to combat flakiness in google metadata server during tpu initialization

### PR DESCRIPTION
**Pull request by dlwh**
Google people can please reference b/374374269 for information.

### CODE REVIEW

**Comment by dlwh** [comment]
(cc @skye based on git blame)

**Comment by skye** [comment]
@gobbleturk this is fixed right? I believe this was somehow resolved on the Cloud TPU side. You may need to recreate your VMs, but Matt should confirm.

**Comment by dlwh** [comment]
Yeah my understanding is this has been mitigated. This change is now only for extra defensiveness in case it happens again, but isn't necessary. happy to just close it if you want.

**Comment by skye** [comment]
Yeah I'm gonna go ahead and close -- there's a lot to do and this did help up catch the issue. Let's revisit if the metadata server breaks another time or two :)

**Comment by dlwh** [comment]
@skye it broke again fwiw

**Pull request closed without merging**
