### PR TITLE
Add TensorFlow Datasets data-loading notebook

### PR DESCRIPTION
**Pull request by rsepassi**

### CODE REVIEW

**Comment by rsepassi** [comment]
@alexbw, before merging, let's decide whether to do the reshape in the TF pipeline (which requires `import tensorflow as tf`), or to keep it in NumPy (which removes the TF import).

**Comment by rsepassi** [comment]
Also, tested this only on CPU (i.e. commented out the pip install JAX whl and added `jaxlib` instead). @mattjj said that typically there's an error when you try to import both `jax` and `tensorflow`. Not using the whl may have been why I avoided it but I'm not sure.

**Comment by mattjj** [comment]
Wooo this is awesome! You guys are making "Unix for ML" a real thing!

**Comment by alexbw** [comment]
The stepsize should be 10x smaller, but I'll merge as is and make a small local change.

**Comment by alexbw** [comment]
I prematurely merged because I got so excited, I have now reverted.

Re: your "REVIEWER" comment: I like option #2, where the reshape is explicit but no tf import is required.

Also, I get an error running here (which is how we recommend people run the colab):
https://colab.sandbox.google.com/github/rsepassi/jax/blob/tfds/notebooks/neural_network_with_tfds_data.ipynb

Error:
```
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "tensorflow/compiler/xla/xla_data.proto":
  tensorflow/compiler/xla/xla_data.proto: A file with this name is already in the pool.
```

**Pull request merged**
