### PR TITLE
Make JAX tracer state thread-local. 

### LINKED ISSUE #1037: Make JAX thread-safe
Currently JAX is not thread-safe, as you can see in the following example:

```
import jax
from jax.experimental import stax
import threading
import jax.random as random

def create_net():
  init_fn, apply_fn = stax.Dense(10)
  key = random.PRNGKey(0)
  _, params = init_fn(key, input_shape=(-1, 5))
  return params, apply_fn

def f1():
  p1, apply_fn1 = create_net()
  x = random.normal(key, shape=(1, 5))
  return apply_fn1

def f2():
  p2, apply_fn2 = create_net()
  x = random.normal(key, shape=(1, 5))
  return apply_fn2

threads = []
t = threading.Thread(target=f1)
t.start()
threads.append(t)

t = threading.Thread(target=f2)
t.start()
threads.append(t)

for t in threads:
  t.join()

```

It has been increasing demand on requesting JAX to be thread-safe, could the developers consider it?

### PR DESCRIPTION
**Pull request by hawkinsp**
Allows tracing in separate threads (e.g., call `jit(f)` concurrently).

Using threading within a traced context still won't work, but that is perhaps less important than the ability to call JIT-ted computations from separate threads.

This change does not yet add any logic to attach thread IDs to tracers to ensure tracer/thread hygiene; that would be a sensible safety measure for a future change.

Revives https://github.com/google/jax/pull/734. Changes since last time:
* the LRU caches are now using `fastcache` which is thread safe.
* subclasses `threading.local`.

Fixes #1037

### CODE REVIEW

**Review by mattjj — APPROVED** [review]
Awesome! I'm not a threading expert but these changes LGTM.

There are at least two other places we might need to make global state into thread-local stuff:
1. for initial-style control flow, uses of `gensym` from partial_eval.py is done [with global state in some places](https://github.com/google/jax/blob/master/jax/lax/lax_control_flow.py#L763) (tangentially: I think [this one](https://github.com/google/jax/blob/master/jax/lax/lax_control_flow.py#L330) should be global for correctness)
2. for pmap, the [`dynamic_axis_env`](https://github.com/google/jax/blob/dd37f8c9611778766dae4aeaa40482e662724cfb/jax/interpreters/pxla.py#L264-L276) singleton data structure works analogously to the `trace_stack` data structure and maybe could receive the same treatment.

We could lock the rules tables too, though those are usually populated at import time and so maybe aren't an issue.

Does it make sense to make those changes in this PR? (Also: let me know if it's better for me to work on those things in a follow-up!)

**Comment by mattjj** [comment]
Here's something I'm not sure about: what about `api.disable_jit` and how it updates the `api._jit_is_disabled` module-level variable?

**Comment by hawkinsp** [comment]
PTAL:
* I made the API jit_disabled state thread-local. 
* I also made the pmap state thread-local.
* I made the gensym state thread-local too. Thread-local seemed sufficient because this is about name uniquification, but names are local to a jaxpr and I don't think these jaxprs cross thread boundaries.

**Comment by mattjj** [comment]
LGTM. I can't think of any other global state.

**Comment by hawkinsp** [comment]
Merging this without waiting for Travis because I realized my previous commit had a leftover line that meant it's going to deadlock. The tests pass locally with this PR.

**Pull request merged**
