### PR TITLE
List organizations using JAX

### PR DESCRIPTION
**Pull request by sandipantech**
Create ADOPTERS.md to list organizations using JAX in production or at stages of testing

### CODE REVIEW

**Comment by sandipantech** [comment]
cc @jakevdp @froystig for review, thoughts.

**Comment by sandipantech** [comment]
cc @superbobry

**Comment by hawkinsp** [comment]
We're not eager to add such a list to JAX's source repository because it seems like:
a) it will be a maintenance burden: we'll have to constantly update it and accept PRs adding to it.
a) it will always be out of date: there will be many people and organizations using JAX not on the list, either because they haven't gotten around to adding themselves or they don't want to announce what they are doing to the world. I'd expect only a small minority of users will add themselves.

So I think it would be better simply not to try.

What do you think?

**Comment by sandipantech** [comment]
I agree with your point. I have seen some cloud native open source projects by Google like [Knative](https://github.com/knative/community/blob/main/ADOPTERS.MD), [Kubeflow](https://github.com/kubeflow/community/blob/master/ADOPTERS.md), [Tekton](https://github.com/tektoncd/community/blob/main/adopters.md) do it, so I thought it might be a good practice.

**Comment by hawkinsp** [comment]
Ok! Thanks for the contribution, though!

**Pull request closed without merging**
