### PR TITLE
Add dtype arg to jnp.stack and friends

### LINKED ISSUE #11501: Add `dtype` argument to `jax.numpy.concatenate` and friends
`np.concatentate` got a `dtype` argument in numpy 1.20; other functions will get them in numpy 1.24.

- [ ] `np.concatenate`
- [ ] `np.stack`
- [ ] `np.vstack`
- [ ] `np.hstack`
- [ ] `np.row_stack`

There is also a `casting` argument that goes with this; for now we can probably ignore this because JAX's type promotion system does not have well-defined casting modes.

### PR DESCRIPTION
**Pull request by alonfnt**
Following the work of #11673, I thought it would be a good first issue to the library to finish it, since the changes are now fairly small.

Hopefully this PR closes #11501

### CODE REVIEW

**Review by jakevdp — APPROVED** [review]
Looks great, thanks for tackling this!

**Comment by jakevdp** [comment]
We ran into some test failures when trying to merge this, could you rebase against the main branch?

**Comment by alonfnt** [comment]
> We ran into some test failures when trying to merge this, could you rebase against the main branch?

I've rebased now, although it seems to be failing some internal CI build. I'm happy to fix any issue if its on my end :)

**Comment by jakevdp** [comment]
Thanks! Looks like the tensorflow update is causing some kokoro issues...

**Comment by jakevdp** [comment]
Thanks for the contribution!

**Pull request merged**
