### PR TITLE
Change all onp to np and np to jnp

### PR DESCRIPTION
**Pull request by joaogui1**
I saw a few commits stating that both `import numpy as onp` and `import jax.numpy as np` are depracated and we should use the classic `import numpy as np` and `import jax.numpy as jnp`, so the idea of this PR is to correct the import across all the codebase.
Is there interest in it? Is there a reason not to do it?
Pinging @gnecula as the commits I referenced are his

### CODE REVIEW

**Comment by gnecula** [comment]
This looks good. I can approve it if you turn the draft mode off. Thanks!

**Comment by joaogui1** [comment]
So, I think I will first remove all the other mentions of `onp`, then I turn off draft mode

**Comment by hawkinsp** [comment]
You might find it easier to send several smaller PRs rather than one giant PR; the bigger the PR, the larger the chance of it getting stale because of other PRs merged in the meantime.

**Comment by joaogui1** [comment]
Good idea @hawkinsp, thanks

**Comment by shoyer** [comment]
Another place where this needs to be fixed in the README (but in a separate PR to avoid conflicts!)

**Comment by joaogui1** [comment]
Can someone merge this please?

**Comment by hawkinsp** [comment]
Thanks for the PR!

**Pull request merged**
