### PR TITLE
Require ml_dtypes>=0.2

### PR DESCRIPTION
**Pull request by jakevdp**
Also clean up a number of related checks

### CODE REVIEW

**Comment by yashk2810** [comment]
Note that you will have to update the dockerfiles too to get the kokoro builds to pass.

**Comment by yashk2810** [comment]
How are the kokoro builds passing? Don't they need to be rebuilt so that they get ml_dtypes 0.2?

**Comment by yashk2810** [comment]
I see, then my recent build would have updated it.

**Review by yashk2810 — APPROVED** [review]
Add it to Changelog.md please?

**Comment by jakevdp** [comment]
> Add it to Changelog.md please?

Done.

**Pull request merged**
