### PR TITLE
Fix Typo in argument description of `jax.numpy.linalg.matrix_rank`

### LINKED ISSUE #22135: Argument mismatch in `jax.numpy.linalg.matrix_rank` documentation.
I've found the following error in the documentation of `jax.numpy.linalg.matrix_rank`:https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.linalg.matrix_rank.html 

The function `jax.numpy.linalg.matrix_rank` has only 3 arguments - `M, rtol, tol` in its definition. However the argument description describes about 4 arguments - `a, rtol, M, tol`.

### PR DESCRIPTION
**Pull request by rajasekharporeddy**
Fixes #22135

### CODE REVIEW

**Comment by jakevdp** [comment]
In numpy the argument is called `A`: https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_rank.html

In the array API it's positional only, so the name doesn't matter: https://data-apis.org/array-api/2022.12/extensions/generated/array_api.linalg.matrix_rank.html

To be honest, this deprecation seems like unnecessary churn. We could fix the doc issue by changing `a` to `M` in line 406: https://github.com/google/jax/blob/98b87540a76bc3b4f9f414bb763304f1cc474544/jax/_src/numpy/linalg.py#L406

**Comment by rajasekharporeddy** [comment]
Thanks! Changed `a` to `M` in argument description and changed the title.

**Comment by jakevdp** [comment]
Yeah, I think that's good. Squash the changes and we can merge this!

**Comment by rajasekharporeddy** [comment]
Squashed

**Review by jakevdp — APPROVED** [review]
Thanks!

**Pull request merged**
