### PR TITLE
Fix duplicate word occurrences

### PR DESCRIPTION
**Pull request by jhrcek**

### CODE REVIEW

**Review by jakevdp — APPROVED** [review]
Thanks!

**Comment by jakevdp** [comment]
It looks like `autodidax.ipynb` needs the same change as the associated `md` and `py` files.

**Comment by jhrcek** [comment]
Oh, I missed that. Fixed. This time I did more thorough search using this magical regex `\b(\w+)\b \b\1\b` and fixed bunch of other places too :smile:

**Comment by jakevdp** [comment]
Thanks! It looks like there are some conflicts in this branch – can you fix those, and then also rebase your changes into a single commit? (see https://jax.readthedocs.io/en/latest/contributing.html#single-change-commits-and-pull-requests) Thanks!

**Comment by jhrcek** [comment]
Rebased and changes squashed to single commit.

**Review by jakevdp — APPROVED** [review]
Thanks!

**Pull request merged**
