### PR TITLE
Batching rule for custom_linear_solve

### PR DESCRIPTION
**Pull request by danieldjohnson**
This PR adds a batching rule for `custom_linear_solve` by batching each of the jaxprs stored in the underlying primitive. Conceptually, this corresponds to transforming the initial linear system into an implicit "block diagonal" system, where `matvec`/`vecmat` apply a linear operation to each part of the input, and `solve`/`transpose_solve` solve each block separately.

Note that the batching of the input and output must agree between all four jaxprs, since the `custom_linear_solve` JVP and transpose rules assume the shapes all match. In particular, the JVP passes the output of `solve` into (the JVP of) `matvec` and then that output back into `solve`, and the transpose rule causes the (cotangents for the) output of `solve` to be fed back into `solve_transpose`  (and then `vecmat` if there are higher dimensional derivatives). To ensure consistency we can do a fixed-point iteration to figure out whether each component of x and b are batched or not.

(This fixed point logic is really only relevant if the vector space we are operating over is a pytree with interesting dependency structures, since otherwise the output is almost certainly batched. I've added a test that does a matvec and a solve over Python lists of scalars to make sure this works as expected.)

### CODE REVIEW

**Comment by shoyer** [comment]
This generally looks good to me, though I don't really understand the fixed point calculation yet :)

**Comment by hexahedria** [comment]
I based the fixed point computation on [the one for `while_loop`](https://github.com/google/jax/blob/58f949f3168ebdc0264448022f90ba8271746356/jax/lax/lax_control_flow.py#L279). I think the principle is the same, but it's more indirect in this case (since for `while_loop` it's only a single jaxpr that has to accept its own output).

**Comment by shoyer** [comment]
LGTM, though I don't have much experience with JAX's batching rules.

I am inclined to merge soon and try it out. Currently batching is broken, so in the worst case we just discover that it is still broken (I think errors are much more likely than silently wrong results here).

There is some high impact follow-on work here using this inside `jax.scipy.linalg.solve` and `jax.numpy.linalg.solve` that I think should be enabled by this PR: https://github.com/google/jax/issues/1747. Let me know if you're interested in giving that a try, it would also be a very good exercise of all the edge cases here to use it inside `solve`.

@mattjj any thoughts?

**Review by mattjj — APPROVED** [review]
LGTM! Fantastic technical work here; you really dove into the deep end!

We've been wondering recently, based on @shoyer's prodding and thinking about others who want to add higher-order primitives (like for ODE integration, numerical fixed point computation, etc.), whether we can better reuse existing machinery for cases like this one. That is, can we somehow just rely on the batching logic for generic while loops, rather than writing special logic for these other higher-order primitives (which may only need to be primitives for autodiff purposes)? Two options seem to be improved custom JVPs, as in #2026 (but it's not looking good that we can solve this problem that way, for tracing mechanism reasons...), and just factoring out better utility functions in these implementations.

If we ever crack that nut, we'll be able to simplify some of the code in this file. But that has consequences beyond just `custom_linear_solve`, and it's for another day. I just wanted to prime anyone reading this with those ideas!

**Comment by mattjj** [comment]
Also, @hexahedria that is a great PR comment! I love the (block) diagonal perspective.

**Comment by shoyer** [comment]
Ah, I get this now -- very nice how this allows only batching one block of outputs!

**Comment by shoyer** [comment]
Thank you @hexahedria !

**Comment by hexahedria** [comment]
Glad I could help!

@mattjj On the topic of better utility functions, I was thinking about how there seem to be commonalities between the batching functions for various control-flow-like primitives. In particular it seems like many of these primitives consist of one or more stored jaxprs that obey type constraints; for while, the jaxpr is something like `a -> a`, for cond its something like `(a->c), (b->c)`, for custom_linear_solve it's `{matvec :: (x->y), solve :: (y->x), vecmat :: (y->x), transpose_solve :: (x->y)}` (and I guess there's also an input to each for the closed-over constants). Batching then seems kind of like doing type inference, where you put constraints on the batch dimensions of the inputs and figure out what the batching strategies should be for each of the type variables.

I wonder if there's something there that could be factored out to make a more generic solution for batching of primitives? One possible interface could look like:

```
def _linear_solve_batching_rule(...):
  # ... unpack things from parameters ...
  batched_jaxpr_list, name_to_dims_map = jointly_batch_jaxprs(
    values=[(b_dims, "b")],
    jaxprs=[
      (matvec_jaxpr, matvec_const_dims, "x->b"),
      (solve_jaxpr, solve_const_dims, "b->x"),
      (vecmat_jaxpr, vecmat_const_dims, "b->x"),
      (solve_t_jaxpr, solve_t_const_dims, "x->b"),
    ]
  )
  new_b = ensure_batched(b, name_to_dims_map["b"])
  out_dims = name_to_dims_map["x"]
  return linear_solve_p.bind(*consts, *new_b, ...), out_dims
```
or
```
def _while_loop_batching_rule(...):
  # ...
  batched_jaxpr_list, name_to_dims_map = jointly_batch_jaxprs(
    values=[(init_dims, "carry")],
    jaxprs=[
      (cond_jaxpr, cond_const_dims, "carry->pred"),
      (body_jaxpr, body_const_dims, "carry->carry"),
    ]
  )
  new_init = ensure_batched(init, name_to_dims_map["carry"])
  out_dims = name_to_dims_map["carry"]
  return while_p.bind(*consts, new_init, ...), out_dims
```

I'd be curious to see if this kind of interface would work well for other primitives, and whether it would play nicely with the custom JVP work (maybe custom JVP batching would turn out to be a special case of this kind of analysis, instead of the other way around? I haven't really thought about it very much, but it seems plausible.)

**Pull request merged**
