### PR TITLE
Implementation of np.linalg.tensorsolve.

### PR DESCRIPTION
**Pull request by Guillem96**
According to issue #1999 I implemented the currently missing `np.linalg.tensorflow`.

To test my implementation (coming from [here](https://github.com/numpy/numpy/blob/v1.10.4/numpy/linalg/linalg.py#L227-L294)) I developed a unit test called `testTensorsolve`. The test covers the implementation calling the method with tensors of various dimentions and shapes.

### CODE REVIEW

**Review by jekbradbury — APPROVED** [review]

**Comment by jekbradbury** [comment]
This looks good, but I think it'll have to wait for us to figure out what to do with code copied directly from NumPy (it may need to be in a `jax/third_party/...` directory, in which case we'll need to set that up)
CC @shoyer

**Comment by jekbradbury** [comment]
Oops, didn't see that https://github.com/google/jax/pull/2125 is already creating that third_party directory. Once that goes in, @Guillem96, can you move your code into the directory from that PR?

**Comment by Guillem96** [comment]
Okey no problem. Let me know when it is done

**Comment by Guillem96** [comment]
@shoyer @jekbradbury what's the status of the `third_party` directory? Thanks 😊

**Comment by shoyer** [comment]
I just merged the `third_party` directory with https://github.com/google/jax/pull/2125. Please merge in `master` into your branch.

**Comment by Guillem96** [comment]
Done. I moved my implementation under third_party directory.

**Comment by shoyer** [comment]
Thanks!

**Pull request merged**
