### PR TITLE
Stax: Make elemwise a public function.

### PR DESCRIPTION
**Pull request by aslanides**
This is useful for making layers that do simple preprocessing e.g. re-scaling inputs.

### CODE REVIEW

**Comment by aslanides** [comment]
@zhongwen

**Comment by zhongwen** [comment]
It's very useful for users to utilize the elementwise function to create their own layers.

**Review by mattjj — COMMENTED** [review]
Would you mind making the name `elementwise` rather than `elemenwise`? Otherwise SGTM.

**Comment by aslanides** [comment]
Done. PTAL.

**Review by mattjj — APPROVED** [review]
Thanks!

**Pull request merged**
