### PR TITLE
Add PyPI version badge to README.

### PR DESCRIPTION
**Pull request by aslanides**

### CODE REVIEW

**Comment by aslanides** [comment]
Renders like this:

image

**Comment by jakevdp** [comment]
I've always used shields.io for this; e.g. https://img.shields.io/pypi/v/jax:

jax pypi version

Do you have strong feelings on whether fury.io is more stable? (I don't have strong feelings either way, just curious!)

**Comment by jakevdp** [comment]
Actually, now that I look at it, shields.io, unlike fury.io, is not for profit, fully open source (https://github.com/badges/shields) and badges have a CC0 license. I'd lean toward using shields.io badges.

**Comment by aslanides** [comment]
> Actually, now that I look at it, shields.io, unlike fury.io, is not for profit, fully open source (https://github.com/badges/shields) and badges have a CC0 license. I'd lean toward using shields.io badges.

Ah, I wasn't aware of that. Have made the change -- thanks!

**Comment by jakevdp** [comment]
Thanks!

**Pull request merged**
