### PR TITLE
[NVIDIA] Cudnn dot_product_attention supports head size up to 256

### PR DESCRIPTION
**Pull request by kaixih**
Since [cudnn v9.5.0](https://docs.nvidia.com/deeplearning/cudnn/latest/release-notes.html#cudnn-9-5-0), the larger head dim of 256 is supported. This PR enables this improvement.

This PR depends on https://github.com/openxla/xla/pull/18839 and https://github.com/openxla/xla/pull/18840

cc. @Cjkkkk

### CODE REVIEW

**Comment by kaixih** [comment]
@superbobry @hawkinsp Can you help take a look? The dep PRs in the description have already been merged. So, this one is ready.

**Review by superbobry — APPROVED** [review]

**Comment by superbobry** [comment]
Can you rebase please?

**Comment by kaixih** [comment]
@superbobry  Rebased. PTAL.

**Review by superbobry — APPROVED** [review]

**Comment by superbobry** [comment]
`DotProductAttentionTest.test_sdpa_large_head_size` is failing on our internal CI. Does this repro for you locally?

**Comment by kaixih** [comment]
@superbobry Yes, I can repro. The `DotProductAttentionTest.test_sdpa_large_head_size` should only be run on Hopper+ GPUs. New change is added. PTAL.

**Comment by kaixih** [comment]
Squash the commits.

**Review by superbobry — APPROVED** [review]

**Pull request merged**
