### PR TITLE
[BUG] Associative scan regression

### PR DESCRIPTION
**Pull request by AdrienCorenflos**
This PR now only includes a test to reproduce a problem which arises when using linalg.solve or linalg.lu from within the associative scan operation.

### CODE REVIEW

**Comment by hawkinsp** [comment]
The issue should now be fixed; I added a more specific unit test. If you wanted to add this test as well as a regression test, that'd be great! You'd need to clean up the PR a little bit, e.g., currently it reformats the whole test file; it should only add a new test case and not touch unrelated lines.

**Comment by AdrienCorenflos** [comment]
Thanks for the fix Peter. Indeed, I configured auto pep8 on commit in PyCharm, didn't think about the fact JAX doesn't follow it. I'll need to revert and deactivate it prior to committing again. Apologies!

**Comment by AdrienCorenflos** [comment]
Merged and updated

**Comment by hawkinsp** [comment]
I slightly improved this test case in https://github.com/google/jax/pull/6741, by (a) squashing the commits, and (b) reducing the number of test cases. ~100 test cases is too many.

(I'm assuming you won't mind me merging it via my own PR, it seemed easier than going back and forth on tiny improvements to a test.)

**Pull request closed without merging**
