### PR TITLE
[shard-map] add systematic vmap-of-shmap tests

### PR DESCRIPTION
**Pull request by mattjj**
Follow-up on #14513 (and #14550)

### CODE REVIEW

**Review by yashk2810 — APPROVED** [review]
Should we wait for Marcello's reply on the pxla.py change?

**Comment by mattjj** [comment]
> Should we wait for Marcello's reply on the pxla.py change?

No I'm already blocked on one XLA bug, don't want to block on another :P I'll leave a TODO(mattjj)

**Comment by yashk2810** [comment]
> No I'm already blocked on one XLA bug, don't want to block on another

Ohh.. I was saying maybe we wait for his reply (lol) to see if this is actually correct.

We should fix this in python until HloSharding gets fixed. That's fine by me.

**Comment by mattjj** [comment]
Well given the test case here I know the OpShardings in question represent replicated shardings.

**Comment by mattjj** [comment]
Following up on the comment thread: it was an XLA bugs that these MANUAL shardings propagated to outputs!

**Pull request merged**
