### PR TITLE
Adding info to CG and BICGSTAB

### PR DESCRIPTION
**Pull request by botev**

### CODE REVIEW

**Review by froystig — APPROVED** [review]
Thanks for the PR!

**Comment by froystig** [comment]
I reviewed and merged this PR prior to recalling that we had some discussion (and draft PRs) on this topic in the past, involving @shoyer @jakevdp @PhilipVinc @nicholasjng and others. Some related threads: #6490, #7825, #7909.

**Comment by froystig** [comment]
Also tagging #14249, which seems to be a bug revealed by this change in combination with jaxopt.

**Comment by nicholasjng** [comment]
> I reviewed and merged this PR prior to recalling that we had some discussion (and draft PRs) on this topic in the past, involving @shoyer @jakevdp @PhilipVinc @nicholasjng and others. Some related threads: #6490, #7825, #7909.

Thanks for the tag! I think I'm pretty sure I wrote the code for aux support in the `custom_linear_solve` batching rule that was mentioned in #14249, let me know if you need anything from my end.

**Pull request merged**
