### PR TITLE
Don't AD through max-subtraction in softmax

### PR DESCRIPTION
**Pull request by jekbradbury**
The max-subtraction doesn't change derivatives, so taking the gradient through it is just unnecessary computation. There is also an issue with grad-of-max that might be worth solving separately (it relies on exact bitwise equality of two versions of the stored max that can be broken by certain XLA optimizations).

(Going to also try doing this in logsumexp, where I'm less confident that it won't change derivatives.)

### CODE REVIEW

**Review by mattjj — APPROVED** [review]
LGTM, but is it possible to add tests for any improved numerics here? Also might be good to add a comment explaining why the stop_gradient is present.

**Comment by jekbradbury** [comment]
The numerics shouldn't change on CPU/GPU. We could easily test the jaxpr/HLO though?

**Comment by mattjj** [comment]
Hm whatever you think is best. "No tests" is fine with me. (Is there test coverage that these gradients are numerically correct? I ask because use of stop_gradient could in principle break that.)

**Comment by fehiepsi** [comment]
@jekbradbury I have faced NaN issue in *fast-math* mode of this op for half a year (in [this example](https://github.com/pyro-ppl/numpyro/blob/master/examples/neutra.py#L40)). [Here](https://github.com/google/jax/issues/939) is my early attempt to submit a repro script but it passed in recent JAX releases. However, the NaN issue still happens in that example. Now, I see your PR and try to apply this `stop_gradient` trick - the issue no longer appears. Could you make the change in logsumexp too? :D Thanks in advance!

cc @neerajprad

**Comment by fehiepsi** [comment]
Any chance this gets merged. I think we can add those special functions to [this test](https://github.com/google/jax/blob/master/tests/lax_scipy_test.py#L58) to check for gradient.

**Comment by jekbradbury** [comment]
Sorry I dropped the ball on this. It looks like this is a significant performance improvement for transformer-like models, and it passes internal tests, so I'm merging.

**Comment by fehiepsi** [comment]
Thanks, @jekbradbury! We also found that this is really helpful.

**Pull request merged**
