### PR TITLE
Annotate custom_vjp and custom_jvp

### PR DESCRIPTION
**Pull request by NeilGirdhar**

### CODE REVIEW

**Comment by shoyer** [comment]
mypy does not need seem to like these annotations, unfortunately.

**Comment by NeilGirdhar** [comment]
@shoyer What errors are you seeing?  It works on my end, except for this problem: https://github.com/python/mypy/issues/10299

**Comment by shoyer** [comment]
> @shoyer What errors are you seeing? MyPy passes on my code using these annotations, except for this problem: [python/mypy#10299](https://github.com/python/mypy/issues/10299).

I'm noting the "lint_and_typecheck" continuous integration failure:
```
jax/_src/lax/control_flow.py:2069: error: Argument 1 to "defjvp" of "custom_jvp" has incompatible type "Callable[[Any, Any, Any, Any], Any]"; expected "Callable[[Tuple[Any, ...], Tuple[Any, ...]], Tuple[ReturnValue, ReturnValue]]"  [arg-type]
jax/custom_derivatives.py:159: error: Incompatible types in assignment (expression has type "Callable[[Tuple[Any, ...], Tuple[Any, ...]], Tuple[ReturnValue, ReturnValue]]", variable has type "None")  [assignment]
jax/custom_derivatives.py:414: error: Name 'Optional' is not defined  [name-defined]
jax/custom_derivatives.py:414: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Optional")
jax/custom_derivatives.py:415: error: Name 'Optional' is not defined  [name-defined]
jax/custom_derivatives.py:415: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Optional")
jax/_src/numpy/linalg.py:316: error: Argument 1 to "defjvp" of "custom_jvp" has incompatible type "Callable[[Any, Any, Any], Any]"; expected "Callable[[Tuple[Any, ...], Tuple[Any, ...]], Tuple[ReturnValue, ReturnValue]]"  [arg-type]
jax/_src/numpy/lax_numpy.py:1074: error: Argument 1 to "defjvp" of "custom_jvp" has incompatible type "Callable[[Any, Any, Any], Any]"; expected "Callable[[Tuple[Any, ...], Tuple[Any, ...]], Tuple[ReturnValue, ReturnValue]]"  [arg-type]
jax/_src/scipy/special.py:234: error: Argument 1 to "defjvps" of "custom_jvp" has incompatible type "None"; expected "Callable[..., Any]"  [arg-type]
jax/_src/scipy/special.py:598: error: Argument 1 to "defjvp" of "custom_jvp" has incompatible type "Callable[[Any, Any, Any], Any]"; expected "Callable[[Tuple[Any, ...], Tuple[Any, ...]], Tuple[ReturnValue, ReturnValue]]"  [arg-type]
Found 8 errors in 5 files (checked 176 source files)
```

**Comment by NeilGirdhar** [comment]
@shoyer Oh, sorry for not checking that output myself! I think I might have fixed the problems, but let's see.

By the way, I noticed that `custom_jvp.defjvps` doesn't document passing `None`.

**Comment by NeilGirdhar** [comment]
@shoyer Is this okay with you?

**Comment by NeilGirdhar** [comment]
Thank you!!

**Pull request merged**
