### PR TITLE
fix PEP 561 problems in jax.numpy init file

### PR DESCRIPTION
**Pull request by machineko**
Add simple fix for problem with PEP 561 considering this document [document](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md)
"In particular, imported symbols are not assumed to be re-exported unless they appear in __all__ or use a redundant form of import"

autocompletion before fix

jaxautocompl

after fix
after

### CODE REVIEW

**Comment by machineko** [comment]
#7762

**Comment by jakevdp** [comment]
Thanks! We were discussing this in #7570, but I think the preferred fix would be explicit imports, to avoid ambiguity in whether the lists are synced; see https://github.com/google/jax/pull/7606.

**Comment by machineko** [comment]
Ahh didnt see that was looking for autocomplete and stuff like that 😄

**Comment by jakevdp** [comment]
I've stalled on merging that because I hate how redundant it is... but I guess that's required by PEP 484, so I think there's probably no way around it.

I think I'll update that PR to make similar changes to other namespaces.

**Comment by machineko** [comment]
Hey np. Take it over I didn't see u guys were working on that so I create a fast PR as I was only searching phrases like auto completion and vscode.

I'll be happy with working vscode autocompletion for jax and can agree that all export method looks ugly but it works 😅

**Pull request closed without merging**
