### PR TITLE
Implement jax.numpy.spacing

### PR DESCRIPTION
**Pull request by jakevdp**
Somehow we've missed this numpy API up until now.

### CODE REVIEW

**Comment by jakevdp** [comment]
Hmm, this approach seems to be failing for inputs very close to zero, because `nextafter` returns a denormal, and `lax.sub` flushes denormals.

**Comment by jakevdp** [comment]
> How close are we talking?

Anything where the next higher number is a denormal. For example:
```python
>>> x = np.float32(0)

>>> np.spacing(x)
np.float32(1e-45)

jnp.spacing(x)
Array(0., dtype=float32)
```
This is because of the issue noted here: https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.nextafter.html

**Comment by dfm** [comment]
Interesting! When I run `spacing(np.float32(0))` after copying your new implementation into colab (where I was originally experimenting), it returns `Array(1.e-45, dtype=float32)`, just like the `np` version, but on my mac, I see `Array(0., dtype=float32)`, like you do. I guess this is related to the "in _some_ environments" part of that docstring?

It doesn't seem awesome to have environment-dependent behavior here, but perhaps it's not worth digging into it too deeply. Maybe it's ok to keep this implementation with the appropriate caveat in the docstring, unless you have an idea for an easy fix!

**Comment by jakevdp** [comment]
I think I managed to work around the denormal issue – we'll see if the tests pass. I also added special logic for `float16` so as to match NumPy's outputs (not sure whether we should do that, or just note that JAX's convention differs).

Agreed it's probably worth filing an upstream bug.

**Review by dfm — APPROVED** [review]
Great work! I think this looks like a very sensible approach.

**Comment by jakevdp** [comment]
I reported the float16 issue on the existing issue surrounding conventions used in `np.spacing`: https://github.com/numpy/numpy/issues/15331#issuecomment-2391997232.

**Pull request merged**
