### PR TITLE
[NVIDIA] Add jit for `jax.nn.dot_product_attention` tests

### PR DESCRIPTION
**Pull request by kaixih**
This PR uses jax.jit for testing the `jax.nn.dot_production_attention`.

cc. @nouiz

### CODE REVIEW

**Comment by gnecula** [comment]
This change is Ok, but can you please explain the rationale?

**Comment by kaixih** [comment]
Yes, this is actually motivated from one of our internal tests, which failed only with jitting is off. Still investigating the root cause. So, this PR is more a work around to that issue.

**Comment by gnecula** [comment]
Were your problems with `jit` for these functions? If not, then I would propose that we do not make this change. This would be distracting here, and we have separate tests for `jit`. If those tests are not sufficient, we should expand them.

**Comment by kaixih** [comment]
It seems the requirement of jit is no longer relevant. Closing.

**Pull request closed without merging**
