### PR TITLE
Drop support for numpy 1.21

### PR DESCRIPTION
**Pull request by jakevdp**
This is in accordance with NEP 29 and https://jax.readthedocs.io/en/latest/deprecation.html

Looks like we need to update some kokoro scripts first.

### CODE REVIEW

**Review by hawkinsp — APPROVED** [review]
Looks fine, provided we update the other CI configs as well.

**Comment by hawkinsp** [comment]
The CI builds should now work if you retrigger them.

**Comment by yashk2810** [comment]
I think we will need to update dockerfiles too?

**Comment by hawkinsp** [comment]
> I think we will need to update dockerfiles too?

Perhaps, please do so if it's needed.

**Comment by yashk2810** [comment]
I am updating the docker images after which the CI builds will pass. I'll report back once it's done. Please don't submit this until then

**Comment by yashk2810** [comment]
The Dockerfiles have been updated. You can retrigger the CI in about 5 minutes and hopefully the tests will pass.

**Comment by jakevdp** [comment]
Re-triggered the tests

**Pull request merged**
