### PR TITLE
[Awaiting Reviews] Attempt at reformating with yapf

### PR DESCRIPTION
**Pull request by joaogui1**
Cleaner version of #1450

### CODE REVIEW

**Comment by jekbradbury** [comment]
I think I’m -1 on this in general; I don’t think the readability benefit is worth adding a formatting logistics step to every PR.

**Comment by mattjj** [comment]
Thanks for investigating this @joaogui1.

I am also -1 on merging this though. I don't see much advantage to standard formatting, and I think there are advantages to leaving formatting up to the code author.

**Comment by mattjj** [comment]
In particular, there are a lot of intentional formatting choices we've made that would be undone by this PR. Maybe we could add exceptions or monkey with yapf's configuration until we're happy, but I'm not sure that's a high-priority use of time.

**Comment by joaogui1** [comment]
Thanks for the input @jekbradbury, @mattjj, the main benefit would be not getting unnecessary error on pylint, which should help with development. Last time I checked there were some weird things going on, like a few functions using 4-space tabs, instead of the usual 2-space ones. But I guess this is a concern for a more mature library (in the sense of having more users and more active contributors, which could end up using different styles and bringing more confusion to the code), so I think I will be closing this PR for now.

**Pull request closed without merging**
