### PR TITLE
Primitive Rules for Higher-Order Derivatives (jet) Scoreboard

### PR DESCRIPTION
**Pull request by jessebett**
- [ ] zeros_like
- [ ] id
- [ ] add_any
- [x] device_put
- [x] neg
- [ ] sign
- [ ] floor
- [ ] ceil
- [ ] round
- [ ] is_finite
- [x] exp
- [x] log
- [ ] expm1
- [ ] log1p
- [ ] tanh
- [ ] sin
- [ ] cos
- [ ] atan2
- [ ] regularized_incomplete_beta
- [ ] lgamma
- [ ] igamma
- [ ] igammac
- [ ] bessel_i0e
- [ ] bessel_i1e
- [ ] erf
- [ ] erfc
- [ ] erf_inv
- [x] real
- [ ] imag
- [x] complex
- [ ] conj
- [ ] abs
- [ ] sqrt
- [ ] rsqrt
- [ ] pow
- [ ] and
- [ ] or
- [ ] xor
- [x] add
- [x] sub
- [x] mul
- [ ] safe_mul
- [x] div
- [ ] rem
- [ ] max
- [ ] min
- [ ] shift_left
- [ ] shift_right_arithmetic
- [ ] shift_right_logical
- [ ] eq
- [ ] ne
- [ ] ge
- [ ] gt
- [ ] le
- [ ] lt
- [x] convert_element_type
- [ ] bitcast_convert_type
- [x] conv_general_dilated
- [x] dot_general
- [x] broadcast
- [x] broadcast_in_dim
- [ ] clamp
- [x] concatenate
- [x] pad
- [x] reshape
- [x] rev
- [x] transpose
- [ ] select
- [x] slice
- [ ] dynamic_slice
- [ ] dynamic_update_slice
- [x] gather
- [ ] scatter-add
- [ ] scatter
- [x] reduce_sum
- [ ] reduce_prod
- [x] reduce_max
- [ ] reduce_min
- [x] reduce_window_sum
- [ ] reduce_window_max
- [ ] reduce_window_min
- [ ] select_and_scatter_add
- [ ] select_and_gather_add
- [ ] sort
- [ ] sort_key_val
- [x] tie_in
- [ ] stop_gradient
- [ ] while
- [ ] cond
- [ ] scan
- [ ] root
- [ ] custom_linear_solve
- [ ] fft
- [ ] psum
- [ ] ppermute
- [ ] jit(arcsinh,static_argnums=())
- [ ] cholesky
- [ ] eigh
- [ ] triangular_solve
- [ ] lu
- [ ] qr
- [ ] svd
- [ ] jit(slogdet, static_argnums=())
- [ ] logit
- [ ] expit
- [ ] log_ndtr
- [ ] random_gamma

@jacobjinkelly @duvenaud @mattjj

Here's the list of all the `ad.jvp_primitives` and probably reflects what we'd need for coverage by `jet`.

It would also be great if we can have some more robust testing of these primitives as they're implemented.

### CODE REVIEW

**Comment by duvenaud** [comment]
@googlebot I consent.

**Comment by jacobjinkelly** [comment]
@googlebot I consent.

**Comment by mattjj** [comment]
@jessebett let's move the TODO list to an issue!

**Comment by jessebett** [comment]
@mattjj Jet in master! :D  🎉 🎉 

I will make that TODO an issue.

**Pull request merged**
