### PR TITLE
Add dynamically methods to _DeviceArray and PyBuffer.

### PR DESCRIPTION
**Pull request by jblespiau**
As you suggested during a review, calling `_DeviceArray` directly when LazyExpr are present is clearer.
We need to remove the weakref slot, otherwise we get:

TypeError: __weakref__ slot disallowed: either we already got one, or __itemsize__ != 0

### CODE REVIEW

**Comment by mattjj** [comment]
Looks like #1180 effectively added `__weakref__` to DeviceArray, though unfortunately it didn't add a test.

@brianwa84 do you still need DeviceArrays to be weakref-able?

**Comment by jblespiau** [comment]
(I have note tested it, but it's is possible that they are still weak-ref friendly, because I think pybind11 classes, are weak-ref friendly by default). If it's still needed, I guess we should add a test.

**Comment by brianwa84** [comment]
I expect we have tests in TFP that would break if weakref support were broken. I can think of a change that might allow us to get rid of this, but it's a user-visible API change to bijectors and transformed distributions.

**Comment by jblespiau** [comment]
I have added a test in api_test.py:

```
  def test_devicearray_weakref_friendly(self):
    x = device_put(1.)
    y = weakref.ref(x)
    self.assertEqual(y(), 1.)
    del x
    self.assertIsNone(y())
```

**Review by mattjj — APPROVED** [review]

**Pull request merged**
