### PR TITLE
Implement np.copysign

### PR DESCRIPTION
**Pull request by jakevdp**
(See #70)

### CODE REVIEW

**Comment by hawkinsp** [comment]
I would have assumed the semantics of `copysign` are not to promote its arguments against each other, but instead to preserve the type of the `x1` unchanged.

**Comment by jakevdp** [comment]
> I would have assumed the semantics of copysign are not to promote its arguments against each other, but instead to preserve the type of the x1 unchanged.

I initially tried that, but it led to a failure under x64, so I tried this approach to see if it would fix the issue. I'll revert the second commit.

**Comment by jakevdp** [comment]
Any thoughts on what's causing the failure under x64, when it succeeds without?

**Comment by jakevdp** [comment]
Opted to turn off dtype checking. Rationale: numpy makes some strange choices, e.g.
```
>>> x = np.arange(4, dtype=int)
>>> np.copysign(x, [1, 1, -1, -1]).dtype
dtype('float64')
```

**Review by mattjj — APPROVED** [review]
Awesome! The NumPy dtype thing was tricky, but this looks like the right call (we don't care to match NumPy's dtype behavior here).

**Pull request merged**
