### PR TITLE
automatic detection of wheel version

### PR DESCRIPTION
**Pull request by JL2718**
simple bash snippet for easy installation added to README.md

### CODE REVIEW

**Comment by skye** [comment]
This is a great idea! Unfortunately it's not working for me:
`ERROR: jaxlib-0.1.40--none-linux_x86_64.whl is not a valid wheel filename.`

I think this is because I still have python 2.7 as the default `python` on my system, so the python version bit isn't working. Is it safe to use `python3` instead of `python`? Not sure if more modern setups still have the python3 alias by default...

**Comment by JL2718** [comment]
Yes; I think that works. I tried with Conda and venv. Both link python3 to the current environment.

**Comment by skye** [comment]
Thanks, works for me now! Let's give it a shot in the wild :)

**Comment by JL2718** [comment]
:fist_right:

**Pull request merged**
