### PR TITLE
added pjit tuorial colab

### PR DESCRIPTION
**Pull request by TinaZetongJia**
Added pjit tutorial with only the colab file

### CODE REVIEW

**Comment by jakevdp** [comment]
OK, I added the markdown version

**Review by apaszke — COMMENTED** [review]
It might be worth trying to decrease the size of images embedded in the notebook before we check it in. At the moment they're taking up the majority of the file.

**Comment by skye** [comment]
This is great, thanks so much for writing it up!

The screenshots aren't showing up when I look at the rendered markdown version (https://jax--7814.org.readthedocs.build/en/7814/jax-101/08-pjit.html). I got to that link by clicking on "Details" of the "docs/readthedocs.org:jax" Github check. You can also build the docs locally while experimenting: https://jax.readthedocs.io/en/latest/developer.html#update-documentation.

Can you try to get the images working in the markdown file? I'm not sure how jupytext handles images, if at all. (jupytext is what we use to create sync'd notebooks and markdown files, see https://jax.readthedocs.io/en/latest/developer.html#syncing-notebooks).

It might be easiest for now to drop the notebook file altogether, since the code needs to be run on a TPU VM anyway, and use regular image files. See https://github.com/google/jax/blob/main/docs/profiling.md for an example markdown file with images. It uses directives like `TensorBoard profiler example`, where the image is checked in at https://github.com/google/jax/tree/main/docs/_static. Let me know if you need help with any of this.

I think once we get it rendering correctly, it should be good to go!

**Comment by cgarciae** [comment]
Hey! I kinda read the notebook very lightly and my constant thought throughout was: how does `pjit` compare/relate to `pmap`? Maybe a note or a small section would help users understand the rational of why/when they need `pjit` vs `pmap`.

**Comment by skye** [comment]
@cgarciae this is a great suggestion, thanks! Sadly tomorrow is the last day of @TinaZetongJia's internship (:sob:), so we're trying to get this in ASAP without too much further editing. Can you file an issue with this suggestion so someone else can add it after the PR is merged? (Or @TinaZetongJia if she wants to continue contributing in her spare time :D)

**Review by skye — APPROVED** [review]
Thanks for pushing this through!

**Pull request merged**
