### PR TITLE
Allow custom_jvp and custom_vjp to decorate methods

### PR DESCRIPTION
**Pull request by NeilGirdhar**
Addresses https://github.com/google/jax/issues/2483

### CODE REVIEW

**Comment by NeilGirdhar** [comment]
If this pull request is likely to be accepted, I'll happily write a test for vjp as well.  Sorry for the trailing space removal, my editor kills them.

**Comment by NeilGirdhar** [comment]
@mattjj Any chance this might make it in?  I have to keep merging this every time I pull from upstream.  You can see how I use it in efax where I avoid a lot of ugly static methods.

**Comment by mattjj** [comment]
Sorry, I'm backlogged, but will look when I can!

**Comment by NeilGirdhar** [comment]
@mattjj thanks!

**Comment by NeilGirdhar** [comment]
@googlebot I consent.

**Comment by NeilGirdhar** [comment]
@mattjj Hi Matt, when you're not busy, any chance I could get a code review on this pull request?

**Pull request closed without merging**
