### PR TITLE
correct spelling on comment

### PR DESCRIPTION
**Pull request by RuffaloLavoisier**

### CODE REVIEW

**Review by sharadmv — CHANGES_REQUESTED** [review]
Thanks for the fixes. You'll need to rebuild the `jitting` notebook (it has Markdown and ipynb that need to be kept in sync). To do that, check out the guide here: https://jax.readthedocs.io/en/latest/developer.html#syncing-notebooks.

**Comment by RuffaloLavoisier** [comment]
@sharadmv 
Thanks ! I reflected it.

**Comment by sharadmv** [comment]
Thank you! Could you please squash your commits before I merge?

**Comment by RuffaloLavoisier** [comment]
@sharadmv 
Sure - no problem 😄

**Review by sharadmv — APPROVED** [review]

**Comment by RuffaloLavoisier** [comment]
Thanks !

**Pull request merged**
