### PR TITLE
Implement jnp.ravel_multi_index()

### PR DESCRIPTION
**Pull request by jakevdp**

### CODE REVIEW

**Comment by jakevdp** [comment]
Internal tests pass.

**Review by froystig — APPROVED** [review]
Nice. Do we want to check upfront, and err with a more specific message, if this is called in `'raise'` mode with non-static first argument?

**Comment by jakevdp** [comment]
> Nice. Do we want to check upfront, and err with a more specific message, if this is called in 'raise' mode with non-static first argument?

Good idea. I added an explicit `ValueError` when the `multi_index` value is traced. Is that what you had in mind, or is there a standard utility for this that I'm not aware of?

**Comment by froystig** [comment]
I had `core.concrete_or_error` in mind, which is used elsewhere throughout `lax_numpy`. It allows tracers as long as they're concrete.

**Comment by jakevdp** [comment]
OK, Done.

**Pull request merged**
