### PR TITLE
[sparse] add jvp rule for bcoo_spdot_general

### PR DESCRIPTION
**Pull request by jakevdp**
I'll do the transpose rule in a later PR.

### CODE REVIEW

**Review by froystig — APPROVED** [review]

**Comment by lucagrementieri** [comment]
Will the vjp rule for bcoo_spdot_general implemented soon?

**Comment by jakevdp** [comment]
I'm not currently working on it - is it something you need?

**Comment by lucagrementieri** [comment]
I'm writing an optimization software that has to back-propagate through a product of large sparse matrices.
I would like to use JAXopt, but the program crashes because JAXopt uses the gradient computed using reverse mode differentiation. I can change the inner working of JAXopt but it would be better to have the vjp rule for the product of sparse matrices.

I'm trying to implement the vjp rule myself right now, but I have no previous experience with the inner workings of JAX, so I'm not sure I can succeed.

**Comment by jakevdp** [comment]
The challenge with the spdot_general transpose rule is that it requires the sparse equivalent of bcoo_extract, which is not yet implemented, and is an operation that I'm not sure how to implement efficiently. You can see roughly what it would have to do by looking at `_bcoo_dot_general_transpose`: https://github.com/google/jax/blob/be64d8ba7c0ebffc935cd9d88bb6e927b6ee491c/jax/experimental/sparse/bcoo.py#L874

**Comment by jakevdp** [comment]
That said, it seems like there may be some problem with the forward rule as well: #10163

**Pull request merged**
