### PR TITLE
Apply pyupgrade --py39-plus.

### LINKED ISSUE #16537: Use PEP 585 type hints
Since JAX just dropped Python 3.8 support, we can update our type hints to use the PEP 585 syntax.
https://peps.python.org/pep-0585/

### PR DESCRIPTION
**Pull request by hawkinsp**
Notable changes:
* use PEP 585 type names
* use PEP 604 type union syntax where `from __future__ import annotations` is present.
* use f-strings in more places.
* remove redundant arguments to open().

Fixes #16537

### CODE REVIEW

**Comment by hawkinsp** [comment]
h/t to @lgeiger for pointing out that `pyupgrade` is a thing.

**Comment by jakevdp** [comment]
If you do the jupytext fixes via `pre-commit run jupytext --all-files` then you won't get the version mismatches.

Alternatively, make sure your local `jupytext` matches the version specified in `pre-commit-config.yaml`.

**Comment by hawkinsp** [comment]
> If you do the jupytext fixes via `pre-commit run jupytext --all-files` then you won't get the version mismatches.
> 
> Alternatively, make sure your local `jupytext` matches the version specified in `pre-commit-config.yaml`.

Done

**Review by jakevdp — APPROVED** [review]
Looks good.

A couple (probably non-actionable) comments:

- I kind of hate that we have to import `Sequence` from `collections.abc` instead of from `typing`. Oh well...
- I'm not a fan of replacing `Optional[type]` with `type | None`. In my mind `type | None` implies that the default value is not necessarily `None`, but that the user could pass `None` if they wish. `Optional[type]` implies to me that the default value is `None`, but the user should not necessarily pass `None` explicitly.

But like I said, those are a matter of preference & probably not actionable here. Ship it!

**Comment by yashk2810** [comment]
Does this mean we can't/shouldn't use Optional[type] anymore?

Like Jake, I also prefer Optional[type] over `type | None`.

**Comment by hawkinsp** [comment]
I personally prefer `x | None` over `Optional`, so I agree with `pyupgrade` personally. If nothing else, it requires one fewer import and it's shorter. Shorter code is our primary goal in life!

**Comment by hawkinsp** [comment]
> Does this mean we can't/shouldn't use Optional[type] anymore?
> 
> Like Jake, I also prefer Optional[type] over `type | None`.

Well, we don't have a rule here. Do as you like. But I suspect if I run `pyupgrade` Python 3.10 it may rewrite to this form.

**Pull request merged**
