### PR TITLE
Updates onp -> np in random, loops, optix and their tests

### PR DESCRIPTION
**Pull request by joaogui1**

### CODE REVIEW

**Comment by jakevdp** [comment]
Looks good! I think some of these files may have changed in the meantime; can you rebase on master and force-update?

**Comment by joaogui1** [comment]
@jakevdp like this? Sorry, I'm not very proficient with git :/

**Comment by jakevdp** [comment]
No, something strange happened: it looks like you added your new changes to the most recent commit on master? I'm honestly not sure what's going on with your branch right now...

**Comment by joaogui1** [comment]
I tried rebasing :(, guess I can kill this PR and start again

**Comment by jakevdp** [comment]
What I meant is for you to run (assuming ``upstream`` points to http://github.com/google/jax and ``origin`` points to http://github.com/joaogui1.jax)
```
git fetch upstream master
git rebase upstream/master
git push -f origin master
```
But at this point, you've rewritten your history enough that that won't do the right thing...

**Comment by jakevdp** [comment]
In general things will be cleaner if you develop new features on a branch other than ``master``

**Comment by joaogui1** [comment]
> In general things will be cleaner if you develop new features on a branch other than `master`

yeah, I realized my mistake after I had already changed many files, should have fixed it before opening the PR, thanks for the tip!

**Pull request closed without merging**
