### PR TITLE
Pin pygments version in RTD build

### PR DESCRIPTION
**Pull request by skye**
Disable notebook generation

### CODE REVIEW

**Comment by 8bitmp3** [comment]
🤙 for `pmap` notebooks? @skye

**Comment by skye** [comment]
No, only to fix our broken RTD builds

**Review by jakevdp — APPROVED** [review]
LGTM! Thanks for looking into this

**Comment by skye** [comment]
BTW I don't know how to change the title of this PR but the commit has a useful title + description :)

**Pull request merged**
