### PR TITLE
Fix lax.broadcast_shapes returning numpy ints in shape tuple

### PR DESCRIPTION
**Pull request by sharadmv**

### CODE REVIEW

**Comment by mattjj** [comment]
I think you can use [this function](https://github.com/google/jax/blob/a669eda6ce9ea52f0516536effdb295ee9abf9fb/jax/core.py#L832-L839). The masking transform sometimes puts non-integers (namely polynomial expressions) in shape tuples.

**Comment by mattjj** [comment]
Can you add a test which repros how you were seeing numpy scalars before?

**Comment by sharadmv** [comment]
Thanks for the pointer! I've added a test now.

**Comment by sharadmv** [comment]
Could I get a re-review on this :)?

**Comment by sharadmv** [comment]
Thanks!

**Pull request merged**
