### PR TITLE
Fix the bug in classifier example, batching_test and README

### PR DESCRIPTION
**Pull request by praveen-palanisamy**
### What does this PR do?
Fixes the bug in applying the activation function.

### Related issue(s)
#31

### CODE REVIEW

**Comment by praveen-palanisamy** [comment]
I signed it!

**Review by hawkinsp — COMMENTED** [review]
Thanks for the PR!

Unfortunately I don't think this change is correct. The intent of the loop is the output of each layer (loop iteration) is fed to the input of the next layer, so the behavior shown here is intentional.

However, I think the PR does highlight some confusing code, and perhaps the alternative formulation of the loop, as used in the shiny new colab notebook example:

https://colab.research.google.com/github/google/jax/blob/master/notebooks/neural_network_and_data_loading.ipynb

might be less surprising, and perhaps we should change all of these examples to look like that colab example. (See the `predict` function under "Auto-batching predictions".)

Other JAX folks — what do you think?

**Comment by alexbw** [comment]
Yes, I agree that the colab version is less surprising. Less cleverness!

**Comment by praveen-palanisamy** [comment]
Ah. I see! I totally missed the for loop over the params/layers.
After seeing that, although the colab version looks more verbose/explicit, the examples version looks more elegant/concise.

**Comment by praveen-palanisamy** [comment]
I will close this PR. I will be happy to update these to look like the colab version if you decide.

**Pull request closed without merging**
