### PR TITLE
Migrate api_test, lax_numpy_test, and lax_vmap_test to

### PR DESCRIPTION
**Pull request by hawkinsp**
jtu.sample_product.

Gives a ~2x improvement in pytest --collect-only timing for lax_numpy_test.

### CODE REVIEW

**Comment by jakevdp** [comment]
Looks good overall, but there are a LOT of diffs and I'm not confident I can look through them by eye and be certain every parameterization is translated faithfully. I wonder if we could do something like diff the output of `pytest-cov` over relevant files before and after this change to give us confidence that we haven't lost some tests in the translation?

**Comment by soraros** [comment]
Not sure how helpful this is, there is
```bash
pytest --collect-only tests/lax_numpy_test.py
```
with output like
```
platform darwin -- Python 3.10.6, pytest-7.1.3, pluggy-1.0.0
rootdir: .../jax, configfile: pytest.ini
plugins: anyio-3.6.1, xdist-2.5.0, forked-1.4.0
collected 2662 items                                                                                                   

<Module tests/lax_numpy_test.py>
  <UnitTestCase LaxBackedNumpyTests>
    <TestCaseFunction testAbstractionErrorMessage>
    <TestCaseFunction testAllClose_x=1_y=1_equal_nan=True>
    <TestCaseFunction testAllClose_x=[1, 1.0001]_y=1_equal_nan=False>
    <TestCaseFunction testAllClose_x=[1, nan]_y=1_equal_nan=False>
    <TestCaseFunction testAllClose_x=[1, nan]_y=1_equal_nan=True>
   ...
```

**Comment by hawkinsp** [comment]
@soraros There are two issues:
* One is that after this change the test cases now don't have the same meaningful names (e.g., they will be named `testAllClose7` or similar.

  Initially I was sad about this but became sold on it because:
  a) generating strings accounts for a pretty good fraction of the time to collect the tests
  b) it's a lot of tedious code to generate the strings
  c) the strings often have things like spaces or newlines in them that makes them hard to work with, e.g., when filtering tests, and
  d) it turns out that both `pytest` and `unittest` will print the test parameters; although pytest will do so only for failures. So comparing the test case names won't work.

* Even if we simply compared the test parameters, we are now going to select a different random sample of test cases, because the procedure used to select the random sample has changed. This problem also means anything like coverage data also won't tell us much. So I'm not sure there's a whole lot we can do here other than stare at the diffs (or trust they are right).

**Comment by jakevdp** [comment]
Here's a quick attempt at coverage diffs:
```bash 
$ git checkout main
$ pytest --cov-report xml:lax-vmap-test-main.xml --cov=jax/_src/lax tests/lax_vmap_test.py
$ git checkout testing
$ pytest --cov-report xml:lax-vmap-test-hawkinsp.xml --cov=jax/_src/lax tests/lax_vmap_test.py
$ diff -y -W 240 --suppress-common-lines lax-vmap-test-main.xml lax-vmap-test-hawkinsp.xml 
<coverage version="5.1" timestamp="1664990344355" lines-valid="8897" lines-covered="3597" line-rate="0.4043" branches |	<coverage version="5.1" timestamp="1664990175108" lines-valid="8897" lines-covered="3599" line-rate="0.4045" branches
		<package name="." line-rate="0.4754" branch-rate="0" complexity="0">				      |			<package name="." line-rate="0.4757" branch-rate="0" complexity="0">
				<class name="convolution.py" filename="convolution.py" complexity="0" line-rate="0.43 |					<class name="convolution.py" filename="convolution.py" complexity="0" line-rate="0.45
						<line number="587" hits="0"/>					      |							<line number="587" hits="1"/>
						<line number="589" hits="0"/>					      |							<line number="589" hits="1"/>
						<line number="592" hits="0"/>					      |							<line number="592" hits="1"/>
						<line number="593" hits="0"/>					      |							<line number="593" hits="1"/>
						<line number="598" hits="0"/>					      |							<line number="598" hits="1"/>
						<line number="599" hits="0"/>					      |							<line number="599" hits="1"/>
				<class name="lax.py" filename="lax.py" complexity="0" line-rate="0.6516" branch-rate= |					<class name="lax.py" filename="lax.py" complexity="0" line-rate="0.6501" branch-rate=
						<line number="1052" hits="1"/>					      |							<line number="1052" hits="0"/>
						<line number="1095" hits="1"/>					      |							<line number="1095" hits="0"/>
						<line number="2944" hits="1"/>					      |							<line number="2944" hits="0"/>
						<line number="2946" hits="1"/>					      |							<line number="2946" hits="0"/>
						<line number="2948" hits="1"/>					      |							<line number="2948" hits="0"/>
						<line number="2959" hits="0"/>					      |							<line number="2959" hits="1"/>
						<line number="2961" hits="0"/>					      |							<line number="2961" hits="1"/>
						<line number="3425" hits="1"/>					      |							<line number="3425" hits="0"/>
```
Spot-checking the newly missing coverage, it looks like it basically comes from several `if` statements inside particular batching rules, which is probably due to test parameterization hitting different combinations of inputs. Based on this, I'm pretty confident that changes to `lax_vmap_test.py` don't contain any errors.

I'll run some similar checks for the other tests.

**Comment by jakevdp** [comment]
`api_test` only causes diffs in `test_util`, which tells me test coverage is virtually identical aside from using different utilities:
```
$ git checkout main
$ pytest --cov-report xml:api-test-main.xml --cov=jax tests/api_test.py
$ git checkout testing
$ pytest --cov-report xml:api-test-hawkinsp.xml --cov=jax tests/api_test.py
$ diff -y -W 240 --suppress-common-lines api-test-main.xml api-test-hawkinsp.xml
<coverage version="5.1" timestamp="1664992118320" lines-valid="52338" lines-covered="19829" line-rate="0.3789" branch |	<coverage version="5.1" timestamp="1664992260977" lines-valid="52339" lines-covered="19835" line-rate="0.379" branche
		<package name="_src" line-rate="0.6172" branch-rate="0" complexity="0">				      |			<package name="_src" line-rate="0.6178" branch-rate="0" complexity="0">
				<class name="test_util.py" filename="_src/test_util.py" complexity="0" line-rate="0.5 |					<class name="test_util.py" filename="_src/test_util.py" complexity="0" line-rate="0.5
						<line number="606" hits="0"/>					      |							<line number="605" hits="0"/>
						<line number="608" hits="0"/>					      |							<line number="607" hits="0"/>
.
.
.
<many more diffs in test_util.py but no other files>
```

**Comment by jakevdp** [comment]
And for `lax_numpy_test.py`; only a handful of non-clustered changes. Again, spot checks imply this is just hitting different parameterizations:
```
$ git checkout main
$ pytest --cov-report xml:lax-numpy-test-main.xml --cov=jax/_src/numpy tests/lax_numpy_test.py
$ git checkout testing
$ pytest --cov-report xml:lax-numpy-test-hawkinsp.xml --cov=jax/_src/numpy tests/lax_numpy_test.py
$ diff -y -W 240 --suppress-common-lines lax-numpy-test-main.xml lax-numpy-test-hawkinsp.xml
<coverage version="5.1" timestamp="1664992750464" lines-valid="5470" lines-covered="4449" line-rate="0.8133" branches |	<coverage version="5.1" timestamp="1664993040122" lines-valid="5470" lines-covered="4456" line-rate="0.8146" branches
		<package name="." line-rate="0.8133" branch-rate="0" complexity="0">				      |			<package name="." line-rate="0.8146" branch-rate="0" complexity="0">
				<class name="lax_numpy.py" filename="lax_numpy.py" complexity="0" line-rate="0.8664"  |					<class name="lax_numpy.py" filename="lax_numpy.py" complexity="0" line-rate="0.8667" 
						<line number="548" hits="1"/>					      |							<line number="548" hits="0"/>
						<line number="1193" hits="1"/>					      |							<line number="1193" hits="0"/>
						<line number="1664" hits="0"/>					      |							<line number="1664" hits="1"/>
						<line number="1827" hits="1"/>					      |							<line number="1827" hits="0"/>
						<line number="2300" hits="0"/>					      |							<line number="2300" hits="1"/>
						<line number="2305" hits="0"/>					      |							<line number="2305" hits="1"/>
						<line number="3257" hits="1"/>					      |							<line number="3257" hits="0"/>
						<line number="3310" hits="0"/>					      |							<line number="3310" hits="1"/>
						<line number="4234" hits="1"/>					      |							<line number="4234" hits="0"/>
						<line number="4400" hits="0"/>					      |							<line number="4400" hits="1"/>
						<line number="4455" hits="1"/>					      |							<line number="4455" hits="0"/>
						<line number="4572" hits="1"/>					      |							<line number="4572" hits="0"/>
						<line number="4573" hits="1"/>					      |							<line number="4573" hits="0"/>
						<line number="4574" hits="1"/>					      |							<line number="4574" hits="0"/>
						<line number="4601" hits="0"/>					      |							<line number="4601" hits="1"/>
						<line number="4602" hits="0"/>					      |							<line number="4602" hits="1"/>
						<line number="4641" hits="0"/>					      |							<line number="4641" hits="1"/>
						<line number="4650" hits="1"/>					      |							<line number="4650" hits="0"/>
						<line number="4668" hits="0"/>					      |							<line number="4668" hits="1"/>
						<line number="4669" hits="0"/>					      |							<line number="4669" hits="1"/>
						<line number="4670" hits="0"/>					      |							<line number="4670" hits="1"/>
				<class name="polynomial.py" filename="polynomial.py" complexity="0" line-rate="0.7778 |					<class name="polynomial.py" filename="polynomial.py" complexity="0" line-rate="0.7725
						<line number="292" hits="1"/>					      |							<line number="292" hits="0"/>
				<class name="reductions.py" filename="reductions.py" complexity="0" line-rate="0.7161 |					<class name="reductions.py" filename="reductions.py" complexity="0" line-rate="0.7214
						<line number="326" hits="0"/>					      |							<line number="326" hits="1"/>
						<line number="358" hits="0"/>					      |							<line number="358" hits="1"/>
				<class name="setops.py" filename="setops.py" complexity="0" line-rate="0.9505" branch |					<class name="setops.py" filename="setops.py" complexity="0" line-rate="0.978" branch-
						<line number="144" hits="1"/>					      |							<line number="144" hits="0"/>
						<line number="232" hits="0"/>					      |							<line number="232" hits="1"/>
						<line number="233" hits="0"/>					      |							<line number="233" hits="1"/>
						<line number="289" hits="0"/>					      |							<line number="289" hits="1"/>
						<line number="299" hits="0"/>					      |							<line number="299" hits="1"/>
						<line number="300" hits="0"/>					      |							<line number="300" hits="1"/>
						<line number="302" hits="0"/>					      |							<line number="302" hits="1"/>
```
Given those checks I'm happy with this PR - thanks Peter!

**Review by jakevdp — APPROVED** [review]

**Comment by hawkinsp** [comment]
BTW I had to disable some tests for `testConcatenate` due to promotion errors. I'll file a bug for @jakevdp for that.

**Pull request merged**
