### PR TITLE
Adds lots of trivial jet rules, partly addresses #2431

### PR DESCRIPTION
**Pull request by duvenaud**
This PR adds more systematic tests for jet rules, and also adds jet rules for some of the easier lax operations: 

 - fft 
 - abs
 - sign
 - floor
 - ceil
 - round
 - and
 - or
 - xor
 - add
 - sub
 - mul
 - eq
 - ne
 - ge
 - gt
 - le
 - lt
 - reduce_min
 - stop_gradient

The rules for propagating Taylor series through these lax operations are simple, especially since many are linear or have all derivatives equal to zero.  I think there are 20 or 30 more simple ones like this in the list at #2431.

The tests could certainly be more systematic.  For instance, we could check that we can take the jet of the jet of all of these.

I think some of the nonlinear ones will be pretty challenging, especially for the linear algebra operations.

Also, @mattjj , I was just copying the ```jtu.skip_on_devices("tpu")``` decorators from our old code - do you think we should keep those for all tests?

Co-Authored-By: jessebett <jessebett@cs.toronto.edu>
Co-Authored-By: Jacob Kelly <jacob.jin.kelly@gmail.com>

### CODE REVIEW

**Comment by mattjj** [comment]
@googlebot David is Google-affiliated (and has signed the CLA on other PRs like #2363 ).

**Comment by mattjj** [comment]
> I was just copying the jtu.skip_on_devices("tpu") decorators from our old code - do you think we should keep those for all tests?

I'm not sure. TPUs tend to have lower numerical accuracy, so I think I marked the tests as skipped on TPUs just so that we didn't have to fiddle with TPU-specific tolerances to make them pass. They may very well work already.

Seems like a fine thing to cargo-cult for now though. The tests will still run on CPU and GPU when we sync the code into Google.

**Comment by mattjj** [comment]
> I think some of the nonlinear ones will be pretty challenging, especially for the linear algebra operations.

IIUC we'll have to take them one-at-a-time, and either work out some bespoke math or else fall back on a generic Faà di Bruno approach. Is that your thinking too?

**Review by mattjj — APPROVED** [review]
Awesome! Thanks for pushing this forward.

**Comment by jessebett** [comment]
I updated the list in #2431

**Pull request merged**
