### PR TITLE
Support `pathlib.Path` input to `start_trace`

### PR DESCRIPTION
**Pull request by cool-RR**
If you want tests for this or anything else, let me know.

### CODE REVIEW

**Comment by sharadmv** [comment]
A test would be nice, maybe add one [here](https://github.com/google/jax/blob/3dd0d74f2b54c89e5f919cd00c58683c08c89f08/tests/profiler_test.py)?

**Comment by cool-RR** [comment]
@sharadmv I wrote a couple of tests. I don't have a local setup to run tests, could you approve for the CI to run on this issue so I'll see whether my tests pass?

**Review by sharadmv — APPROVED** [review]
Thank you!

**Comment by cool-RR** [comment]
If you want I can also convert the internal code to use `pathlib`. This means that stuff like `os.path.join(curr_path, "plugins", "profile")` would be just `curr_path / "plugins" / "profile"`. Same for `glob` etc.

**Comment by sharadmv** [comment]
That would be welcome, but not super high priority since it's internal code.

**Pull request merged**
