### PR TITLE
Make jnp.array convert empty list to DeviceArray

### PR DESCRIPTION
**Pull request by sharadmv**

### CODE REVIEW

**Comment by gnecula** [comment]
This seems fine, but it is not obvious to me that the requirement on `jnp.array` is to produce a DeviceArray always. It does seem to be the case in most other cases, by virtue of `reshape` and `concatenate` being jitted. 

I also notice that there are no other tests to check this. What do you think about expanding the test with a few more cases, thus generalizing it beyond the empty list.

**Comment by hawkinsp** [comment]
I think we do have something of an informal rule that functions in `jax.numpy` should always return a JAX array object and never a NumPy array object. This is important because the two don't act the same, for example, with respect to things like type promotion semantics.

**Review by hawkinsp — APPROVED** [review]

**Comment by sharadmv** [comment]
Would you still like additional tests before merging?

**Comment by hawkinsp** [comment]
I approved because I think this PR improves the world, but if you wanted to add a couple more test cases, it would be welcome too.

**Comment by sharadmv** [comment]
I added some additional asserts into the test.

**Review by hawkinsp — APPROVED** [review]

**Pull request merged**
