### PR TITLE
Updated broken links and cell outputs in thinking_in_jax.ipynb to reflect the current JAX behavior

### PR DESCRIPTION
**Pull request by che-shr-cat**
I updated the broken links and cell outputs (including error messages and some related texts) to reflect the current JAX behavior

### CODE REVIEW

**Comment by che-shr-cat** [comment]
I didn't get it, why the check is failed with the message:

[jupytext] Error: the git index is outdated.
Please add the paired notebook with:
    git add docs/notebooks/thinking_in_jax.ipynb

**Comment by jakevdp** [comment]
You can find information on our approach to notebooks at https://jax.readthedocs.io/en/latest/developer.html#update-notebooks; in short, you can `git add` your changes and then run `jupytext --sync` to fix the issue

That said, I'd prefer we avoid the large (mostly meaningless) metadata diffs in the notebook format here; I'd suggest reverting the change to the `ipynb`, and then re-generating it from the markdown with jupytext.

Sorry for the complication here – notebooks and git just don't mix all that well.

**Review by jakevdp — CHANGES_REQUESTED** [review]
Looks good, thanks!

A couple minor remaining things:

- I think the CI failure is something that's already been fixed; if you rebase on the current main, it should work itself out
- Please squash your changes into a single commit (see https://jax.readthedocs.io/en/latest/contributing.html#single-change-commits-and-pull-requests for details)

Thanks for looking at this!

**Comment by che-shr-cat** [comment]
Thanks for the help! Working on this

**Comment by che-shr-cat** [comment]
Read the Docs build is still failing, and I cannot understand what's the issue with it. It looks like two cells cannot be parsed (there are warnings there) but I cannot identify which ones and what's exactly the reason :(

**Comment by jakevdp** [comment]
I suspect the issue is the back-ticks within the traceback messages (e.g. line 238 of the ipynb file)

**Comment by che-shr-cat** [comment]
Still cannot fix it, so I'll close the PR for now to understand better what's wrong

**Comment by che-shr-cat** [comment]
I removed cell output changes from the notebook as I cannot identify what exactly makes tests fail. So I kept only text changes regarding the broken URLs and updated text to better align with the output of current versions of the JAX library.

**Review by jakevdp — APPROVED** [review]

**Comment by jakevdp** [comment]
Thanks! Sorry for the confusion about this. For what it's worth, I think the issue is that myst-nb cannot handle error messages that contain back-tick characters, despite the fact that some of JAX's current error messages contain back-ticks. We could either fix this by patching myst-nb, or by modifying JAX's error messages to remove the back-ticks.

**Pull request merged**
