### PR TITLE
Expose UnexpectedTracerError and add docs.

### PR DESCRIPTION
**Pull request by LenaMartens**
Adding the UnexpectedTracerError as a public symbol and adding some docs in the process :)

I haven't checked how it renders in the doc format (not sure how to do that?), and could use some help on the wording (too verbose/not verbose enough/talking too much about Tracers?)

### CODE REVIEW

**Comment by hawkinsp** [comment]
> Adding the UnexpectedTracerError as a public symbol and adding some docs in the process :)
> 
> I haven't checked how it renders in the doc format (not sure how to do that?), and could use some help on the wording (too verbose/not verbose enough/talking too much about Tracers?)

Instructions for building the docs locally are here: https://jax.readthedocs.io/en/latest/developer.html#update-documentation

**Review by froystig — APPROVED** [review]
Nice! I made various edit suggestions, but nothing too important. Feel free to take any, or none, and to iterate further.

**Comment by LenaMartens** [comment]
Thanks for the review and suggestions, Roy! I've accepted the suggestions and iterated a bit more on the wording and formatting, PTAL.

**Comment by froystig** [comment]
Looks good!

**Pull request merged**
