### PR TITLE
Revert change to jaxlib version in XLA_in_Python.ipynb.

### PR DESCRIPTION
**Pull request by jlebar**
I accidentally made this change in https://github.com/google/jax/pull/904/commits/d5ba04b79e37c6f5dbb9df58d701b19b9523770a#diff-e512abedc01637b70a5b9f6781cc964e.

### CODE REVIEW

**Comment by mattjj** [comment]
I saw that when reading through, but thought git would sort out the merge itself. TIL to trust the diff.

**Comment by mattjj** [comment]
I saw that when reading through, but thought git would sort out the merge itself. TIL to trust the diff.

Don't forget notebooks/Common_Gotchas_in_JAX.ipynb too!

**Comment by mattjj** [comment]
Maybe just grep for 0.1.18 to make sure it's not mentioned :)

**Comment by jlebar** [comment]
> Don't forget notebooks/Common_Gotchas_in_JAX.ipynb too!

Looks like that one does not specify an explicit version?

> Maybe just grep for 0.1.18 to make sure it's not mentioned :)

Done.  I also looked through every instance of `jaxlib` in the tree.  I *think* it's only this one that's wrong.

Dunno if it would make sense to try to make it less fragile somehow?  Even if it's just a shell script to print out the jaxlib+cuda name or something?

**Comment by jlebar** [comment]
Oh, I found one that I missed because it has a space in the filename.  :)

**Comment by mattjj** [comment]
We could make this less fragile by hosting our own wheel repository (super easy just can’t do it from a Google cloud bucket.) or by writing more in-line shell!

**Pull request merged**
