### PR TITLE
DOC: clarify behavior of lax.cond & lax.select

### PR DESCRIPTION
**Pull request by jakevdp**
In response to questions at #13586; also #7934

Related to #8409

### CODE REVIEW

**Comment by skirsten** [comment]
I also just found #7934 which will probably be resolved by this.

**Comment by jakevdp** [comment]
Thanks for the pointer!

**Comment by jakevdp** [comment]
Updated based on offline discussion - please take a look!

**Comment by bheijden** [comment]
I have a question related to

I've been noticing super linear compilation times in my application when using `jax.lax.switch` with an increasing number of branches (similar to [this](https://github.com/google/jax/issues/4453) issue). From what I read [here](https://github.com/google/jax/pull/3318), `jax.lax.cond` is implemented as a special case of `switch`.  

Could  [these lines](https://github.com/google/jax/pull/13589/files#diff-8964bb46126eb1a8e01c28fd7ca7058c589380c0df5dd4fd7f8a23f3652f9a39R172-R179) explain the increased compilation time? You state that XLA may nevertheless choose to use a `select` instead of branching if it is deemed advantageous, but could this process of inference lead to super linear compilation times? 

In my application, I chose to use a `switch` instead of a `select` because I feared long compilation times, but now it seems under the hood it is ignoring this. If this is indeed the culprit, it would be great if there was an option to force jax/xla to forgo on this optimization to lower the compilation times.

**Review by froystig — APPROVED** [review]

**Pull request merged**
