### PR TITLE
Make `core.call_p` a call primitive.

### PR DESCRIPTION
**Pull request by sharadmv**

### CODE REVIEW

**Comment by mattjj** [comment]
Thanks, @sharadmv ! Nice catch!

**Comment by gnecula** [comment]
call_p is never used anywhere in the code. What is its purpose?

**Comment by mattjj** [comment]
It's essentially the canonical example of a call with no extra constraints or features, i.e. it works with Python control flow and doesn't abstract its inputs, etc. It's been the basis for a lot of my work recently, namely remat and custom jvp/vjp stuff, all of which are calls but with different funny behaviors. I find it helpful to keep in as a reference, and in some ways much of JAX was designed around it.

**Comment by mattjj** [comment]
It's also been the basis of a lot of @sharadmv's work, which is why he noticed this bug I suspect!

**Pull request merged**
