### PR TITLE
add lax.cond (initial-style implementation)

### LINKED ISSUE #325: lax.cond does not exist, contrary to the README
The README says

> If you want compiled control flow, use structured control flow primitives like lax.cond and lax.while.

But `lax.cond` does not actually exist, and `lax.while` only exists in the form of `lax._while_loop`.

1. Is `lax.cond` already implemented somewhere, just not part of the master branch? I don't need gradient support for `lax.cond` (which is tracked by PR #83), just jit-compilable `cond` would be a huge gain for me (currenty looking into whether I might be able to contribute this if it doesn't exist yet)

2. `lax.while` will probably never exist because `while` is a reserved keyword; so this should probably be renamed to `lax.while_loop` and can probably already be made available by renaming `lax._while_loop`, or what's the problem with the `_while_loop` implementation (`fori_loop` and `foreach_loop` are not prefixed with an underscore and use `_while_loop`, so it should be fully functional)?

### PR DESCRIPTION
**Pull request by mattjj**
closes #325

### CODE REVIEW

**Comment by mattjj** [comment]
@dougalm explained some subtleties: we need to do a lattice join on partial values as well as abstract values (and, for AD, a join on the zero-or-nonzero lattice too!). I added a commented-out failing test, where one branch is a constant and the abstract value lattice join fails because the constant side's jaxpr is effectively lambda x: ().

We're going to do some light jaxpr munging here. This shows all the cases:

```
cond(predicate, x, lambda x: (x, x, 1, 1), y, lambda y: (y, 1, y, 1))
```

That needs to result in jaxprs that correspond to `lambda x: (x, x, 1, ())`  and  `lambda y: (y, 1, y, ())`, since the last element is statically known but the others aren't.

**Comment by jonasrauber** [comment]
Is this usable?

**Comment by mattjj** [comment]
Yes with two caveats:

1. If one side of the branch is a constant (like a literal) and the other isn't, then you'll get an error. It's clear how to fix it, but it might take a couple hours of work.
2. It doesn't support any transformations other than `jit` compilation. It's not too hard to add `vmap` and `jvp`, but `grad`/`vjp` is trickier. There are no known unknowns, but it might take more than a couple hours.

I think we want to fix the first caveat before merging.

**Comment by jonasrauber** [comment]
Great! I already startet using it. `vmap` support would be the most interesting addition for me.

**Comment by jonasrauber** [comment]
The issue with constants is actually more common than I thought. I work around it by adding `0 * non-constant value` or defining `true = np.logical_or(True, non-constant bool)`

**Comment by jonasrauber** [comment]
What's the best way to handle cases where one only needs the _if clause_? Right now I use the identity function and the expected output value for the else part, but maybe there is a better solution.

**Comment by mattjj** [comment]
@jonasrauber The new commits should handle the const-ness and non-const-ness for you (including if you have nested data structures of mixed const-ness). I plan to merge this soon, though it could certainly use some field-testing!

**Comment by mattjj** [comment]
> What's the best way to handle cases where one only needs the if clause? Right now I use the identity function and the expected output value for the else part, but maybe there is a better solution.

That sounds like the right solution to me. We could provide convenience wrappers or default arguments (e.g. true_fun and false_fun could default to identity, or something). We could use help in figuring out the right convenience layers!

**Comment by mattjj** [comment]
I merged to allow some internal users to start testing this. I'll defer a full review from @dougalm (and anyone else) until later.

**Comment by jonasrauber** [comment]
Awesome, thanks!

**Comment by fehiepsi** [comment]
@mattjj It seems to me that `lax.cond` evaluates both true_fun and false_fun. Is it the expected behaviour?
Here is the replicate script:
```
def t(x):
    def true_fn(x):
        return (np.log((x ** 2) * 2) + 1 - x ** 3 / 23) * 2 + 1 - 7 * x
    def false_fn(x):
        return 3.
    return lax.cond(x < 2, x, true_fn, x, false_fn)

%timeit t(3)
%timeit t(1)
```

**Comment by mattjj** [comment]
Yes, it’s expected that both get evaluated _on abstract values_. Only one side’s FLOPs are carried out. That is, we evaluate the Python code of each branch on abstract values, so that the staged our computation can see both sides, but that staged out computation only executes one side. 

If you make one side just a big matmul (or any operations on large arrays, since tracing the same number of operations doesn’t depend on the array sizes) you’ll be able to tell.

**Comment by fehiepsi** [comment]
Thanks @mattjj ! You are right, when I add some operations on large arrays, I can observe the difference.
```
@jit
def t(x):
    y = np.ones((5000, 5000))
    def true_fn(x):
        a = np.sum(np.matmul(y, x) + x * x)
        b = np.sum(np.matmul(y, x) + 2 * x * x)
        c = np.sum(np.matmul(y, x) + 3 * x * x)
        d = np.sum(np.matmul(y, x) + 4 * x * x)
        e = np.sum(np.matmul(y, x) + 5 * x * x)
        return np.sum((np.log((x ** 2) * 2) + 1 - x ** 3 / 23)) * 2 + 1 - np.sum(7 * x) + a + b + c + d + e
    def false_fn(x):
        return 3.
    return lax.cond(np.max(x) < 2, x, true_fn, x, false_fn)

x1 = np.ones(5000) * 1
x2 = np.ones(5000) * 3
%timeit t(x1)  # 42ms
%timeit t(x2)  # 16ms
```
Though we can see the difference, it is still costly. In this case, maybe using `np.where` is better. With `return np.where(np.max(x) < 2, true_fn(x), false_fn(x))`, it costs only 22ms.

**Comment by mattjj** [comment]
Good idea to use `np.where` as an alternative where appropriate. In principle, a functional language could even be lazy and only evaluate one side of that `np.where` expression, but in practice XLA doesn't do that. I expect `lax.cond` will be most useful when gating expensive operations, or when working with side-effects (which aren't even expressible in JAX yet).

**Pull request merged**
