### PR TITLE
[typing] annotate jax.numpy scalar types with JAXScalarType

### PR DESCRIPTION
**Pull request by jakevdp**

### CODE REVIEW

**Comment by jakevdp** [comment]
@hawkinsp - requesting some early feedback on this approach. There will likely be a lot of work required to land a change like this, similar to what we did with the rest of `jax/numpy/__init__.pyi`

**Comment by jakevdp** [comment]
Another option would be to avoid the `Protocol` and annotate them more directly as `type[_ScalarMeta]` I'm not sure which I'd prefer.

**Comment by hawkinsp** [comment]
I think I like the protocol over exposing the implementation details

I might not call it `JAXScalarType` because the `JAX` is somewhat redundant.

Overall I'm in favor of  doing something like this.

**Comment by jakevdp** [comment]
> I might not call it `JAXScalarType` because the `JAX` is somewhat redundant.

Renamed to `ScalarType`

**Comment by jakevdp** [comment]
Some updates here: there is a *ton* of downstream code that uses annotations like `-> jnp.float32` ([codesearch](https://github.com/search?q=%22-%3E+jnp.float%22+lang%3Apython&type=code)), which will never be valid: it's impossible to create instances of the type `float32` because JAX doesn't have scalar types.

Still, the intent of those annotations is clear: users want an annotation that communicates both to the reader of the code and to the static type checker that the input is an array (or perhaps array-like) with a float32 dtype.

I'm wondering now whether we'll need to provide some dtype-specific array annotations before we can land something like this change.

**Comment by hawkinsp** [comment]
I agree. We can certainly land this change as is (it makes the world better), but we certainly should see if we can better capture the dtype before forcing everyone to migrate to `jax.Array` as a type annotation.

**Comment by jakevdp** [comment]
I'm going to close this for now – there are far too many uses of `jnp.float32` and others as type annotations (currently valid as they are aliases of `Any`) and I'm not sure how to proceed without a decent typed array replacement.

**Pull request closed without merging**
