### PR TITLE
(docfix) Clarify variable names in README.md snippit

### PR DESCRIPTION
**Pull request by bileschi**
`predict` function should apply nonlinearity to output

### CODE REVIEW

**Comment by jakevdp** [comment]
Hi - thanks for looking into this! This is actually correct as currently written: the idea is that the output vector from one iteration becomes the input vector for the next. I agree it's a bit confusing... We discussed a bit how to improve this in #4048, but didn't land on any good options.

**Comment by gnecula** [comment]
I propose to change the example along the lines discussed in #4048:

```
def predict(params, inputs):
  activations=inputs
  for W, b in params:
    outputs = jnp.dot(activations, W) + b
    activations = jnp.tanh(outputs)
  return outputs
```

@bileschi do you want to do that instead?

**Comment by 8bitmp3** [comment]
(Naming is hard. Linking this issue https://github.com/google/jax/issues/5230 just in case)

**Comment by bileschi** [comment]
Updated to fix / reflect `activations` / `outputs` naming.

**Review by gnecula — APPROVED** [review]

**Pull request merged**
