### PR TITLE
JIT-compile index and index-update expressions.

### PR DESCRIPTION
**Pull request by hawkinsp**
Improves the performance of indexing in op-by-op mode.

### CODE REVIEW

**Comment by mattjj** [comment]
Nice!

Btw see #996 and the discussion there. The approach there (in 8c72e2f, a commit I mentioned at the bottom of the thread) was to register `slice` and `type(Ellipsis)` as PyTrees.

One downside to treating slices as static (as currently in this PR) rather than as transparent (whether via a pytree mechanism or otherwise) is that we'll recompile more often (since we'll compare slices on object id whereas we can likely compile once to handle slice(0, 5) and slice(1, 6)).

WDYT about making `slice` and `type(Ellipsis)` into pytrees? TBH I didn't follow up on 8c72e2f because I thought this might be tricky to think through. But we can think through it now!

**Comment by hawkinsp** [comment]
Making `slice` into a pytree node doesn't work. `slice` indices must have statically known values in all cases that we support. We explicitly issue an error if they don't have concrete values:
https://github.com/google/jax/blob/master/jax/numpy/lax_numpy.py#L2566
If we made it a pytree node, the contents would never be known statically.

It is possible that we might see a little less cache reuse by forming larger clusters here. 

We could make `Ellipsis` into a pytree I guess but I don't see any benefit given we already need to do a static/dynamic split.

**Comment by mattjj** [comment]
> Making slice into a pytree node doesn't work. [...]

Good point. But that's a reason we don't want to abstract the contents of slices: we still don't want to compare (unhashable) slices on object id (which might be fresh every time), and would rather compare their un-abstracted integer contents on equality. The questions of whether slices are transparent (vs opaque unhashable objects) and whether we abstract their contents are distinct (even though the first thing we'd think to try would conflate them).

> We could make Ellipsis into a pytree I guess but I don't see any benefit given we already need to do a static/dynamic split.

Right, the benefit would just be simplicity, but in this case it's not adding much complexity to handle Ellipsis here. I think slices are the real question.

**Review by mattjj — APPROVED** [review]
LGTM based on our convo, thanks for sorting out the issues here!

**Pull request merged**
