### PR TITLE
[ROCm] ci build and dockerfile changes

### PR DESCRIPTION
**Pull request by Ruturaj4**
1. Install system GCC libraries
2. Remove docker image
3. apt update

Created from: rocm/jax#161

### CODE REVIEW

**Comment by Ruturaj4** [comment]
@superbobry  could you please approve? thanks!

**Review by superbobry — APPROVED** [review]

**Comment by Ruturaj4** [comment]
@superbobry @dfm can someone merge please?

**Comment by dfm** [comment]
It looks like there was a merge conflict when this was submitted internally and then it must have gotten lost in the shuffle. Thanks for the ping! @Ruturaj4 — Can you rebase, and then I'll get this merged?

**Comment by Ruturaj4** [comment]
@dfm Just rebased! Could you please merge! thanks.

**Review by dfm — APPROVED** [review]

**Pull request merged**
