### PR TITLE
Implement .view() method of jax.numpy arrays

### PR DESCRIPTION
**Pull request by jakevdp**

### CODE REVIEW

**Comment by danielsuo** [comment]
This is really exciting! I'm guessing [this](https://numpy.org/devdocs/user/basics.subclassing.html) won't be in the cards in the near future, if ever, but I remain hopeful :)

**Comment by jakevdp** [comment]
Yeah, ``view()`` here is a bit of a misnomer, because the result of this is not a view but a transformed array. But the casting behavior of ``np.ndarray.view()`` is something I've been missing...

**Comment by danielsuo** [comment]
Haha, you are forgiven; although what is the hard part about providing a true view? Is it the support for TPU/GPU? I guess there would need to be a much more holistic approach to keep track of references to memory.

**Review by mattjj — APPROVED** [review]
LGTM!

**Pull request merged**
