### PR TITLE
Switch from flake8 to Ruff

### PR DESCRIPTION
**Pull request by NeilGirdhar**
Consider switching to [Ruff](https://docs.astral.sh/ruff/) :smile:

### CODE REVIEW

**Comment by jakevdp** [comment]
Thanks for the proposal! Looking through the failures, it seems that it caught some real issues in the code, though some of the recommendations seem a bit nitpicky (why are list comprehensions better than `map`, for example?)

**Comment by NeilGirdhar** [comment]
> the recommendations seem a bit nitpicky

You're absolutely right.  Even the maintainers don't like all the rules.  They add them by user request.  Definitely, block the codes you don't like.

(I blocked the unnecessary map rule.)

**Review by jakevdp — APPROVED** [review]
Looks good! Let me check with the team to see how they feel about switching to ruff.

**Comment by jakevdp** [comment]
@NeilGirdhar – after a couple weeks, my verdict is: ruff is blazing fast and works great. Thanks so much for suggesting this!

**Comment by NeilGirdhar** [comment]
@jakevdp My pleasure, glad it worked out! 

(Of course the real credit goes to the Ruff team :) @charliermarsh)

**Comment by charliermarsh** [comment]
Thanks for tagging @NeilGirdhar! So glad Ruff is working well for you and the team @jakevdp, I'm a big fan of your work :)

**Comment by chiamp** [comment]
Hi @NeilGirdhar, Flax is also using the unused import Ruff rule (F401) currently and may look to add more rules (currently looking at the [JAX ruff rules](https://github.com/google/jax/pull/18539/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R148-R189) for inspiration). I have a couple questions:
* why use the F811 and F821 for just the single files, instead of applying them to all files?
* why not apply F401 to all files and add an exclusion (i.e. `exclude=[...]`) for `jax/_src`, which would make it less verbose than adding a separate line for each file you want to apply F401 to?

**Comment by NeilGirdhar** [comment]
> why use the F811 and F821 for just the single files, instead of applying them to all files?

They should ideally not be applied to any files.  I only preserved because this change was intended to convert the flake8 configuration into a Ruff one.  If I had more time, I would eliminate these problems.

In particular, F401 would ideally be eliminated by adding an `__all__` to each of these files.  This would solve https://github.com/google/jax/issues/7570.  It would also keep PyRight happy.  If you add `RUF022` to the rules and use `ruff . --fix`, ruff will automatically sort `__all__` for you too.

**Comment by NeilGirdhar** [comment]
Incidentally, if you're interested in linting, there's quite a bit of low hanging fruit that I noticed.  If you enable every error and run Ruff, you should be able to find other rules that could be usefully enabled, e.g.,
* RUF*
* PTH*
* UP*
* RET505
* E231
* PYI026
* D301

It'll be up to the Jax team of course what they value changing and how much churn they want to tolerate, so I didn't want to open that door :smile:.

**Pull request merged**
