### PR TITLE
Ensure all ops get cache hits on second op-by-op mode call

### PR DESCRIPTION
**Pull request by j-towns**
`lax.scatter` forms a new lambda expression every time it is called which leads to a cache miss and the creation of a new jaxpr by _reduction_jaxpr, which in turn leads to scatter being recompiled every time it is called. This change fixes that by defining the lambda function outside of scatter.

### CODE REVIEW

**Comment by j-towns** [comment]
Have found that LU decomposition, lcm and gcd are also getting cache misses in op-by-op. Will see if I can work out the causes.

**Comment by j-towns** [comment]
I think the LU cache misses are probably caused by [this function](https://github.com/google/jax/blob/master/jax/lax_linalg.py#L612..L618) being redefined every time LU is called and then passed as an argument to fori_loop.

**Comment by hawkinsp** [comment]
Looks good, although I guess the LU fix isn't yet included (hence the test failures.)

**Comment by j-towns** [comment]
Gonna take a look at LU today.

**Comment by j-towns** [comment]
LU turned out to be a bit trickier, and I discovered that fori_loop was also not getting cache hits, because of [these two functions] being freshly created on each call. Have fixed that, going to see if I can add a straightforward test for fori_loop's caching so don't merge yet!

**Comment by j-towns** [comment]
@hawkinsp @mattjj this should be ready to merge now. Summary of changes:
 + Add check that no compilation occurs on second op-by-op call to _CompileAndCheck.
 + Add _CompileAndCheck to testForiLoopBasic
 + Fix caching for gcd, lcm, lu, scatter and fori_loop, so that all tests pass.

I wonder whether we ought to document somewhere the fact that in op-by-op mode, compiled primitives are cached based on the shapes and dtypes of their array arguments, and the *identity* of their function arguments. Thus if we define
```python
def count(num):
  def body_fun(i, tot):
    return i + tot
  return lax.fori_loop(0, num, body_fun, 0)
```
then every time `count` is called, a new body fun is created and the fori_loop will have to be recompiled. We can avoid this by defining `body_fun` outside of `count`:
```python
def body_fun(i, tot):
  return i + tot

def count(num):
  return lax.fori_loop(0, num, body_fun, 0)
```
The fixes in this pr are of the above form. This was discussed briefly in https://github.com/google/jax/pull/1221.

**Review by mattjj — APPROVED** [review]
Fantastic. Thank you so much for catching these, fixing them, and adding tests.

**Comment by mattjj** [comment]
Re: docs, we should probably just add a paragraph (a sentence or two) to every control flow primitive docstring. We could also have a top-level note at jax.readthedocs.io but that seems of secondary value.

WDYT?

**Comment by mattjj** [comment]
@fehiepsi more control flow compilation cache improvements here.

**Comment by fehiepsi** [comment]
@mattjj Thanks for pointing out this interesting PR! We'll see if we can adopt it in our codebase.

Currently, we heavily use the pattern
```
def count(num):
  def body_fun(i, tot):
    return i + tot
  return lax.fori_loop(0, num, body_fun, 0)
```
and it is not trivial to move `body_fun` outside. Actually, we will compile `count` so I guess two approaches (defining body_fn inside and outside) are equivalent.

**Pull request merged**
