### PR TITLE
[NVIDIA] Throw an error for unsupported bias shape when cudnn backend is used in `nn.dot_product_attention`

### PR DESCRIPTION
**Pull request by kaixih**
Address the issue reported in [here](https://github.com/google/jax/issues/23701).

cc. @sbodenstein

### CODE REVIEW

**Comment by kaixih** [comment]
I’ve implemented a new change that defines custom VJP rules and batching rules to validate the bias shape in both bprop and vmap usage.

**Comment by mattjj** [comment]
Thanks!

Why do we need primitives here, rather than just `custom_vjp`? It seems like the only action is in autodiff rules...

**Comment by kaixih** [comment]
Hi @mattjj , the primary purpose of the custom primitives is the custom batcher `bias_bwd_batch_rule`. We want to throw an error only when the bias has a singleton batch size and d_bias is required.

Yes, for checking the existence of d_bias, using custom_vjp should suffice. However, checking the batch size is more complex because users may utilize vmap, where the actual batch size can only be obtained from the custom batcher.

**Comment by kaixih** [comment]
Gentle ping. @mattjj @sbodenstein

**Review by mattjj — APPROVED** [review]
Thank you! Sorry for the delay.

**Pull request merged**
