### PR TITLE
Added example of automatic differentiation variational inference

### PR DESCRIPTION
**Pull request by duvenaud**
A simple example that shows off how vmap can be used both for batching over dimensions, and over random samples.  It's a transliteration of an [autograd example](https://github.com/HIPS/autograd/blob/master/examples/black_box_svi.py).

I'm happy to make edits.  I can also add a screenshot if desired:
advi

### CODE REVIEW

**Comment by mattjj** [comment]
David, you're the man! This was always one of my favorite Autograd examples, and now it's even better because it shows off `jit` and `vmap`!

I think I just noticed an issue with the use of the PRNG here. This line may be problematic:

```python
old, rng = random.split(rng)  # 'old' isn't used anywhere
```

It's a danger sign when an output of `random.split` isn't used. (@dougalm we should really explore adding the "linear typing" check, not only to ensure the same rng key isn't used twice as we usually discuss, but also to ensure that every rng key produced by `random.split` is eventually consumed. In fact, the latter check may be more important than the former: it would have caught this and I think every other issue we've seen with PRNG use.)

The problem is that the function you're calling a couple lines up, namely `update(t, opt_state, rng)` could itself call `split` somewhere in its code. That means it could produce the same key that the next iteration's `update` is going to be fed. I'm concerned that could mean identical samples would be produced somewhere, possibly across different loop iterations, though I haven't pinned down a precise error.

A better pattern might be something like this:

```python
     rng = random.PRNGKey(0)
     for t in range(num_steps):
       rng, subrng = random.split(rng)
       opt_state = update(t, opt_state, subrng)
       callback(minmax.get_params(opt_state), t, random.PRNGKey(1))  # maybe
```

In words, we only give function calls new sub-keys that we split off from our rng key. Then no matter how they call `split` they get their own subtree of keys, independent from our own.

What do you think? (And do we want a separate, fixed PRNG key for plotting, as in the line marked "maybe"? Or do we want to use the same `subrng`? That's the plotting trick I learned from you, after all!)

I also noticed that my `random.split` code is causing you to need an unnecessary-seeming np.array here:

```python
     rngs = np.array(random.split(rng, num_samples))
```

Since [`random.split` is just making a tuple of keys from an array](https://github.com/google/jax/blob/d2bfc9ad2aca9ab451a3afdacf38677261aca228/jax/random.py#L158), I think we should instead just have `random.split` return something that is vmap-compatible by default (i.e. return an array). I'll make that change, though we could merge this PR first and then make this tweak after.

**Comment by duvenaud** [comment]
Ah, thanks for the detailed feedback!  I'm glad you brought up these issues, so I can learn the most effective style of using these new primitives.

> The problem is that the function you're calling a couple lines up, namely update(t, opt_state, rng) could itself call split somewhere in its code. That means it could produce the same key that the next iteration's update is going to be fed.

Ah, I was worried about this.  I was hoping that there was some mechanism that avoided this, but now that I think about it more, I'm not sure that what I was hoping for is even a coherent possibility.

> Or do we want to use the same subrng?

That was my intention - I wanted to show the exact same samples that were using during optimization.  Using the same RNG seemed like a nice way to do this, since the RNGs have to be threaded through everything anyways.  Although perhaps tracing the random samples through explicitly would be a more robust way to do things.  Also, I imagine that a linearity checker would forbid using the same rng for two different functions?

A third option is to forget threading through an rng, and just create a new rng each iteration based on the iteration count.  Is there any reason not to do it this way?

> I think we should instead just have random.split return something that is vmap-compatible by default (i.e. return an array). I'll make that change, though we could merge this PR first and then make this tweak after.

If you make that change, I'll be happy to update this example and rebase it.  I think your proposed change would make it worthwhile for me to remove my rng_map function and just use vmap everywhere.

**Comment by mattjj** [comment]
We talked about this off-thread, but for posterity: creating a new PRNG key on every loop iteration, with something like `random.PRNGKey(t)`, works fine. We might want to generalize that pattern so that we can create keys by combining old keys and extra data, like the loop counter in this case.

**Comment by mattjj** [comment]
@duvenaud I think you showed me an updated version of this code; want to push it onto this PR? (I admit I was waiting to merge until you pushed the update, but let me know if we should follow a different plan.)

**Comment by duvenaud** [comment]
Done.  Your update to the RNG type sped up the demo and allowed some more simplifications.

**Comment by mattjj** [comment]
Really glad you wrote this! I'm excited for things to come.

**Pull request merged**
