### PR TITLE
Added `associative_scan`.

### PR DESCRIPTION
**Pull request by dpiponi**

### CODE REVIEW

**Comment by xingyousong** [comment]
+1 much support

**Comment by ValeryTyumen** [comment]
+1

**Comment by shoyer** [comment]
How much code does this generate in the JAXpr/XLA? I am a little worried that this could generate surprisingly large amounts of code.

**Comment by mattjj** [comment]
@shoyer the amount of code is a small constant factor times the logarithm of the sequence length. Months ago, when Dan first showed this to me, he demoed it on a sequence of length 1M with no problem IIRC.

**Comment by shoyer** [comment]
Very nice, I notice now that it only calls `_scan` recursively exactly once.

**Review by mattjj — APPROVED** [review]
LGTM! Thanks so much, @dpiponi. Sorry I took 3.5 months longer to merge this than I said...

**Comment by mattjj** [comment]
Internal tests pass!

**Comment by AdrienCorenflos** [comment]
Hi, 
It would maybe be good to precise that this is the work-efficient implementation of the [prefix sum ](https://en.wikipedia.org/wiki/Prefix_sum#Algorithm_2:_Work-efficient) that you implemented, at least if I read the algorithm correctly. 
I can do it, but just wanted to check that I wasn't misreading the recursion.
Adrien

**Pull request merged**
