### PR TITLE
add note on autodiff of OOB indexing

### PR DESCRIPTION
**Pull request by jekbradbury**
Doc note suggested in https://github.com/google/jax/issues/5760

### CODE REVIEW

**Comment by jekbradbury** [comment]
Oops, looks like I need to check out and run the pre-commit workflow locally. @jakevdp I'm guessing there's no way to make jupytext run automatically on docs PRs created from the web interface?

**Review by shoyer — APPROVED** [review]

**Comment by 8bitmp3** [comment]
Just noticed that this PR - for the 🔪 Common Gotchas 🔪  notebook - can't pass the `jupytext` lint test, so it's been sitting there kind of idle 🤷‍♂️

**Comment by jakevdp** [comment]
I synced the notebook; we should be able to merge this now.

**Comment by 8bitmp3** [comment]
cool, thanks @jakevdp @jekbradbury

**Pull request merged**
