### PR TITLE
Windows build related updates

### PR DESCRIPTION
**Pull request by cloudhan**
Disable various s3 like fs support in windows build. Originally enabled due to compiling error. Now it seems upstream have addressed them.

Workaround weird issue with non-standard CUDA path. See https://github.com/tensorflow/tensorflow/issues/51040 for more information.

bazel auto download failed due to wrong machine name.

### CODE REVIEW

**Comment by cloudhan** [comment]
I added a windows builder which you can find it at https://github.com/cloudhan/jax-windows-builder

**Comment by cloudhan** [comment]
It only make the build pass, but has some problems with DLL loading.

**Comment by zhangqiaorjc** [comment]
@hawkinsp

**Comment by cloudhan** [comment]
@hawkinsp Could you take time to look into this?

**Review by hawkinsp — APPROVED** [review]

**Comment by hawkinsp** [comment]
Thanks for the PR!

**Pull request merged**
