### PR TITLE
Enable context manager name stack with `jax2tf`

### PR DESCRIPTION
**Pull request by sharadmv**
This PR enables the use of the new name stack with `jax2tf`. Previously, `jax2tf` would convert `named_call` into `tf.name_scope` and the original name stack would be used for XLA metadata like it is in JAX. 

This PR changes that behavior: now the new name stack is used for both `tf.name_scope`s *and* XLA metadata. This means a lot more information in the TF graph. It also fixes an issue with tensor names that contain `>` that can come from lambdas.

### CODE REVIEW

**Comment by sharadmv** [comment]
Repro for name issue:

```python
In [2]: import tensorflow as tf
    
In [3]: @tf.function
   ...: def f(x):
   ...:     with tf.name_scope('jax2tf__lambda>'):
   ...:         x = tf.convert_to_tensor(x, name='Cos')
   ...:         return x
   ...: 

In [4]: f(2.)
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-4-f5b314978f7c> in <cell line: 1>()
----> 1 f(2.)

~/.cache/pypoetry/virtualenvs/jax-aRPwvaRe-py3.9/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py in error_handler(*args, **kwargs)
    151     except Exception as e:
    152       filtered_tb = _process_traceback_frames(e.__traceback__)
--> 153       raise e.with_traceback(filtered_tb) from None
    154     finally:
    155       del filtered_tb

~/.cache/pypoetry/virtualenvs/jax-aRPwvaRe-py3.9/lib/python3.9/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     52   try:
     53     ctx.ensure_initialized()
---> 54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:

InvalidArgumentError: Node 'jax2tf__lambda>/Cos': Node name contains invalid characters [Op:__inference_f_5]
```

**Comment by sharadmv** [comment]
Repro for name issue:

```python
In [2]: import tensorflow as tf
    
In [3]: @tf.function
   ...: def f(x):
   ...:     with tf.name_scope('jax2tf__lambda>'):
   ...:         x = tf.convert_to_tensor(x, name='Cos')
   ...:         return x
   ...: 

In [4]: f(2.)
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-4-f5b314978f7c> in <cell line: 1>()
----> 1 f(2.)

~/.cache/pypoetry/virtualenvs/jax-aRPwvaRe-py3.9/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py in error_handler(*args, **kwargs)
    151     except Exception as e:
    152       filtered_tb = _process_traceback_frames(e.__traceback__)
--> 153       raise e.with_traceback(filtered_tb) from None
    154     finally:
    155       del filtered_tb

~/.cache/pypoetry/virtualenvs/jax-aRPwvaRe-py3.9/lib/python3.9/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     52   try:
     53     ctx.ensure_initialized()
---> 54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:

InvalidArgumentError: Node 'jax2tf__lambda>/Cos': Node name contains invalid characters [Op:__inference_f_5]
```

**Review by gnecula — APPROVED** [review]
Thanks

**Comment by sharadmv** [comment]
@rxsang PTAL

**Review by rxsang — APPROVED** [review]
Thanks!

**Pull request merged**
