### PR TITLE
[ROCm] Update ROCm builds for manylinux_2_28

### LINKED ISSUE #233: [Issue]: broken rocm_jaxlib wheels
### Problem Description

The jaxlib wheel for version v0.4.30 (from https://github.com/ROCm/jax/releases) depend on glibc 2.31 but according to its label as 'manylinux2014' should only depend on glibc 2.17 (see https://github.com/pypa/manylinux).

### Operating System

irrelevant

### CPU

irrelevant

### GPU

AMD Radeon VII

### ROCm Version

ROCm 6.1.0

### ROCm Component

_No response_

### Steps to Reproduce

wget python3 -m pip install https://github.com/ROCm/jax/releases/download/rocm-jaxlib-v0.4.30/jaxlib-0.4.30+rocm611-cp39-cp39-manylinux2014_x86_64.whl
auditwheel show jaxlib-0.4.30+rocm611-cp39-cp39-manylinux2014_x86_64.whl

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

_No response_

### Additional Information

_No response_

### LINKED ISSUE #21816: [ROCM] Error: wheel file is invalid
### Description

The wheel files distributed at https://github.com/ROCm/jax/releases are invalid. See error

```python
(jax-env) [cad14908] fvicentini@login5:~$ python3 -m pip install --verbose -U https://github.com/ROCm/jax/releases/download/rocm-jaxlib-v0.4.28/jaxlib-0.4.28+rocm611-cp311-cp311-manylinux2014_x86_64.whl
Using pip 24.0 from /lus/home/CT5/cad14908/fvicentini/jax-env/lib/python3.11/site-packages/pip (python 3.11)
Looking in indexes: https://gorgone.cines.fr//root/pypi/+simple/
Collecting jaxlib==0.4.28+rocm611
  Downloading https://github.com/ROCm/jax/releases/download/rocm-jaxlib-v0.4.28/jaxlib-0.4.28+rocm611-cp311-cp311-manylinux2014_x86_64.whl (112.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.7/112.7 MB 85.1 MB/s eta 0:00:00
ERROR: Wheel 'jaxlib' located at /tmp/pip-unpack-qej7pdlb/jaxlib-0.4.28+rocm611-cp311-cp311-manylinux2014_x86_64.whl is invalid.
```

### System info (python version, jaxlib version, accelerator, etc.)

(jax-env) [cad14908] fvicentini@login5:~$ pip --version
pip 24.0 from /lus/home/CT5/cad14908/fvicentini/jax-env/lib/python3.11/site-packages/pip (python 3.11)
(jax-env) [cad14908] fvicentini@login5:~$ python --version
Python 3.11.5

### LINKED ISSUE #22034: jaxlib wheel hardcoded to manylinux2014 platform
### Description

I am opening this issue to get a discussion started around manylinux support for JAX/jaxlib. I am currently working on trying to get manylinux_2_28 jaxlib wheels built with ROCm support for ROCm users.

Currently jaxlib wheels are hardcoded to be tagged as manylinux2014. See https://github.com/google/jax/blob/main/jaxlib/tools/build_wheel.py#L167 and https://github.com/google/jax/blob/main/jax/tools/build_utils.py#L56-L58
This hardcoding of platform name forces the wheel build process to tag the wheel filename and metadata (WHEEL file inside the zip) as manylinux2014 which is only correct if building/linking on a platform with glibc 2.17, which is rather old.
I am not aware of how google is building these wheels internally, but I imagine this is going to result in an incorrect wheel build for almost all other linux users.

I have tested a change which removes the platform name override, running a build on a Centos8 / Almalinux 8 system, and it results in a `linux_x86_64` wheel, which is expected. After running `auditwheel repair` on this wheel it correctly scans the glibc versioned symbols and creates a new manylinux_2_27 wheel (highest symbol is actually 2.27 in the output wheel). This seems more correct, although I have yet to try it with the new jax plugin wheel builds.

Some open questions are:
Is there a reason that the builds were hardcoded to manylinux2014?

Is making the above change and using auditwheel repair a path forward that works for upstream JAX/jaxlib builds?

What is the manylinux target that jaxlib needs to support going forward? manylinux2014 seems to be deprecated at the end of June 2024
from pypa/manylinux repo
> (PEP 599 defines the following platform tags: manylinux2014_x86_64, manylinux2014_i686, manylinux2014_aarch64, manylinux2014_armv7l, manylinux2014_ppc64, manylinux2014_ppc64le and manylinux2014_s390x. Wheels are built on CentOS 7 which will reach End of Life (EOL) on June 30th, 2024.)

### System info (python version, jaxlib version, accelerator, etc.)

```
```

### PR DESCRIPTION
**Pull request by mrodden**
This set of commits changes the ROCm build to build wheels inside an AlmaLinux8 (EL8) container provided by PyPA org for manylinux_2_28 compatible wheel outputs. The Docker image target (and test target) from before are run after, using these wheel outputs rather than direct source builds.

There are a few patches that I found during rebase that made small changes to the testing and build scripts that I pulled along as well. These minor changes include some testing and build script updates only.

Resolves: https://github.com/ROCm/rocm-install-on-linux/issues/233
Resolves: https://github.com/google/jax/issues/21816
Resolves: https://github.com/google/jax/issues/22034

### CODE REVIEW

**Comment by mrodden** [comment]
@hawkinsp @skye  Could you take a look and approve this for the CI flow if it looks OK?

**Review by skye — APPROVED** [review]

**Comment by mrodden** [comment]
Small update here: I have a fix for the linting failure but I am also trying to get another change included for our build team to be able to use development rocm builds, so I might push those up together.

**Comment by mrodden** [comment]
@skye This should be ready for merge / CI now.

Also, when the copybara job fails, is there some action I need to take? There doesn't seem to be any output associated with the check.

**Comment by skye** [comment]
Thanks for the update. We need to handle copybara failures, i.e. no action on your end needed (but do ping if nothing happens for a while, it probably means I queued something up and then forgot to check back later :grimacing:). I'll let you know if the error is due to something you need to change in the PR.

**Comment by skye** [comment]
Ah, @mrodden copybara failed because you're missing the license at the top of some of the new files. Please copy/paste from some other file and make sure the copyright year is 2024. Then copybara should be happy. (You had no way to view this error FYI)

**Comment by mrodden** [comment]
Added copyright and license headers and rebase on latest main

**Comment by PhilipVinc** [comment]
Sorry for the bump, but Can we get this merged and some new AMD Wheels?

Lack of this is holding off using Jax on HPCs...

**Comment by skye** [comment]
Ah sorry for the delay and thank you for the ping! Trying again...

**Comment by skye** [comment]
I think you need to resolve the merge conflicts now, so sorry :(

**Comment by mrodden** [comment]
Yeah I have the rebased branch ready on my machine, but I have a few more changes to merge in that fix issues we found from our internal CI again :/

**Comment by mrodden** [comment]
@skye This should be ready to merge now assuming it passes linting CI checks again.

I included some fixes for issues found in some of our internal CI runs.

**Comment by skye** [comment]
Awesome thanks, trying again...

**Comment by skye** [comment]
Third time's the charm! Thanks for your patience

**Pull request merged**
