### PR TITLE
Add reflect_type argument for symmetric and reflect modes in padding

### PR DESCRIPTION
**Pull request by minoring**
Related #5010

### CODE REVIEW

**Review by jakevdp — APPROVED** [review]
Looks great, thanks for the contribution!

**Comment by jakevdp** [comment]
Running a more comprehensive set of tests is revealing errors for the `bool` dtype; for example:
```
LaxBackedNumpyTests.testPadSymmetricAndReflect_shape=bool[1,4]_mode=symmetric_pad_width=((1, 2),)_reflect_type=odd

Traceback (most recent call last):
  File "/build/work/5af997c0288660df34bdcf33f52a84c4f9b3/google3/runfiles/google3/third_party/py/absl/testing/parameterized.py", line 299, in bound_param_test
    return test_method(self, **testcase_params)
  File "/build/work/5af997c0288660df34bdcf33f52a84c4f9b3/google3/runfiles/google3/third_party/py/jax/tests/lax_numpy_test.py", line 1418, in testPadSymmetricAndReflect
    tol={np.float32: 1e-3, np.complex64: 1e-3})
  File "/build/work/5af997c0288660df34bdcf33f52a84c4f9b3/google3/runfiles/google3/third_party/py/jax/test_util.py", line 900, in _CheckAgainstNumpy
    canonicalize_dtypes=canonicalize_dtypes)
  File "/build/work/5af997c0288660df34bdcf33f52a84c4f9b3/google3/runfiles/google3/third_party/py/jax/test_util.py", line 827, in assertAllClose
    self.assertDtypesMatch(x, y, canonicalize_dtypes=canonicalize_dtypes)
  File "/build/work/5af997c0288660df34bdcf33f52a84c4f9b3/google3/runfiles/google3/third_party/py/jax/test_util.py", line 807, in assertDtypesMatch
    self.assertEqual(_dtype(x), _dtype(y))
AssertionError: dtype('int64') != dtype('bool')
```

I think it's probably reasonable to test this over `number_dtypes` rather than `all_dtypes`

**Comment by minoring** [comment]
Thanks for the testing :)
I removed bool type only when`reflect_type=odd` since I believe it is OK to use bool when`reflect_type=even`.
Also, removed type conversion code that was for bool types.
PTAL!

**Comment by jakevdp** [comment]
Thanks! I'll trigger another run of the expanded test suite

**Comment by jakevdp** [comment]
Thanks for the contribution!

**Pull request merged**
