### PR TITLE
Add a few popular distributions to jax.scipy.stats

### PR DESCRIPTION
**Pull request by vishwakftw**
- Beta
- Exponential
- Gamma
- Laplace
- Uniform

This could be a precursor for adding more properties to distributions such as mean, variance and entropy.

Please let me know if this looks merge-able, and is worth adding to the package. Thank you.

### CODE REVIEW

**Comment by vishwakftw** [comment]
@googlebot I signed it!

**Comment by alexbw** [comment]
Could you please add tests? I think they should probably live in `tests/lax_scipy_stats_test.py`, but I will defer to @mattjj  or @froystig on this.

**Comment by alexbw** [comment]
And -- thanks! This is great!

**Comment by vishwakftw** [comment]
Sure, I'll do that. It seems like the logpdf tests for the normal distribution are added in test/lax_scipy_test.py. Adding tests for multiple distributions could cause a lot of clutter, hence I am advocating to move it to a separate file. Perhaps, @mattjj or @froystig could shed some light about that.

**Comment by froystig** [comment]
A new test file corresponding specifically to scipy.stats seems like a good eventual plan. In this PR, either file (existing or new) would be fine.

**Comment by mattjj** [comment]
@vishwakftw this is excellent, thanks for diving in! You might end up being our first external contributor of significant code!

Making a separate file sounds good to me. Whatever you think makes things clean! (Fortunately, file organization is relatively easy to revise later if we ever change our minds about it.)

We still need to make our tests easily runnable from OSS land, and document how to do it. For the time being, though, things like this should work from the `tests` subdirectory:

```bash
bazel test lax_test_cpu --test_output streamed --test_arg=--num_generated_cases=10
```

or alternatively even

```bash
python lax_test.py  --num_generated_cases=10
```

**Comment by vishwakftw** [comment]
@mattjj @froystig Thank you for your comments and clarifications. I'll build and test locally as advised.

**Comment by vishwakftw** [comment]
@mattjj @froystig I've added tests in a separate file in the most recent commit. Please have a look when you can. Thank you.

**Review by mattjj — CHANGES_REQUESTED** [review]
Can you rename tests/test_scipy_stats.py to tests/scipy_stats_test.py, just for consistency?

Otherwise, looks good to me!

**Comment by mattjj** [comment]
Looks great! I ran this change against our internal tests (which cover a lot of combinations of configurations and backends, including TPUs) and everything passes. If you can just change the filename of the test file (which I requested in part to test out how GitHub reviews work), this will be good to merge!

**Review by mattjj — APPROVED** [review]

**Comment by mattjj** [comment]
Thank you for the contribution!

**Pull request merged**
