### PR TITLE
[Draft] Performance Tests

### PR DESCRIPTION
**Pull request by joaogui1**
This pull request solves #104. What I have made just now is a quick draft, but I have some questions before proceeding.

1. Is there still interest in solving #104 ?
2. Do you guys think that [asv](https://github.com/airspeed-velocity/asv) is a good solution?
3. What are the main things that need performance tests? Right now I mostly copied numpy, besides that we will need to test the transformations (jit and grad, what else?), but for example should we test experimental?
Thank you for your input

### CODE REVIEW

**Comment by gnecula** [comment]
Thank you for your initiative. The answer to your question whether we still need this, is YES. The answer to the other questions is harder. I do not know ASV to be able to say whether it is a good solution. I would start with your last question: what kind of performance tests we need? And then we decide what is a good way to get there. 

I think that we need both microbenchmarks (of the kind that you have created) and also larger benchmarks (e.g., how long it takes to train a certain model to a certain precision). We need to worry both about memory usage and speed. For all of these I would like to know if we can leverage similar tools used for XLA. 

What gave you the idea of using ASV? How well does it work on shared testing environments like Travis?

**Comment by joaogui1** [comment]
I thought of using ASV because it was used in autograd and since there is a good intersection in developers from both projects it would be more familiar. I myself don't have much experience with ASV to answer all the questions, but since it is used by both Numpy and Autograd I believe it works well with testing environments.
Finally could you elaborate a bit more on the 

> for all of these I would like to know if we can leverage similar tools used for XLA." 

please? What tools were used for XLA?

**Comment by joaogui1** [comment]
So, I believe given #2143 this PR seems more important now, so pinging @gnecula

**Comment by mattjj** [comment]
Thanks for starting this! I'm just paging it in again now, and asked some other folks whether asv makes sense for microbenchmarks for us. @shoyer and @jakevdp seem to think so!

We probably want to use [`block_until_ready`](https://jax.readthedocs.io/en/latest/async_dispatch.html) right?

**Comment by mattjj** [comment]
Maybe we can separate out two questions:
1. What benchmark harness should we use? asv seems to make sense now, but also perhaps this is easy to change later as needed, so it's a Type 2 decision (in the Jeff Bezos sense).
2. What should we start with in our microbenchmark suite? We should probably think about what each thing is measuring.

The former I'm not too concerned about. On the latter, I wonder if we can try to come up with a rationale for each test, and only commit ones that have some rationale behind them. For example, some things to measure and track are:

1. jit versus op-by-op dispatch times (say directly calling some `lax` primitives, like `lax.add`), since the latter has a special-case path only for performance reasons
2. cache hit versus cache miss cases for the above
3. numpy.ndarray aguments versus jax DeviceArray arguments to jitted functions
4. some key numpy functions of interest to which we might want to apply jit or otherwise look into speeding up
5. overheads from dtype and shape promotion logic

(I'm setting aside pmap and ShardedDeviceArray ideas because those may be harder to meaningfully test in OSS.)

Those might not be the right rationales, but perhaps we can iterate here. What signals do we want to track out of this? Avoiding regressions? Monitoring progress for specific overheads we've identified and want to improve on? (Keep in mind I'm focused on microbenchmarks only in this comment.)

**Comment by mattjj** [comment]
This might give us an alternative to asv: https://github.com/google/benchmark/pull/957. I need to learn more from our Google / DM colleagues about it. Will report back when I do!

**Pull request closed without merging**
