### PR TITLE
Implement np.diff 

### PR DESCRIPTION
**Pull request by navneet-nmk**
Added np.diff (refer to #70 )

### CODE REVIEW

**Comment by mattjj** [comment]
By the way, in case it helps you iterate faster, you [can run the tests locally](https://github.com/google/jax#running-the-tests), and even [see how the Travis CI setup installs things and runs the tests](https://github.com/google/jax/blob/master/.travis.yml). You can even run a specific failing test by name, like `python tests/lax_numpy_test.py 'LaxBackedNumpyTests.testOpDiff_int64[]'`.

**Comment by navneet-nmk** [comment]
The problem is that in the onp.diff, we call normalize_axis_index on the axis for the given dimension of the array. 
In the tests, we create a 0-dimensional array and axis=-1 is invalid for these dimensions.

`axis = normalize_axis_index(axis, nd)`

Should I add a try/except or just return the array in case of 0-dimensions?

And I was also wondering whether I have to make changes to the function_base.py.

**Comment by navneet-nmk** [comment]
I checked how NumPy handles 0-dim arrays and it also throws the same exception: AxisError

`axis = normalize_axis_index(axis, nd)`
`numpy.AxisError: axis -1 is out of bounds for array of dimension 0`

I agree function_base is not in JAX. Apologies for the misunderstanding.

**Comment by navneet-nmk** [comment]
I raised an issue in the numpy GitHub project: https://github.com/numpy/numpy/issues/13296
The main response is that np.diff expects iterable arrays and therefore providing a scalar should throw an exception.

**Comment by mattjj** [comment]
We should make the tests pass before we merge (even if that means changing what cases we test this function on).

**Comment by mattjj** [comment]
Thanks for this!

**Review by mattjj — APPROVED** [review]
LGTM!

**Pull request merged**
