### PR TITLE
initial draft of hard coded docstrings

### PR DESCRIPTION
**Pull request by joaogui1**
Related to #2979, creates an external docstrings file and allows us to hardcode docstrings

### CODE REVIEW

**Comment by gnecula** [comment]
Thank you for helping clean up the documentation. Am I correct saying that for the specific case of `sqrt` we want to remove the mention or `lib.scimath.sqrt` (as pointed out in #2979) and the `where` parameter (which is missing from the new documentation)?

I think that we should avoid making a copy of the numpy documentation. Perhaps we can just add a note about differences, and then include the original documentation? 

If instead we do want JAX-specific documentation, I think that it is best to put it next to the 
definition of `jax.numpy.sqrt` instead of a separate file. My thinking is that there is no point in inventing a new mechanism for associating documentation with definitions. 

@skye PTAL

**Comment by joaogui1** [comment]
@gnecula  I don't understand the comment about `where`, it's not in the documentation and I think JAX doesn't support it, right?
The idea of the separate file was so we wouldn't change too much the library because of a small problem (in this case a somewhat confusing comment in the docstring of a single function) and we could keep that up until/if the number of custom docstrings grows considerably

**Comment by gnecula** [comment]
Re: `where`, I just wanted to make sure that I understand the scope of the changes, since it was not mentioned in #2979 as a problem. JAX does not support it and it is fine that is missing from the documentation. 

I am assuming that needing a custom documentation is the exception, not the common case. In those cases, I think it is preferable to add a docstring where the function is defined, rather than 
putting it in a separate file, for the same reason that `numpy` has the documentation in docstrings rather than in a separate file. 

My preference would be to just have a short paragraph that explains how JAX's version is different than numpy (assuming the differences are small and easily explainable), and then include verbatim the numpy documentation. This way we do not have to maintain a 
separate documentation string than numpy. 

We can see what Skye thinks also. @skye

**Comment by hawkinsp** [comment]
Another comment is that we must respect copyright here. I haven't looked into the details, but at a minimum anything copied from NumPy (e.g., doc strings) must go in the `third_party/numpy` directory.

**Comment by skye** [comment]
I like this proposal. Peter correctly points out we should put the docstrings in `jax/third_party/numpy`, which sounds like reason enough for putting the docstrings in a separate file, so I won't go into why I thought it was a good idea even without the copyright consideration.

We could just add a note to the top of the documentation. As I see it, the upshot is that we don't need this extra complexity. The downside is lower-quality documentation (e.g. "blah blah blah ... please disregard the confusing bit below ... confusing bit ...", and in this case the confusing bit is highlighted in an eye-catching box). There's probably some argument about updates to the original numpy documentation, but I think that could go either way depending on if the updates still align with what our version of the function does :) Am I missing anything?

I think it's worth having the higher-quality documentation, and it clears the way for future improvements of this kind. However, I'd also be ok adding the note for now and seeing if it comes up for other numpy functions.

**Comment by gnecula** [comment]
I'd be interested to know how many cases we know of where we need to have custom documentation, and what are the cases when it is really awkward to rely on a comment at the top to list unimplemented or different behavior.

**Comment by hoffmannjordan** [comment]
I noticed that `vander` also [references](https://jax.readthedocs.io/en/stable/_autosummary/jax.numpy.vander.html
) something that isn't (yet) in JAX.
`nanmax` [references](https://jax.readthedocs.io/en/stable/_autosummary/jax.numpy.nanmax.html) `fmin()` which isn't implemented.
I haven't gone through looking, though, so I'm guessing there are more.

**Comment by jakevdp** [comment]
I'm -1 on specializing docstrings further: it seems like it would open us to playing an eternal, unwinnable game of whack-a-mole (in particular, even when we're "done" with a particular numpy release, in the sense of there being no more non-jax functions mentioned, the next numpy release might modify docstrings further)

Currently the numpy docs are prefaced by "Original documentation below", which (to me) implies that I'm reading the numpy docstring. Perhaps we could make the language in that indicator more clear? Something like
```
"This function provides a jax implementation of the np.sqrt function. Numpy docstring below:"
```
That would be far more maintainable in the long-run.

**Comment by jakevdp** [comment]
This situation will also be improved by our adopting the convention of importing jax.numpy as ``jnp`` rather than ``np``; that will make it more clear that the numpy portions docstrings are referrring to numpy, rather than jax.

**Comment by joaogui1** [comment]
I don't think so. 
We are implementing `jax.numpy`, which already makes one think they will be dealing with an API compatible with Numpy, then if we use the same docstring users will be really confused when the JAX functions don't work the same way Numpy functions do

**Comment by gnecula** [comment]
Let's try to make progress on this. I see that several of us have expressed reservations about making an almost-copy of the numpy documentation. I think that the maintainability cost is still an issue even if we put it in third_party/numpy. How about the following compromise:

* We have the option to add a custom docstring to lax.numpy primitives, along with the definition of the primitive.
* The _wrap function will do what it does already, except that it can insert this custom docstring before it includes the original numpy implementation
* We put in that custom docstring only what is specific about lax implementation. This may include notes about how it differs from the original numpy.

**Comment by skye** [comment]
I think what I wrote in [my above comment](https://github.com/google/jax/pull/3023#issuecomment-626804362) is still true. Re: Jake's point about numpy versions, I would guess having an accurate version of older numpy docs would usually be better than the updated numpy version (especially since I'm guessing most updates to numpy documentation are to introduce new features that jax doesn't support).

It sounds like everyone else prefers a note at the top though, so let's do that, and we can revisit if people are still confused. It looks like `_wraps` already supports this ([link](https://github.com/google/jax/blob/master/jax/numpy/_util.py#L85)), so it's just a matter of adding the note.

**Pull request closed without merging**
