### PR TITLE
Make `dimensions` argument of `bcoo_reshape` optional.

### PR DESCRIPTION
**Pull request by geraschenko**

### CODE REVIEW

**Review by jakevdp — APPROVED** [review]
Looks good, thanks!

**Comment by geraschenko** [comment]
Whoops. I forgot to fix the matching "broadacsted" -> "broadcasted" typo in the test. Serves me right for trying to sneak that in.

**Review by jakevdp — COMMENTED** [review]
Looks good, can you squash the changes into a single commit? (See https://jax.readthedocs.io/en/latest/contributing.html#single-change-commits-and-pull-requests) Thanks!

**Review by jakevdp — APPROVED** [review]
Thanks!

**Pull request merged**
