### PR TITLE
adding div and linear prims

### PR DESCRIPTION
**Pull request by jessebett**
@jacobjinkelly and I implemented div together as well as the ones with `ad.deflinear`

### CODE REVIEW

**Comment by jacobjinkelly** [comment]
@googlebot I consent.

**Comment by mattjj** [comment]
Googlebot is unhappy because of my @csail.mit.edu address being on some commits (I can override that), but it's also unhappy because duvenuad@cs.toronto.edu needs to consent.

Let's ping David!

**Comment by duvenaud** [comment]
@googlebot I consent.

**Comment by mattjj** [comment]
Woohoo, thanks!

**Pull request merged**
