### PR TITLE
Fix dictionary key sorting in `tree_util`

### PR DESCRIPTION
**Pull request by XuehaiPan**
Function `sorted` does not support sorting with different types.

```python
>>> sorted({1: 0, 'a': 1})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'str' and 'int'
```

This will cause errors when manipulating dictionaries that have different key types.

```python
>>> import jax.tree_util as pytree
>>> pytree.tree_flatten({1: 1, 2: 2})
([1, 2], PyTreeDef({1: *, 2: *}))
>>> pytree.tree_flatten({'a': 1, 'b': 2})
([1, 2], PyTreeDef({'a': *, 'b': *}))
>>> pytree.tree_flatten({1: 1, 'a': 2})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../venv/lib/python3.9/site-packages/jax/_src/tree_util.py", line 60, in tree_flatten
    return pytree.flatten(tree, is_leaf)
TypeError: '<' not supported between instances of 'str' and 'int'
```

Since Python 3.6, the keys are insertion ordered.

NOTE: same change should be made for the jaxlib C extension (tensorflow/tensorflow#57122).

### CODE REVIEW

**Comment by apaszke** [comment]
While this might solve your use case, I'm afraid that it can lead to surprising results. The order here is used to decide the PyTree structure. If you have two dicts that are not key-sortable and have different key orders, but are otherwise equivalent, they will lead to two different and incompatible pytrees.

**Comment by XuehaiPan** [comment]
> If you have two dicts that are not key-sortable and have different key orders, but are otherwise equivalent, they will lead to two different and incompatible pytrees.

Thanks for pointing out this. Do you mean there are two types that are not comparable (not support `inst1 < inst2`), but the `__eq__` / `__hash__` methods are overloaded (`inst1 == inst2`)?

**Comment by apaszke** [comment]
Yes, I agree that the tree construction is deterministic. But I would claim that dictionary key order has no influence on the meaning of a Python dict (use OrderedDict for that). As you've noticed, they will always compare equal, even though they use different orders. And I think that it is important that two equal objects produce equal pytrees, which is false in your example.

**Comment by XuehaiPan** [comment]
> As you've noticed, they will always compare equal, even though they use different orders. And I think that it is important that two equal objects produce equal pytrees, which is false in your example.

Despite the non-sortable case, the old implementation also does not guarantee `tree1 == tree2` -> `pytree.tree_leaves(tree1) == pytree.tree_leaves(tree2)`.

Here I add a new `__lt__` method to the example in https://github.com/google/jax/pull/11871#issuecomment-1212997687, where `KeyType2`'s order is reversed:

```python
class KeyType1(KeyTypeBase):
    def __lt__(self, other: object) -> bool:
        if isinstance(other, KeyType1):
            return self.key < other.key  # <<<
        return False

class KeyType2(KeyTypeBase):
    def __lt__(self, other: object) -> bool:
        if isinstance(other, KeyType2):
            return self.key > other.key  # >>>
        return False
```

```python
In [2]: tree1 = {KeyType1(0): 0, KeyType1(1): 1}

In [3]: tree2 = {KeyType2(1): 1, KeyType2(0): 0}

In [4]: list(tree1)
Out[4]: [KeyType1(0), KeyType1(1)]

In [5]: list(tree2)
Out[5]: [KeyType2(1), KeyType2(0)]

In [6]: tree1 == tree2
Out[6]: True

In [7]: import jax.tree_util as pytree  # jaxlib 0.3.15

In [8]: pytree.tree_flatten(tree1)
Out[8]: ([0, 1], PyTreeDef({KeyType1(0): *, KeyType1(1): *}))

In [9]: pytree.tree_flatten(tree2)
Out[9]: ([1, 0], PyTreeDef({KeyType2(1): *, KeyType2(0): *}))

In [10]: pytree.tree_leaves(tree1) == pytree.tree_leaves(tree2)
Out[10]: False
```

**Comment by apaszke** [comment]
Sure, nothing is guaranteed in Python. You can always come up with contraptions like this one. Our current implementation assumes that they keys have a total order, and your example violates that.

And I think it's not only about the implementation. pytree flattening is about converting a nested data structure into a sequence, it is ill-defined to attempt to do that unless the elements of any given container can be given a total order.

**Comment by XuehaiPan** [comment]
> Our current implementation assumes that they keys have a total order

What if we sort by `key = (obj.__class__.__qualname__, obj)`? It will have a total order that `key[0]` is a string and always is comparable.

**Comment by XuehaiPan** [comment]
Hi @apaszke, a gentle ping for this. The XLA upstream (https://github.com/tensorflow/tensorflow/pull/57122#issuecomment-1538488523) would decide to review the corresponding change if this PR is also accepted.

Is there any progress on this? For sortable keys, this PR is fully backward compatible. While for non-sortable keys, it sorts the keys by `key=lambda o: ('{0.__module__}.{0.__qualname__}'.format(o.__class__), o)` rather than raises a `TypeError`. If the JAX community thinks we need to raise an error when the keys are not directly comparable, I can close this PR.

**Comment by XuehaiPan** [comment]
Closing for now due to inactivity.

**Pull request closed without merging**
