### PR TITLE
[Pallas]: Fix CUDA kernel grid dimensions that are too large in Y and Z

### LINKED ISSUE #18361: [Pallas] GPU: CUDA error when kernel launch dimensions >= 65536 in Y or Z
### Description

The following code (adapted from the pallas quickstart) results in a CUDA error, because Pallas tries to launch the resulting CUDA kernel with too large a grid in the Y dimension.

```python
import jax
from jax import random
from jax.experimental import pallas as pl

def add_vectors_kernel(x_ref, y_ref, o_ref):
  x, y = x_ref[...], y_ref[...]
  o_ref[...] = x + y

@jax.jit
def add_vectors(x: jax.Array, y: jax.Array) -> jax.Array:
  return pl.pallas_call(add_vectors_kernel,
                        out_shape=jax.ShapeDtypeStruct(x.shape, x.dtype)
                        )(x, y)

# add batch dimension
add_vectors = jax.vmap(add_vectors)

# Standard [N, C] succeeds because leading dimension is mapped to X dim in launch grid
print(add_vectors(random.uniform(random.PRNGKey(5), (65536, 64)),
                  random.uniform(random.PRNGKey(6), (65536, 64))))

# Adding another batch dimension
add_vectors = jax.vmap(add_vectors)

# Fails, because now N = 65536 is mapped to the Y dim in launch grid
print(add_vectors(random.uniform(random.PRNGKey(5), (4, 65536, 64)),
                  random.uniform(random.PRNGKey(6), (4, 65536, 64))))
```

On my machine (jax & jaxlib head, jax-triton 1f41ec2 and triton-nightly-2.1.0.dev20231014192330, cuda 12), the above code prints the following:
```
Launching [N, C]
[N, C] success 0.9997495412826538
Launching [P, N, C]
2023-11-02 14:19:11.657404: W external/xla/xla/service/gpu/runtime/support.cc:58] Intercepted XLA runtime error:
INTERNAL: jaxlib/gpu/triton_kernels.cc:259: operation gpuLaunchKernel( kernel, grid[0], grid[1], grid[2], block_dim_x_, 1, 1, shared_mem_bytes_, stream, params, nullptr) failed: CUDA_ERROR_INVALID_VALUE
2023-11-02 14:19:11.657424: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2716] Execution of replica 0 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.custom_call' failed: jaxlib/gpu/triton_kernels.cc:259: operation gpuLaunchKernel( kernel, grid[0], grid[1], grid[2], block_dim_x_, 1, 1, shared_mem_bytes_, stream, params, nullptr) failed: CUDA_ERROR_INVALID_VALUE; current tracing scope: custom-call.0; current profiling annotation: XlaModule:#hlo_module=jit_add_vectors,program_id=6#.
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pallas_error.py", line 29, in <module>
    r = add_vectors(random.uniform(random.PRNGKey(5), (4, 65536, 64)),
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.custom_call' failed: jaxlib/gpu/triton_kernels.cc:259: operation gpuLaunchKernel( kernel, grid[0], grid[1], grid[2], block_dim_x_, 1, 1, shared_mem_bytes_, stream, params, nullptr) failed: CUDA_ERROR_INVALID_VALUE; current tracing scope: custom-call.0; current profiling annotation: XlaModule:#hlo_module=jit_add_vectors,program_id=6#.
```

For context, I'm hitting this issue in my population-based-training codebase, where I'm training an ensemble of models simultaneously using jax.vmap over my update loop (this expands the training loop inputs from shape [N, C] to [P, N, C], where P is my population size and P << N). I'm using pallas to optimize certain layers within my model, and I hit this error when N >= 65536.

The core issue is twofold:
1. The pallas_call batching rule internally *prepends* the vmapped dimension to GridMapping
2. When mapping this to a 3D CUDA grid, [`_process_grid_to_3d_grid`](https://github.com/google/jax/blob/main/jax/_src/pallas/triton/lowering.py#L167) just assigns the GridMapping dims from left to right to X, Y, and Z in the kernel launch.

The problem is that the CUDA API [specifies](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#features-and-technical-specifications) that the max dimensions for a launch are [2^31 - 1, 65535, 65535] for the 3D grid. I believe the intent is that adjacent threadblocks will be assigned along the x dimension first (like the inner loop in a triple nested for loop over z, y, then x). 

Given these semantics, I think it would actually make the most sense for the pallas_call batching rule to *append* the vmapped dimensions to the GridMapping rather than prepending them, but I don't know if that would have negative implications for the TPU backend. That would result in a 2D kernel launch of size [65536, 4] in my above example. For >3 grid dimensions, `_process_grid_to_3d_grid` could collapse the additional dimensions into the Z launch dimension rather than X, although something would need to be done if the resulting Z dimension was greater than 65535.

To sidestep all these issues in my own repo and avoid changing the pallas_call batching rule, I've replaced `_process_grid_to_3d_grid` with an implementation that just collapses all the dimensions into X, resulting in a one dimensional kernel launch, leveraging the fact that the X launch dimension can go all the way up to 2^31 - 1:
```python
def _process_grid_to_3d_grid(builder, grid_mapping: GridMapping):
  if len(grid_mapping.grid) == 0:
    return grid_mapping.grid, []

  total_axis_size = np.prod(grid_mapping.grid)
  new_grid = (total_axis_size,)

  def make_subidx(cur_idx, s):
    return (
        cur_idx.__floordiv__(s, _builder=builder),
        cur_idx.__mod__(s, _builder=builder),
    )

  grid0 = tl.program_id(0, _builder=builder)
  out_indices = [0] * len(grid_mapping.grid)

  # Preserve existing ordering for non-mapped dims
  for i, s in enumerate(grid_mapping.grid):
    if i in grid_mapping.mapped_dims:
      continue

    grid0, out_indices[i] = make_subidx(grid0, s)

  # For mapped dims, iterate the inner mapped dims to the outer dims. This 
  # follows the pallas_call batching rule that prepends the vmapped dimension.
  # Intuitively, it makes sense to iterate over the inner mapped dimensions first.
  for dim in reversed(grid_mapping.mapped_dims):
    s = grid_mapping.grid[dim]
    grid0, out_indices[dim] = make_subidx(grid0, s)

  return new_grid, out_indices
```

This fixes the above crash for me (and all the pallas tests still pass). The downside of this approach is that the resulting kernel has to do a bit more indexing math. I haven't checked for a performance impact yet (although I doubt it would be significant).

Please let me know if I should open a pull request with this solution (or I'd be happy to implement it differently if some other strategy is more desirable).

### What jax/jaxlib version are you using?

jax c8b7c1b80 (HEAD), jaxlib c8b7c1b80

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.10, Linux

### NVIDIA GPU info

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        Off | 00000000:01:00.0  On |                  N/A |
| 30%   48C    P8              42W / 350W |   1296MiB / 24576MiB |      3%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+------------------
----+
```

### PR DESCRIPTION
**Pull request by shacklettbp**
Fixes https://github.com/google/jax/issues/18361

This uses a more involved approach than originally proposed in the issue:
1) Reverse the pallas grid mapping and use this as the base cuda launch grid
2) Collapse excess dimensions (>3) into the X dimension as suggested by @sharadmv
3) Iterate over the resulting dimensions and check if any are too large. Collapse into X if so. This is important because you can easily run into the bug described in the issue with < 3 dimensions depending on the vmap / batch ordering.

**Important Note**: This PR changes the behavior of existing pallas GPU kernels even without vmapping, because the grid mapping => launch grid ordering has been flipped. So the attention kernel for example now will perform a [num_heads, batch_size] launch rather than [batch_size, num_heads]. This might be confusing to users familiar with Triton. A different solution would be to only flip the order of the vmapped dimensions, and preserve the grid ordering specified in pallas_call.

I also added a couple simple vmap tests that catch the bug without this patch applied.

### CODE REVIEW

**Comment by sharadmv** [comment]
Thanks, this generally LGTM but re: your note. Does the launch grid ordering have any implication on correctness/numerics? My understanding is that it wouldn't.

**Comment by shacklettbp** [comment]
No there are no implications for the kernel output / correctness. CUDA doesn't provide guarantees on cross-threadblock execution ordering / threadblock mapping to SMs anyway (unless you're using something like cooperative grids, which pallas / triton are not).

The only impact would be if some existing pallas GPU user has determined empirically that a certain grid ordering provides better performance with their kernel (perhaps due to threadblocks mapped to the same SM accessing adjacent memory having some caching effects?), and then we flipped that grid ordering which might impact performance.

**Comment by sharadmv** [comment]
Are you able to verify the speed of the pallas flash attention kernel with and without the changes?

**Comment by shacklettbp** [comment]
I've just gone ahead and tested performance with and without this PR using the benchmark script from https://github.com/google/jax/pull/17328 (just the benchmark script, not including his attention improvements).

This is all on a RTX 3090 (I don't have ready access to anything better).

It turns out the grid ordering does make a small but measurable performance difference:
Perf without this PR:
prepatch

Perf with this PR:
postpatch

Perf with this PR with the attention kernel manually edited to use a flipped grid:
postpatch_flipattention_grid

For fun, performance with my original implementation of _process_grid_to_3d_grid that collapses everything in X (note that this function only reverses grid order for mapped dimensions (none in this case)):
flatgrid

(I ran each of these multiple times and the results are consistent - I'd say all but the second result are close enough to not really matter).

I see the following options:
1) Merge this PR as is, patch the attention kernel to use a flipped grid. I think this maintains the most consistency between pallas kernels and the rest of JAX,  because the grid specification follows the same [outer, to, inner] ordering as normal JAX (which this PR then maps to [Z, Y, X] in the CUDA launch. The downside of this is divergence from triton, in particular because flipping the grid specification requires changing program IDs in the kernel. Probably would be worth a note in the docs.
2) Change this PR to preserve the order of the grid provided at the pallas_call site while appending vmapped dimensions in reverse order. This is what original "fully collapse into X" patch did, although with the new code we can preserve the 3D CUDA launch. The upside to this is there should be no performance change for existing pallas kernels, grid order and program IDs follow triton.

**Comment by sharadmv** [comment]
We want to avoid compromising on performance whenever possible. I think Option 2 thus makes the most sense. If the grid ordering in Triton/CUDA has meaningful performance implications, we should follow those conventions as much as we can to avoid performance footguns.

**Comment by sharadmv** [comment]
Thank you for your thorough investigation.

**Comment by shacklettbp** [comment]
Just pushed an implementation of option 2 to the PR (and reduced some line lengths to better fit the existing style).

As shown here, we're back to attention performance without the patch:
newpatch

**Review by sharadmv — APPROVED** [review]
Thank you!

**Pull request merged**
