### PR TITLE
Add jnp vs np out of bounds indexing to Sharp Bits nb

### PR DESCRIPTION
**Pull request by hoffmannjordan**
Added a section on the differences in out of bounds indexing to the 🔪 Sharp Bits notebook.

### CODE REVIEW

**Comment by skye** [comment]
This is a great addition, thanks! I made some very minor cleanup changes.

**Comment by gnecula** [comment]
I suspect that this change in the Gotchas notebook triggers failures in the documentation build. 

See https://travis-ci.org/github/google/jax/jobs/661093689?utm_medium=notification&utm_source=github_status

I am confused how come Travis did not fail for this change. It fails in #2401.

**Comment by skye** [comment]
Ah sorry, I didn't wait for the Travis presubmit because I forgot we build the notebooks as part of it!

**Comment by skye** [comment]
Matt fixed this in https://github.com/google/jax/pull/2402 btw (thanks Matt!!)

**Pull request merged**
