### PR TITLE
Update installation directions in README to mention expected CUDA location.

### PR DESCRIPTION
**Pull request by skye**
See https://github.com/google/jax/issues/989

### CODE REVIEW

**Comment by refraction-ray** [comment]
Hi, there. I think it would be better that the recommended approach is setting XLA_FLAGS. the symlink approach is more limited. For example, what if the user doesn't have sudo permission on the system and thus fail seting the symlink to /usr. Or if there are multiple cuda installations that the user wanna use with jax. Switching an enviroment variable is simpler than switching the sysmlink as far as I am concerned.

**Comment by gnecula** [comment]
> Hi, there. I think it would be better that the recommended approach is setting XLA_FLAGS. the symlink approach is more limited. For example, what if the user doesn't have sudo permission on the system and thus fail seting the symlink to /usr. Or if there are multiple cuda installations that the user wanna use with jax. Switching an enviroment variable is simpler than switching the sysmlink as far as I am concerned.
> 

+1

**Comment by hawkinsp** [comment]
The only thing I will caution you is that `XLA_FLAGS` is not a stable API; it is subject to change at any time.

**Comment by skye** [comment]
@refraction-ray great points about symlinks. I didn't read the original thread closely enough and wasn't sure if the XLA_FLAGS option actually worked, but rereading it looks like it does :) I just added a blurb about that as well. @hawkinsp I didn't mention the unstable aspect, we can always update the README again and it probably won't change for a while at least (right?). But good to know.

**Comment by skye** [comment]
I'm gonna go ahead and merge this, but please feel free to comment if you have further suggestions!

**Pull request merged**
