### PR TITLE
Fix `loc` and `scale` parameters in `scipy.logistic.*`. Add CDF and SF for several distributions

### PR DESCRIPTION
**Pull request by b0nce**
This is a continuation of [previous PR](https://github.com/google/jax/pull/14839) with fixes for extended tests:
 - added forgotten `strict_promotion_if_dtypes_match` for tests of logistic distribution
 - `rtol` for PPFs and ISFs in `_CompileAndCheck`
 - `_lax_constant` with `cdf_result` type in gamma and beta (since internal numpy's `betainc` and `gammainc` can change returned type)
 - `inf` wrapped with `_lax_const` in every `lax.clamp` call (to overcome fails in x64)

@jakevdp, waiting for your review :)

### CODE REVIEW

**Comment by b0nce** [comment]
Hey @jakevdp, you previously said you will help me to land this PR. Is that still the case? Is there anything I need to change?

**Comment by jakevdp** [comment]
Sure, sorry I didn't see this come through.

Can you rebase your files and fix conflicts? Then we'll be able to run the tests and make sure the issues are fixed.

**Review by jakevdp — APPROVED** [review]
Thanks! Let's try running the tests

**Review by jakevdp — APPROVED** [review]
OK, seems like tests are passing now. Thanks for digging back into this!

**Comment by b0nce** [comment]
Hey @jakevdp, will this be merged automatically or some other actions required from my side?
Also, thanks for such a welcoming experience of contribution to jax :)

**Pull request merged**
