### PR TITLE
add ravel_pytree to generated docs

### PR DESCRIPTION
**Pull request by jakevdp**
Addresses https://github.com/google/jax/issues/3124#issuecomment-891409507

### CODE REVIEW

**Review by froystig — APPROVED** [review]

**Comment by carlosgmartin** [comment]
@jakevdp Out of curiosity, is there any reason why [`ravel_pytree`](https://jax.readthedocs.io/en/latest/_autosummary/jax.flatten_util.ravel_pytree.html) is under [`flatten_util`](https://jax.readthedocs.io/en/latest/jax.flatten_util.html) (where it is the only function) rather than [`tree_util`](https://jax.readthedocs.io/en/latest/jax.tree_util.html) with the other tree functions?

**Comment by mattjj** [comment]
I think it's because tree_util doesn't depend on any array stuff (array data types, jax.numpy, etc) whereas the ravel stuff does.

**Comment by carlosgmartin** [comment]
@mattjj Another question: Is excluding `flatten_util` from [`jax.__init__`](https://github.com/google/jax/blob/main/jax/__init__.py) (unlike, say, `tree_util`) intentional?

**Comment by froystig** [comment]
Yeah, that is intentional.

**Comment by carlosgmartin** [comment]
@froystig Thanks. Do you know why it's excluded? (Just trying to understand the architectural decisions a bit better.)

**Comment by froystig** [comment]
We haven't seen a strong case for considering it a public API (in turn taking on the cost of maintainenance according to the [compatibility policy](https://jax.readthedocs.io/en/latest/api_compatibility.html)). We generally try to keep a minimal API surface.

**Pull request merged**
