### PR TITLE
Add sentence explaining user guide

### PR DESCRIPTION
**Pull request by canyon289**
Putting this up for early discussion. Admittedly I struggled on what else to add, both in terms of context, and additional content. Will continue thinking through this through the week in prep for our Friday discussion

### CODE REVIEW

**Comment by jakevdp** [comment]
What would you think about adding more organization/context to the table of contents, similar to the [notes](https://jax.readthedocs.io/en/latest/notes.html) or [advanced tutorials](https://jax.readthedocs.io/en/latest/advanced_guide.html) sections?

**Comment by canyon289** [comment]
i think its a great idea, a good dimension of organization to add, and I appreciate the nudge. Will update PR

**Review by jakevdp — APPROVED** [review]
Looks great, thanks!

It's still marked as a draft – are you happy to merge this?

**Comment by canyon289** [comment]
I am happy to merge this. Let me collapse into one commit and mark as ready for review. Thanks Jake

**Comment by canyon289** [comment]
Collapsed to single commit with no code changes. Marked ready for review

**Review by jakevdp — APPROVED** [review]

**Pull request merged**
