### PR TITLE
(Github CI) Bump ci-build's pre-commit action version

### PR DESCRIPTION
**Pull request by ArjunSharda**

### CODE REVIEW

**Review by jakevdp — APPROVED** [review]
Looks good, thanks!

**Comment by jakevdp** [comment]
Oops, spoke too soon. Seems like this version isn't valid.

**Comment by ArjunSharda** [comment]
Ah, let me update.

**Comment by ArjunSharda** [comment]
Just updated. I hope it should be valid now.

**Comment by jakevdp** [comment]
Thanks - can you squash the changes into a single commit? (see https://jax.readthedocs.io/en/latest/contributing.html#single-change-commits-and-pull-requests) Thanks!

**Comment by ArjunSharda** [comment]
> Thanks - can you squash the changes into a single commit? (see https://jax.readthedocs.io/en/latest/contributing.html#single-change-commits-and-pull-requests) Thanks!

Oh, but i'm not using a IDE, I was just looking through the files and saw this.

**Comment by ArjunSharda** [comment]
> I see - our policy is one commit per change. Are you able to squash these at another time? Alternatively, you could make your branch writeable for maintainers and I could do it for you – that's typically enabled by default, but it's disabled for this PR.

Sure

**Comment by ArjunSharda** [comment]
> I see - our policy is one commit per change. Are you able to squash these at another time? Alternatively, you could make your branch writeable for maintainers and I could do it for you – that's typically enabled by default, but it's disabled for this PR.

I've gave you access to edit it

**Review by jakevdp — APPROVED** [review]

**Comment by jakevdp** [comment]
OK, thanks!

**Pull request merged**
