### PR TITLE
Add methods to interact with `DeviceArray` objects.

### PR DESCRIPTION
**Pull request by jblespiau**
We are going to add a C++ implementation, this is a useful refectoring to ease the transition. In short,

- `isinstance(x, DeviceArray)` will continue to work
- type(x) is DeviceArray will be replaced by `type_is_device_array(x)`
- DeviceArray(...) constructor will be replaced by `get_device_array(...)`.

### CODE REVIEW

**Review by mattjj — APPROVED** [review]
LGTM! I have a slight preference for the name `make_device_array` over `get_device_array`, but that's easy to change later if we want.

**Comment by jblespiau** [comment]
I am fine doing the change, just waiting for Peter if he has additional things to say. @hawkinsp

**Comment by hawkinsp** [comment]
I agree with Matt's suggestion, otherwise LGTM.

**Comment by jblespiau** [comment]
Done :)

**Review by hawkinsp — APPROVED** [review]

**Pull request merged**
