### PR TITLE
Remove 'from __future__ import annotations'

### PR DESCRIPTION
**Pull request by hawkinsp**

### CODE REVIEW

**Review by jakevdp — APPROVED** [review]

**Comment by hawkinsp** [comment]
Hmm. Apparently this change isn't a no-op. I guess definition ordering matters?

**Comment by jakevdp** [comment]
Lint failures are because ruff is linting in Python 3.9: https://github.com/google/jax/blob/2985b623bcad6ba12a98ee0d3023402c79061478/pyproject.toml#L104

**Comment by jakevdp** [comment]
Oh, but maybe the future annotations import is still needed to get the behavior of https://peps.python.org/pep-0649/

**Comment by jakevdp** [comment]
ruff fix in #22126

**Comment by superbobry** [comment]
Yeah, we still need that import in some cases and tbh it's probably a good idea to have it by default to avoid paying the runtime cost of type annotations.

**Pull request closed without merging**
