### PR TITLE
Bump minimum jaxlib version from 0.4.6 to 0.4.7.

### PR DESCRIPTION
**Pull request by skye**
Also removes a bunch of dead version guards (0.4.7 has xla_extension_version 144 and mlir_api_version 47)

### CODE REVIEW

**Comment by yashk2810** [comment]
Please remove the mlir_api_version guards too!

**Comment by skye** [comment]
Removed the mlir_api_version guards

**Review by yashk2810 — APPROVED** [review]

**Comment by yashk2810** [comment]
Thanks! Can you add it to the description like you did for xla_extension_version?

**Comment by skye** [comment]
Done

**Pull request merged**
