### PR TITLE
DOC: Add code examples to `jax.scipy.stats.sem` docs

### PR DESCRIPTION
**Pull request by rajasekharporeddy**

### CODE REVIEW

**Comment by unworld11** [comment]
can this be assigned to me?
please provide description

**Review by jakevdp — APPROVED** [review]
Looks good, thanks!

**Comment by rajasekharporeddy** [comment]
Variable `nan` was used without defininf it which casued errors in example code snippet tests. Fixed it now and sqaushed into single commit.

**Review by jakevdp — APPROVED** [review]

**Comment by jakevdp** [comment]
Hi @unworld11 – sorry to miss your comment. We generally assign reviews to JAX team members, but do feel free to chime in on PRs if you'd like to help!

**Pull request merged**
