### PR TITLE
add fwd+rev hvp section to autodiff cookbook

### PR DESCRIPTION
**Pull request by mattjj**

### CODE REVIEW

**Comment by alexbw** [comment]
It's hard to comment directly on the colab cells, so I'll paste in some possible changes.

First, I think you're implementing reverse-over-forward, which isn't what we should recommend for HVPs. Please correct me if I'm reading it wrong. Here are the functions we should be testing on:

```
def revrev_hvp(f, x, v):
    return grad(lambda x: np.vdot(grad(f)(x), v))(x)

from jax import jvp, grad

# <<< I believe this is what was added in this pull request. It's reverse-over-forward
def revfwd_hvp(f, primals, tangents):
  g = lambda primals: jvp(f, primals, tangents)[1]
  return grad(g)(primals)

# <<< this is the recommended configuration
def fwdrev_hvp(f, x, v):
  return jvp(lambda x: grad(f)(x), (x,), (v,))[1]
```

```
# Updated cell to demonstrate we get the same answer as a naive full materialization of the Hessian
def f(X):
  return np.sum(np.tanh(X)**2)

key, subkey1, subkey2 = random.split(key, 3)
X = random.normal(subkey1, (2, 3))
V = random.normal(subkey2, (2, 3))

ans1, = revfwd_hvp(f, (X,), (V,))
ans2 = np.tensordot(hessian(f)(X), V, 2)

print(ans1)
print(ans2)
```

```
# A small benchmark to show fwd-over-rev is faster
# NOTE: we could bump up the size of W to accentuate differences.
print("Reverse over reverse")
%timeit -n10 -r3 revrev_hvp(f, X, V)
print("Reverse over forward")
%timeit -n10 -r3 revfwd_hvp(f, (X,), (V,))
print("Forward over reverse")
%timeit -n10 -r3 fwdrev_hvp(f, X, V)
print("Naive full Hessian materialization')
%timeit -n10 -r3 np.tensordot(hessian(f)(X), V, 2)
```
On default cloud colab instance, prints
```
Reverse over reverse
10 loops, best of 3: 18.6 ms per loop
Reverse over forward
10 loops, best of 3: 19.1 ms per loop
Forward over reverse
10 loops, best of 3: 14.2 ms per loop
Naive full Hessian materialization
10 loops, best of 3: 26.1 ms per loop
```

**Comment by mattjj** [comment]
You’re right, forward over reverse would be best! I’ll update it.

**Comment by mattjj** [comment]
Though I *think* (not sure) all have roughly the same FLOP cost, and forward-over-reverse and reverse-over-forward should have the same memory costs, but the overheads will differ. I remember us discussing this on the same Autograd issue where we figured out forward-from-reverse.

**Comment by mattjj** [comment]
Updated! Including that timing code is a great idea.

**Review by alexbw — APPROVED** [review]
lgtm!

**Comment by mattjj** [comment]
For posterity, I dug up the comment thread with @j-towns and @jekbradbury on the Autograd issue tracker where we thought through the asymptotic FLOP cost of rev-over-rev and fwd-over-rev:

https://github.com/HIPS/autograd/pull/175#issuecomment-305916378

**Comment by mattjj** [comment]
@alexbw Thanks for the review, the correction to use the best fwd-over-rev stuff, and the timing additions!

**Comment by alexbw** [comment]
Also note in that autograd thread the beginnings of JAX's strategy for
reverse-mode autodiff implementation!

**Pull request merged**
