### PR TITLE
Fixed `ShapeDtypeStruct((), None)` giving float64 under 32-bit mode

### PR DESCRIPTION
**Pull request by patrick-kidger**
As title!

### CODE REVIEW

**Comment by jakevdp** [comment]
I wonder if `dtype=None` should raise an error here instead? It seems like an unintended use to me.

**Comment by patrick-kidger** [comment]
FWIW I figured this was intended. I think it's convenient to be able to specify "please use the default precision", without having to manually check `jax.config.jax_enable_x64` manually oneself.

(E.g. we use it in Diffrax [here](https://github.com/patrick-kidger/diffrax/blob/ea1bdc9a590093898ca5f75342c6f1bcbced1039/diffrax/brownian/tree.py#L78), although if you wanted we could easily change that.)

**Comment by jakevdp** [comment]
Raising an error seems safer to me.

**Comment by froystig** [comment]
If we were to allow it, would it always be a `float` (of the default precision), and not an integer type?

**Comment by jakevdp** [comment]
Numpy chooses float:
```python
>>> np.dtype(None)
dtype('float64')
```
but I still think for a lower-level API, requiring an explicit non-None dtype is better than assuming user intent.

**Comment by jakevdp** [comment]
> How would we recommend one succinctly write what @patrick-kidger is looking for, namely "give me a dtype of the default precision"?

We don't have a well-defined API for that. As currently implemented, `jnp.result_type(float)` will return the default floating-point type though (i.e. respecting the values of the JAX_DEFAULT_DTYPE_BITS and JAX_ENABLE_X64 flags)

**Comment by jakevdp** [comment]
Would it make more sense for `jnp.dtype` to include canonicalization, rather than just being an alias for `np.dtype`?

**Comment by froystig** [comment]
Wondering the same, but not sure. Maybe a new function, with a new and descriptive name, would be clearer and avoid surprises. I could imagine a case for having it live in the top-level `jax` module—something like `jax.canonical_dtype`—so that it can also resolve (trivially) any opaque dtypes (not in numpy).

cc @mattjj, at least for the opaque dtypes bit

**Comment by patrick-kidger** [comment]
Closing due to lack of interest.

**Comment by jakevdp** [comment]
> How would we recommend one succinctly write what @patrick-kidger is looking for, namely "give me a dtype of the default precision"?

I realized we do have a decent answer for this:
```python
import jax
from jax import dtypes

with jax.experimental.enable_x64():
  print(dtypes.result_type(None))
  print(dtypes.result_type(float))
  print(dtypes.result_type(int))
```
```
float64
float64
int64
```
```python
with jax.experimental.disable_x64():
  print(dtypes.result_type(None))
  print(dtypes.result_type(float))
  print(dtypes.result_type(int))
```
```
float32
float32
int32
```
I still think that for `ShapeDtypeStruct`, it should probably raise an error for `dtype = None`. I'm going to give that a try and see if it breaks anyone.

**Pull request closed without merging**
