### PR TITLE
random: add values test cases for various distributions

### PR DESCRIPTION
**Pull request by jakevdp**
Why? In addressing https://github.com/google/jax/issues/9896, I plan to modify the implementation of `gamma`, `beta`, and `dirichlet`. For backward compatibility, we want to ensure that the sequence of values generated by these routines does not change in such refactorings; this PR adds a framework whereby we can test this for these and other distributions.

### CODE REVIEW

**Review by froystig — CHANGES_REQUESTED** [review]
Let's test RNG implementations other than the default as well. The easiest way might be to do so under assumption that #9263 is complete. Here's an [example](https://github.com/google/jax/blob/4d966bb9ac9ae5aa058cebfc0e59dfa0f8bc64b4/tests/random_test.py#L701-L709).

**Comment by jakevdp** [comment]
OK, updated to test all distributions on multiple PRNG backends. PTAL!

**Review by froystig — APPROVED** [review]
Looks good! Maybe add to the docstring when/how one might update these when making changes, or what policy to follow (in particular, do we need to version and deprecate?).

**Comment by jakevdp** [comment]
> Maybe add to the docstring when/how one might update these when making changes, or what policy to follow

Done

**Pull request merged**
