### PR TITLE
[random] wrap_key_data accepts impl=key.dtype.impl

### LINKED ISSUE #17758: jax.random.wrap_key_data(impl=key.impl) problems
### Description

Problem: I would expect the following to work, in order to programmatically wrap/unwrap keys, but it does not

```python
b = jax.random.key(1)
jax.random.wrap_key_data(jax.random.key_data(b), impl=b.impl)
```

as it fails with error
```python
File ~/Documents/pythonenvs/netket/python-3.11.2/lib/python3.11/site-packages/jax/_src/random.py:139, in resolve_prng_impl(impl_spec)
    136   return PRNG_IMPLS[impl_spec]
    138 keys_fmt = ', '.join(f'"{s}"' for s in PRNG_IMPLS.keys())
--> 139 raise ValueError(f'unrecognized PRNG implementation "{impl_spec}". '
    140                  f'Did you mean one of: {keys_fmt}?')

ValueError: unrecognized PRNG implementation "fry". Did you mean one of: "threefry2x32", "rbg", "unsafe_rbg"?
```

### What jax/jaxlib version are you using?

jax==master (today, 25 September) jaxlib==0.4.16

### Which accelerator(s) are you using?

CPU

### Additional system info

MacOs

### NVIDIA GPU info

_No response_

### PR DESCRIPTION
**Pull request by jakevdp**
Fixes #17758

### CODE REVIEW

**Review by froystig — COMMENTED** [review]
I suspect that we don't want `impl` to be a public member of the key array class. We want key arrays to be identical to other jax arrays, and this attribute is a divergence at the moment.

**Comment by jakevdp** [comment]
Note that `impl` is not a member of the key class, but rather a member of the key-specific `dtype` class.

**Comment by froystig** [comment]
Oh, thanks for correcting me there. Adjusting: what do you think of introducing `key_impl` that accepts a dtype (maybe as well as a key array)? And then we hide the `.impl` attribute of the `.dtype`-returned object too, as well as any other attributes! The key dtype could mostly be opaque from a public API perspective.

**Comment by jakevdp** [comment]
Are you proposing something like this for the new API?
```python
def wrap_key_data(key_bits_array: Array, *, impl: Optional[str] = None, dtype: Optional[ExtendedDtype] = None):
  if dtype is not None:
    assert impl is None
    impl_obj = dtype.impl  # eventually a private attribute
  else:
    impl_obj = resolve_prng_impl(impl)
  return prng.random_wrap(key_bits_array, impl=impl_obj)
```

**Comment by froystig** [comment]
Not quite. What I'm suggesting we consider is keeping `wrap_key_data` as is, and then introducing a new function `key_impl`. The `key_impl` function takes a dtype (maybe also an array, for convenience) and returns a string specifying the implementation. The string, when passed back to `wrap_key_data`, closes the round trip:

```python
k = jax.random.key(...)
data = jax.random.key_data(k)
impl = jax.random.key_impl(k)    # or k.dtype
k2 = jax.random.wrap_key_data(data, impl=impl)
assert k.dtype == k2.dtype
```

Separately, I'm suggesting we hide `.impl` from the `k.dtype` object's public attributes. What do you think of that?

**Comment by jakevdp** [comment]
> ... returns a string specifying the implementation. The string, when passed back to wrap_key_data, closes the round trip:

OK, in that case it sounds like we'll need `PRNGKeyImpl` to have some kind of registry system, whereby when it is created it will register its name with some dictionary that maps strings to impls that can then be used by `resolve_prng_impl`.

We'll have to figure out what to do if someone tries to register a duplicate impl name: probably the best thing would be to error in that case, because it could cause unintended consequences. An annoying part about that though is if you're developing iteratively in a notebook, then re-executing a cell that defines your `PRNGKeyImpl` would lead to a duplicate registration error.

Another option is that rather than returning a unique string identifier, we instead return the actual `PRNGImpl` object. What do you think?

**Comment by jakevdp** [comment]
Another observation here: `jax.random.default_prng_impl()` returns a `PRNGImpl` object, not a string. I've found a case where a user is doing something like:
```python
key = jax.random.key(seed, impl=jax.random.default_prng_impl())
```
which seems like it should work, but it doesn't for the reasons discussed above.

If we decide to go with the "impls are only referred to by their string name" route, we'll have to figure out what to do with `jax.random.default_prng_impl()`.

**Comment by jakevdp** [comment]
Replaced by #17983

**Pull request closed without merging**
