### PR TITLE
Implement Poisson distribution for jax.scipy.stats

### PR DESCRIPTION
**Pull request by TuanNguyen27**
An attempt to implement #1518

### CODE REVIEW

**Comment by TuanNguyen27** [comment]
@googlebot I signed it!

**Comment by hawkinsp** [comment]
The Travis builds are failing with errors like:
```
_ LaxBackedScipyStatsTests.testPoissonLogPmf_float32[1,4]_float32[1,4]_float32[1,4] _
[gw0] linux2 -- Python 2.7.15 /home/travis/miniconda/bin/python
self = <scipy_stats_test.LaxBackedScipyStatsTests testMethod=testPoissonLogPmf_float32[1,4]_float32[1,4]_float32[1,4]>
    @functools.wraps(test_method)
    def bound_param_test(self):
      if isinstance(testcase_params, abc.Mapping):
>       test_method(self, **testcase_params)
```

I think perhaps you need to add a line to `jax/scipy/stats/__init__.py` ?

**Comment by TuanNguyen27** [comment]
Thanks for the catch, @hawkinsp !

**Comment by hawkinsp** [comment]
Thanks for the PR!

**Pull request merged**
