### PR TITLE
Fix time issues in odeint reverse mode

### PR DESCRIPTION
**Pull request by samuela**
This is an attempt at addressing the issues brought up in comments [here](https://github.com/google/jax/commit/7e480fa923097826febec8ac6b74222dca6189a3#r38709808) and [here](https://github.com/google/jax/commit/7e480fa923097826febec8ac6b74222dca6189a3#r38709906). This PR is intended to correct issues with the handling of time in the reverse-mode odeint solve.

Ideally we could write a regression test for this. Where would be the right place for such tests?

### CODE REVIEW

**Comment by mattjj** [comment]
Thanks for looking at this! I've now paged this out from my brain, but I am not yet convinced it's buggy...

We don't have a test file for odeint yet (we really should!), and instead just have a simple test and benchmark in ode.py itself. See `pend_check_grads`. If you run the file as a script it'll run.

**Comment by samuela** [comment]
Ok, I added a test in 04bae57! Indeed the implementation in this PR passes, while the existing implementation fails:
```python
AssertionError:
Not equal to tolerance rtol=0.002, atol=0.002

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 41.74458046
Max relative difference: 8.3973634
 x: array(-36.773427)
 y: array(4.971153, dtype=float32)
```

**Comment by mattjj** [comment]
Wow, looks like you are right! Attn @duvenaud @jessebett @jacobjinkelly @sharadmv , looks like odeint has a bug.

**Comment by mattjj** [comment]
Thanks so much for finding this and adding the test, @samuela ! Looks like I did indeed introduce this bug in #2026, and the tests were too weak to catch it. To verify, I checked out 6876271b, did a `pip install --upgrade jaxlib==0.1.42`, and tweaked the code to work with the old api (which also only supported first-order differentiation):

```python
def weird_time_pendulum_check_grads():
  """Test that gradients are correct when the dynamics depend on t."""
  dyn = lambda y, t: np.array([y[1] * -t, -1 * y[1] - 9.8 * np.sin(y[0])])
  def f(y0, ts):
    return build_odeint(dyn)(y0, ts)

  y0 = np.array([np.pi - 0.1, 0.0])
  ts = np.linspace(0., 1., 11)

  check_grads(f, (y0, ts), modes=["rev"], order=1)
```

**Comment by duvenaud** [comment]
FYI, I think there's a simpler and more general way to handle this problem, which is to allow jax's ```odeint``` to handle integration backwards in time.   It's easy to handle: just check if ```t1``` is less than ```t0```, and if so, swap ```t1``` and ```t0```, and replace ```f(y, t, args)``` with ```-f(y, -t, args)```.

If you make this change to ```odeint```, it'll match Scipy's ```odeint``` better, will be more general, and then the vjp of ```odeint```won't have to do this negative munging itself.

**Comment by jacobjinkelly** [comment]
@duvenaud Agreed I think it'd be a good idea to handle integration backwards in time. Since there can be multiple `ts` I think we should actually to do a change of variables and flip their signs like [here](https://github.com/rtqichen/torchdiffeq/blob/master/torchdiffeq/_impl/misc.py#L184-L187) in torchdiffeq.

**Comment by duvenaud** [comment]
Whoops, yes @jacobjinkelly pointed to the correct reversing algorithm.  I'll delete my wrong one above.

**Comment by samuela** [comment]
@duvenaud I like the idea of keeping consistency with scipy, but I do feel obligated to point out that supporting reverse time integration does add a bit of complexity to the calling contract for `odeint`. Previously it was that `ts` had to be monotonically increasing, but now the contract would have to be something like if `ts` is monotonically increasing do X, if `ts` is monotonically decreasing do Y, else throw an error. 

I know that in some cases JAX has thoughtfully avoided repeating certain design patterns in numpy/scipy/matlab. I'm not sure if this should be one of those cases, but I just wanted to mention it.

**Comment by duvenaud** [comment]
That's a fair point.  I guess I'll just say that I know of two examples where we want time-reversibility:
1) The VJP of odeint that you just implemented,
2) The FFJORD demo I'm working on , where encoding runs time in one direction, and decoding runs time in the other.

Finally, we could in principle allow ```ts``` not to have any enforced order (except for a special time zero), and just sort them internally and run the ODE forwards and/or backwards wherever needed to cover that range.  That would be a simpler contract (and I like the idea of separating out time zero anyways), in which case disallowing negative times would be the more-complex contract.

**Comment by jessebett** [comment]
@samuela This fix is awesome thanks for finding it! 

To echo what @duvenaud is saying, supporting reverse time integration is good not just because it is consistent with numpy. The choice of direction for the variable of integration, "time", is often arbitrary. E.g. in the case of FFJORD one direction corresponds to sampling and the reverse direction corresponds to inference.

**Pull request merged**
