### PR TITLE
Check presence of __jax_array__ in _arraylike before calling it in is…

### PR DESCRIPTION
**Pull request by rsepassi**
…scalar

### CODE REVIEW

**Comment by jakevdp** [comment]
Hi - can you say more about the motivation for this change?

**Comment by rsepassi** [comment]
Sure. This ensures that the narrower property of whether the value has the `__jax_array__` property is checked before actually calling it within `isscalar`. The motivation is that I'm working on a small `LazyArray` library that attempts to delay array materialization as late as possible when interacting with JAX functions, and the current order of calls here forces materialization earlier than is optimal.

**Comment by jakevdp** [comment]
Makes sense, thanks!

**Review by jakevdp — APPROVED** [review]

**Comment by rsepassi** [comment]
Thanks!

**Pull request merged**
