### PR TITLE
Strengthened type checking for while and cond

### PR DESCRIPTION
**Pull request by gnecula**
See https://github.com/google/jax/issues/1681.

### CODE REVIEW

**Review by mattjj — APPROVED** [review]
LGTM! The new tests for error messages are a huge improvement, and good error messages are especially important for complex primitives like these control flow ones. Thanks!

**Comment by mattjj** [comment]
I think the apparent test failure was just Travis barfing, not to do with these changes.

**Comment by gnecula** [comment]
> I think the apparent test failure was just Travis barfing, not to do with these changes.

I saw that, did you manually triggered a rerun? Or did it recover by itself?

**Comment by skye** [comment]
I manually triggered a rerun.

**Pull request merged**
