### PR TITLE
DOC: add GPU & TPU installation tabs on index page

### PR DESCRIPTION
**Pull request by jakevdp**
As discussed this morning.

202036b0-174f-4af4-b167-e96923e7336c

Live preview: https://jax--14047.org.readthedocs.build/en/14047/#installation

### CODE REVIEW

**Review by zhangqiaorjc — APPROVED** [review]
Super nice! Thanks Jake!

**Comment by yashk2810** [comment]
Can we add a bit more customization?

CPU/GPU (2 cuda versions)/TPU/MAC?

**Comment by jakevdp** [comment]
Sure, but everything is a balance between having too little information up front and having too much information up front. I tried adding extra info here and it looked busy to me. But feel free to give it a try if you disagree!

**Comment by yashk2810** [comment]
Adding one more cuda version and mac tab is not too much information IMO. It would be sad if users can't find that information too :)

I think install page should be about full information. It doesn't matter if we have a couple more options IMO.

**Pull request merged**
