### PR TITLE
Verify that the inputs to reverse-mode automatic differentiation are …

### LINKED ISSUE #424: Grad should raise an error for non-inexact types
Continuation of https://github.com/google/jax/issues/48 .

`grad` should report an error for integer/bool types (i.e., non-inexact types):

e.g., this example should report an error:

```
def square(x):
  return x**2

val = 3
dfn = grad(square)
print(dfn(val))
```

### PR DESCRIPTION
**Pull request by hawkinsp**
…of an inexact type.

Fixes #424

### CODE REVIEW

**Comment by hawkinsp** [comment]
I should add that it feels awkward that I have to reflatten the primals but I couldn't come up with a better way. Suggestions welcome.

**Comment by mattjj** [comment]
Could we follow this pattern instead?

https://github.com/google/jax/blob/11320c7edb71920c94c80b64f2ae4ec751cfae45/jax/api.py#L342

https://github.com/google/jax/blob/11320c7edb71920c94c80b64f2ae4ec751cfae45/jax/api.py#L350

That is, before turning things into jaxtupletrees, just call a tree_map over `primals`? (Also a similar pattern in jacrev.)

(`primals_flat` is a misnomer, it's really more like `primals_jaxtupletree`.)

I don't think there's a clear advantage to one pattern or the other, but it might be nice to be consistent, and to factor the checking code out into a function. Maybe we could say having the check before the `pytree_to_jaxtupletree` call is catching the error slightly earlier.

WDYT?

**Comment by hawkinsp** [comment]
Changed to use the `tree_map` formulation. I left the type test after the `_check_args` call; the error if the input isn't a valid JAX type is more readable from `_check_args` than this test.

Added a test.

PTAL

**Review by mattjj — APPROVED** [review]
LGTM!

**Pull request merged**
