### PR TITLE
re-export `dtype_real` from jax.dtypes

### PR DESCRIPTION
**Pull request by PhilipVinc**
This was being exported previously.

### CODE REVIEW

**Comment by jakevdp** [comment]
Hi - thanks for flagging this.

The change you reference deliberately cleaned up JAX's public API. We chatted a bit about this offline, and I think we'd prefer for this utility to not be part of JAX's public API, as it really has more to do with numpy dtypes than anything special to JAX. If you want a quick way to get this result, you can do something like this:
```python
def dtype_real(dtype):
  return np.finfo(dtype).dtype if np.issubdtype(dtype, np.complexfloating) else dtype
```

**Comment by PhilipVinc** [comment]
I see.
Indeed it might be something that should be in numpy.  
But it isn't.
Most people probably don't use complex numbers, but since jax's support of complex numbers in AD is somewhat... contrived, this is a fundamental function to have. 

Looking at jax.dtpes I see the following symbols:
```python
>>> jax.dtypes.
jax.dtypes.bfloat16(            jax.dtypes.finfo(               jax.dtypes.iinfo(               jax.dtypes.result_type(
jax.dtypes.canonicalize_dtype(  jax.dtypes.float0               jax.dtypes.issubdtype(          jax.dtypes.scalar_type_of(
```

`result_type` In particular! if I need to compute the result type of an operation that is R->R or C->R, I have the need for `dtype_real`, otherwise how can I compute the result?

This, for me, is telling that it is essential when computing dtypes.

**Comment by jakevdp** [comment]
I'm not certain I understand the relationship to `result_type`, which is basically JAX's version of `np.result_type` specialized to JAX's promotion logic.

The `dtype_real` utility is only used in one place in JAX; unless there are good arguments for keeping it, I'd probably be in favor of removing it altogether.

**Comment by PhilipVinc** [comment]
My argument is that `np.result_type` allows you to compute the type promotion logic of some operation involving two types. 
So if I write a custom jax primitive doing something like a sum `+(a,b) = a+b`, I can implement the abstract evaluation logic using `np.result_type(a, b)`.
But If I write a custom jax primitive doing something like a norm `custom(a) = a.conj()*a` the abstract evaluation logic needs `dtype_real`. You can write your own, `dtype_real` with a series of `if,else`, but that is ugly.

use cases I have for it are (what we are using it in NetKet): 
  - computing the resulting `dtype` of statistical objects (variance, autocorrelation time...) which are all real-valued even if the input data is complex-valued. 
  - In some layers with precise mathematical properties, we want some parameters to be real no matter what, while the rest can be complex too. We ask the user to specify the dtype of the layer, which can be any floating-point type, but then need to extract the `real_dtype`.

In essence, yes, `dtype_real` is fairly niche in that not a lot of people care about complex numbers.

For people who care about complex numbers, this is an important tool and avoids littering the code with 
`dtype_real= lambda typ:jnp.ones((), typ)).real` or smarter implementations. 

Again, I do think that this should be a numpy thing really, but as it's not, I think it's a fairly useful thing to be included in jax.

**Comment by jakevdp** [comment]
Thanks for outlining your thinking. It still seems to me that a utility that's not specific to JAX, is used only once in all the JAX codebase, and that can be reproduced in a single line is not a great candidate to be part of the public API.

**Pull request closed without merging**
