### PR TITLE
Implement scipy.polar

### PR DESCRIPTION
**Pull request by AidanGG**
Part of https://github.com/google/jax/issues/1999. This code is mostly taken from SciPy itself. Are tests necessary (and where would they go)? Also, does documentation need to be regenerated?

### CODE REVIEW

**Comment by shoyer** [comment]
> Part of #1999. This code is mostly taken from SciPy itself.

Please put code copied and/or adapted from SciPy into `jax/third_party/scipy/`.

> Are tests necessary (and where would they go)?

Yes, please. `tests/linalg_test.py` seems like a natural place (but we really aren't too picky).

> Also, does documentation need to be regenerated?

The docstring should be autogenerated by the `wraps` decorator, but you'll need to manually add an entry to the list in `docs/jax.scipy.rst`.

**Comment by AidanGG** [comment]
Thank you, I will make those changes soon.

**Comment by oleg-kachan** [comment]
Any possibility of merging this?

**Comment by shoyer** [comment]
This needs tests, per my comment above

**Comment by AidanGG** [comment]
Sorry, I haven't had a chance to work on it lately. Maybe I will have some time this week.

**Comment by hawkinsp** [comment]
#7335 and #7338 add an implementation of `jax.scipy.linalg.polar`.

**Comment by AidanGG** [comment]
Very cool, that gives the flexibility to perform SVD via QDWH-based polar decomposition and eigh, as an alternative to divide-and-conquer or QR iteration.

**Pull request closed without merging**
