### PR TITLE
Remove unnecessary code in autodiff colab

### PR DESCRIPTION
**Pull request by djdongjin**
1. Fix a typo in the autodiff colab.
2. Remove unnecessary __future__ code.

I followed the `Update notebooks` documentation, but please check the format of new colabs and let me know if they need to be further modified.

### CODE REVIEW

**Comment by skye** [comment]
Hi, thanks for this contribution! It's super hard to tell from the github diff, but it looks like this change is also removing the outputs from a few cells (at least according to a Google-internal tool that does a better job of rendering the diff). Would it be possible for you to manually edit the existing notebook files in this case instead of regenerating them, so we can see the actual diff and make sure there aren't other unintended changes? We run these notebooks as part of the presubmit, so it'll raise an error if they don't run.

(I realize this isn't what the "Update notebooks" documentation says right now -- I'm looking into finding a workflow that allows us to easily update the notebooks and also see a meaningful diff, lemme know if you have any suggestions!)

**Comment by djdongjin** [comment]
@skye, hey! I have created a new pr #2623, which seems much clear. Please have a look!

**Comment by gnecula** [comment]
> Hi, thanks for this contribution! It's super hard to tell from the github diff, but it looks like this change is also removing the outputs from a few cells (at least according to a Google-internal tool that does a better job of rendering the diff). Would it be possible for you to manually edit the existing notebook files in this case instead of regenerating them, so we can see the actual diff and make sure there aren't other unintended changes? We run these notebooks as part of the presubmit, so it'll raise an error if they don't run.
> 
> (I realize this isn't what the "Update notebooks" documentation says right now -- I'm looking into finding a workflow that allows us to easily update the notebooks and also see a meaningful diff, lemme know if you have any suggestions!)

Is it possible to see a diff of the output? I am afraid that cherry-picking the cells contents manually may put a tall barrier to colab changes. The cost would be disproportionately high for small fixes, and completely unmanageable for large ones.

**Comment by skye** [comment]
I'm looking into better ways to see the diff so we don't have to make manual changes like this. One possible lead I have is that creating a notebook in one notebook editor and then modifying it in another can cause enough minor differences to screw up the diff (e.g. mixing Colab and Jupyter). @djdongjin were you using Colab to make changes to and export the notebook, or something else?

**Comment by djdongjin** [comment]
> I'm looking into better ways to see the diff so we don't have to make manual changes like this. One possible lead I have is that creating a notebook in one notebook editor and then modifying it in another can cause enough minor differences to screw up the diff (e.g. mixing Colab and Jupyter). @djdongjin were you using Colab to make changes to and export the notebook, or something else?

Hey, for this closed pr with a lot of diffs, I use colab and export in place of the old notebooks (as in the doc). For the other new pr with fewer diffs, I just modify the notebook in vscode, without running the modified cells.

**Comment by skye** [comment]
Thanks for the info. I'm guessing these notebooks were created and subsequently edited in Colab before your made this PR, so maybe the different editors theory is out... I'll have to try playing around with saving new versions of Colabs and see if I can produce meaningful diffs.

**Comment by djdongjin** [comment]
@skye The [tensorflow instruction](https://www.tensorflow.org/community/contribute/docs#interactive_notebooks) seems reasonable, e.g., open colab by feeding the notebook link in github repo, instead of uploading the notebook in your local repo. Then download it in place of the old one in your local repo and send a pr.

another thing I am not sure is whether the notebook should include outputs. If not include outputs, some figures may be missing. If include outputs, I suggest that, for each notebook, use the `run all` option in colab to make the execution_count in order, which can reduce some unnecessary diff.

**Comment by skye** [comment]
Ah good find with the TF instructions! We do include outputs in the notebooks, so adding the "Run all" workflow to our instructions is also a good idea. Thank you!

**Pull request closed without merging**
