### PR TITLE
Fix exception causes in api.py

### PR DESCRIPTION
**Pull request by cool-RR**

### CODE REVIEW

**Comment by mattjj** [comment]
Thanks for the contribution!

Could you explain a bit what this makes better? That is, do you have an example where this change leads to better error messages?

**Comment by cool-RR** [comment]
@mattjj 
In all the cases I've touched, before the change, you would get a 2 tracebacks for the 2 exceptions, with this message between them:

    During handling of the above exception, another exception occurred:

This text is not appropriate here. It basically means "Your error-handling code has a bug in it" which is not the case here, your error-handling code is working well. After my change, the correct message will be displayed:

    The above exception was the direct cause of the following exception:

**Comment by cool-RR** [comment]
@hawkinsp
My pleasure. I'd like to raise awareness about this feature, so people will pay attention to the message and understand its meaning. 

>  I wonder if we should be suppressing the inner exception entirely because it describes an implementation detail

I'm gonna recommend against that. When I'm debugging, I'm like a man who got lost in the desert and is about to die of thirst. Any possible insight into what happened is like an oasis, even if there are just a few drops of water there.

Also, some tools like Django and Sentry show you all the local variables for your stacktraces, which is a godsend. These often have important information that sheds light on what went wrong, and if you remove the traceback they'll be gone.

**Comment by cool-RR** [comment]
Let me know if you'll be interested in getting PRs for this same issue for other parts of the code.

**Comment by skye** [comment]
+1 thanks for this PR! I'm a python n00b and always wondered about the confusing double stack traces, now I know! I think PRs fixing this elsewhere would be great.

**Pull request merged**
