### PR TITLE
Update doc with the other error that can be thrown.

### PR DESCRIPTION
**Pull request by nouiz**
The error is raised here: https://github.com/nouiz/jax/blob/f578d78f2b93cfba49f158f3f916097de982b725/jax/_src/distributed.py#L194

### CODE REVIEW

**Review by jakevdp — APPROVED** [review]
Thanks!

**Comment by jakevdp** [comment]
Did you intend to add that additional commit to this branch?

**Comment by nouiz** [comment]
> Did you intend to add that additional commit to this branch?

Yes. But I can split that to another PR if you prefer. I won't modify it again unless you tell it is needed.

**Comment by jakevdp** [comment]
It's just a bit awkward when new changes are added after I've already approved initial changes and started the process of pulling them in – it might lead to partially-merged PRs.

**Comment by nouiz** [comment]
Sorry about that. I didn't saw that you approved and started the merge. Will double check/comment about that next time.

**Comment by jakevdp** [comment]
Initial commit was merged as 48b90181e54618bf80d5ca99074b8878d94ce479.

If there are other changes you want to make, please open a new PR.

**Pull request closed without merging**
