### PR TITLE
DOC: Add code examples to `jax.scipy.fft.idct` and `jax.scipy.fft.idctn` docs

### PR DESCRIPTION
**Pull request by rajasekharporeddy**

### CODE REVIEW

**Comment by jakevdp** [comment]
It looks like some of the outputs are wrong in the docs - can you update? Thanks!

**Comment by jakevdp** [comment]
It looks like some of the outputs are wrong in the docs - can you update? Thanks!

**Comment by rajasekharporeddy** [comment]
Thanks! Updated the outputs in the examples.

**Comment by jakevdp** [comment]
Looks good! Last thing is to squash the changes. Thanks!

**Comment by rajasekharporeddy** [comment]
Thanks! Squashed into single commit.

**Review by jakevdp — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
