### PR TITLE
Improve the random module documentation.

### PR DESCRIPTION
**Pull request by jblespiau**
See https://screenshot.googleplex.com/64DMcYXyDc34gV7 (internal link only) to visualize how it's rendered by Sphinx.

### CODE REVIEW

**Comment by jakevdp** [comment]
Also can be previewed here: https://jax--10302.org.readthedocs.build/en/10302/jax.random.html#advanced

**Comment by jakevdp** [comment]
Thanks - do we need to mention the `enable_custom_prng` flag?

**Comment by jblespiau** [comment]
I don't know anything about this `enable_custom_prng`. Do you want to describe to me what it does, so I can add it there, or is it simpler to review & submit this CL, and if someone who knows what this is  wants to document it, they can?

(The only description I found is: https://jax--10302.org.readthedocs.build/en/10302/_autosummary/jax.enable_custom_prng.html?highlight=enable_custom_prng which seems to say it's a transient flag).

**Comment by jakevdp** [comment]
Yes, it's a transient flag, but without setting it to True the alternate random number generators described in your doc cannot be used.

**Review by froystig — APPROVED** [review]
We can ignore the `enable_custom_prng` flag for now. I made it operate orthogonally to `default_prng_impl`, and we aren't encouraging its use until everything works when it is enabled (see #9263 for status).

**Pull request merged**
