### PR TITLE
DOC: Improve docs for `jnp.trim_zeros`

### PR DESCRIPTION
**Pull request by rajasekharporeddy**
Part of #21461

Rendered output:
- https://jax--23540.org.readthedocs.build/en/23540/_autosummary/jax.numpy.trim_zeros.html

### CODE REVIEW

**Review by jakevdp — APPROVED** [review]
Thanks!

**Comment by rajasekharporeddy** [comment]
Thanks! I would remove the annotation in this PR and open another PR for that. Also, `jnp.tim_zeros` works for python list inputs also. Since JAX APIs doesn't take python lists as input, can we make this compatible with other APIs by introducing an array check using `check_arraylike` for this API?

**Comment by jakevdp** [comment]
Yeah, good catch! We should definitely restrict this to arraylike inputs, but that will require a deprecation cycle (you can see similar things in process for other functions in this file)

**Review by jakevdp — APPROVED** [review]
Thanks! I'll look for your PRs with the followup fixes to annotations and checking arraylike inputs.

**Pull request merged**
