### PR TITLE
handle weak types in all lax primitives

### PR DESCRIPTION
**Pull request by jakevdp**
This changes the default weak type rule such that outputs match the inputs; this seems to be the appropriate default behavior, and there are only a few standard primitives that require something different.

### CODE REVIEW

**Review by mattjj — APPROVED** [review]
The code LGTM, but is there a way to add some test coverage for any new behaviors? Without test coverage it's hard to tell if these changes have the desired effect (and what that effect is), and also it risks accidentally regressing things in the future.

**Comment by jakevdp** [comment]
We could add test coverage, but it would be a bespoke test for each lax function. There is already bulk coverage of desired behavior for standard unary and binary operations.

Maybe a new test suite class within `lax_test.py`?

**Comment by mattjj** [comment]
Hmm... since AIUI there are only two operative functions (`_strip_weak_type` and `_argnum_weak_type`), how about we just test one primitive for each? That is, no need to be exhaustive, perhaps?

**Comment by jakevdp** [comment]
I added some tests that, while not comprehensive, cover the bulk of the new code paths.

**Pull request merged**
