### PR TITLE
improve jnp.reshape's error message

### PR DESCRIPTION
**Pull request by mattjj**
At HEAD, here's the traceback we get by evaluating `jnp.reshape(3, 2)` in ipython with `JAX_TRACEBACK_FILTERING=auto` (ie with default traceback filtering):
image

Here's the message after this PR:
image

The PR makes two changes:
1. do some validation of the new shape a bit earlier
2. add two `__tracebackhide__` lines

If we didn't want to add these `__tracebackhide__ = True` lines, we'd get this:
image

I think I like the `__tracebackhide__`s, but what do you think, reviewer? The addition to the `meth` function will affect other Array/ShapedArray method call tracebacks, not just those of `jnp.reshape`, but I think that frame should always be hidden...

### CODE REVIEW

**Comment by mattjj** [comment]
There are some bugs to fix, but I requested a review for the basic strategy; assume I'll fix the failures!

**Comment by mattjj** [comment]
Maybe we should gate the addition of `__tracebackhide__ = True` on the config option? We'd only be able to switch it at import time though...

**Review by froystig — APPROVED** [review]
> Maybe we should gate the addition of `__tracebackhide__ = True` on the config option? We'd only be able to switch it at import time though...

Would it be doable with the help of some indirection (e.g. `__jax_tracebackhide__`) coupled with our traceback filtering machinery?

I think the error message is already an improvement! Approving for that. Up to you whether to experiment with config-gated traceback-filtering in this PR. Would be nice if it isn't too complicated.

**Comment by mattjj** [comment]
> Would it be doable with the help of some indirection (e.g. __jax_tracebackhide__) coupled with our traceback filtering machinery?

An excellent suggestion, wish I had thought if it myself :P

I'll give it a shot.

**Comment by mattjj** [comment]
Hrm, I realized the perhaps-obvious issue that our traceback filtering machinery isn't even being applied here, so we'd have to start applying it.

Also, ipython already has ways to adjust how it managers `__tracebackhide__` frames, namely the `%xmode --show` or `%xmode Verbose` magics, or the `skip_hidden False` ipdb command.

Since I don't want to start applying the general traceback hiding machinery somewhere we aren't already using it, I started to lean back towards land-and-iterate-if-we-come-up-with-improvements.

**Pull request merged**
