### PR TITLE
Clean up jax.numpy.__init__

### PR DESCRIPTION
**Pull request by skye**
This is hopefully the first of several commits to clean up the symbols we export.

### CODE REVIEW

**Comment by skye** [comment]
@hawkinsp @shoyer @tomhennigan

**Review by gnecula — APPROVED** [review]
LGTM, but this is something worth adding to CHANGELOG

Thanks!

**Comment by hawkinsp** [comment]
Any updates?

**Comment by skye** [comment]
No, I haven't had time to follow up on this for a while. There are a million internal failures because this wakes up pytype to a bunch of existing type errors around DeviceArrays. I'll eventually get back to this, but wouldn't mind if someone else wanted to take over.

**Comment by skye** [comment]
Peter took over! https://github.com/google/jax/pull/2978

**Pull request closed without merging**
