### PR TITLE
Differentiable scan!

### PR DESCRIPTION
**Pull request by mattjj**
All work pair w/ @dougalm.

### CODE REVIEW

**Review by dougalm — APPROVED** [review]

**Comment by fehiepsi** [comment]
This works like a charm!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! <3 <3 <3

**Comment by mattjj** [comment]
Thanks, @fehiepsi !

This first version will probably require some iteration and revision, and we're ready and willing to fix all the bugs or inefficiencies users find. After we merge this into master (imminently), open issues with any problems!

**Comment by fehiepsi** [comment]
Sure, @mattjj !

**Comment by mattjj** [comment]
We suspect execution times might be slower than unrolled versions at first, but if you have applications of `scan` that you want to run fast, open them in issues and we can work on getting them to the XLA team as benchmarks. Benchmarks are like catnip to the XLA team.

**Comment by fehiepsi** [comment]
@mattjj We have an [example at numpyro](https://github.com/pyro-ppl/numpyro/pull/117), which is really fast in CPU (but slow in GPU, which is expected because the variables' dimensions are small). I think that the reason for it fast is we just want to forward/backward the carry variable (kind of [jacfwd through while_loop](https://github.com/google/jax/issues/650)) instead of getting the scanned outputs:
```
    def scan_fn(log_prob, word):
        return forward_one_step(log_prob, word, transition_lob_prob, emission_log_prob), np.ones(())
```
there
```haskell
scan :: (log_prob -> word -> (log_prob, 1)) -> log_prob -> [word] -> (log_prob, [1])
```

We have [another example](https://github.com/pyro-ppl/numpyro/pull/119) which getting scanned outputs is necessary, but I have not adapted it to use `lax.scan` yet. I'll work on it and get back to you the performance of `lax.scan` on that model.

If the slowness in GPU is unexpected to you/XLA team, then I will port that example to a standalone repro (not depend on numpyro) for your team to benchmark. GPU is just slow in execution (100x slower than CPU). It is fast when compiling. :)

**Pull request merged**
