### PR TITLE
WIP: x64: make Jax default dtypes 32-bit

### PR DESCRIPTION
**Pull request by jakevdp**
This is step 1 in removing the x64 flag: jax should default to 32-bit types to facilitate working on accelerators.

### CODE REVIEW

**Comment by shoyer** [comment]
Very cool to see progress on this!

I made a half-hearted attempt at this back in https://github.com/google/jax/pull/2082. There might be something from that PR worth salvaging if you want to take a look over :)

**Comment by fehiepsi** [comment]
If this is landed, it would be nice to have a utility to set the default dtype (we mainly use jax in CPU, not in GPU, or TPU).

**Comment by jakevdp** [comment]
> If this is landed, it would be nice to have a utility to set the default dtype (we mainly use jax in CPU, not in GPU, or TPU).

I think that's exactly what the to-be-removed flag does...

**Comment by jakevdp** [comment]
This uncovered an existing bug in `jet`, fixed in #3807

**Comment by hawkinsp** [comment]
Closing, because I think the same development is happening in other newer PRs.

**Pull request closed without merging**
