### PR TITLE
Add `--jax_platforms` flag to replace `--jax_platform_name`.

### PR DESCRIPTION
**Pull request by skye**
The motivation for this change is to make it possible to avoid
initializing unused backends, which may have undesirable side effects
(e.g. GPU memory allocation, only one process can use a Cloud TPU at a
time). It also provides a new and more flexible mechanism for
configuring the default backend, in order to minimize the number of
configs we have.

### CODE REVIEW

**Comment by skye** [comment]
This is rebased on https://github.com/google/jax/pull/8034, I suggest looking at the second commit only or waiting for that to go in.

**Review by hawkinsp — APPROVED** [review]

**Comment by skye** [comment]
This is now rebased directly on main.

**Comment by jakevdp** [comment]
Should this also deprecate `jax_xla_backend`, which advertises itself as an alias for `jax_platform_name`?

**Comment by skye** [comment]
Oh good catch. I'll change the description of `jax_xla_backend`, either in the PR or a follow-up.

**Comment by skye** [comment]
Didn't refresh in time to see the merge, I guess a follow-up :)

**Pull request merged**
