### PR TITLE
[ROCm]: Disable some tests on ROCm platform

### PR DESCRIPTION
**Pull request by rahulbatra85**
Disable some failing tests on ROCm for now

1. tests/experimental_rnn_test.py::test_lstm
2. tests/linalg_test.py::testEighIdentity
3. tests/linalg_test.py::testTridiagonal
4. tests/linalg_test.py::testToeplitzSymmetricConstruction
5. tests/linalg_test.py::testDirichlet
6. tests/linalg_test.py::testDirichletSmallAlpha

### CODE REVIEW

**Review by jakevdp — CHANGES_REQUESTED** [review]
Looks good aside from the lint error (trailing whitespace).

**Comment by rahulbatra85** [comment]
> Looks good aside from the lint error (trailing whitespace).

Fixed.

**Comment by rahulbatra85** [comment]
@jakevdp  If it looks good, then please merge whenever you get a chance. Thanks!

**Review by jakevdp — APPROVED** [review]
Thanks!

**Pull request merged**
