### PR TITLE
Adding implementations for numpy alen, isscalar

### PR DESCRIPTION
**Pull request by fedden**
Hey folks,

I wanted to start getting familiar with this codebase and start contributing more regularly, as I think it's a fantastic project! 

Because of the above I have made a very simple PR to implement numpy alen, isscalar to understand the testing code that is used for jax a little better, aswell as to better understand both the repositories overall structure and the process used to contribute. [I found this op whilst looking at ops from this issue.](https://github.com/google/jax/issues/70#issuecomment-569535681)

### CODE REVIEW

**Comment by fedden** [comment]
@shoyer @hawkinsp If you would kindly review the PR whenever is convenient (or let me know who else to bother) I'd appreciate it. 

If these methods aren't helpful, I'd be very appreciative of any methods/issues you would like to be worked on - implementing these very basic methods has been a good way to start exploring and hacking on this repository so I'd be happy to dig a bit deeper

**Comment by shoyer** [comment]
Both `alen` (https://github.com/numpy/numpy/pull/14181) and  `asscalar` (https://docs.scipy.org/doc/numpy/reference/generated/numpy.asscalar.html) are marked as deprecated in the latest NumPy release. So I would lean against including them in JAX, unless someone has a strong need.

**Comment by fedden** [comment]
Okay fair enough, I noticed that too but they were simple enough to do quickly so no problem if we don't move forward with them. It might be worth removing them from [this list ](https://github.com/google/jax/issues/70#issue-389861159) if we don't want to merge these in 🙂

**Comment by shoyer** [comment]
@fedden thanks for trying to help here and thanks for the feedback. I've updated the list in https://github.com/google/jax/issues/70

**Pull request closed without merging**
