### PR TITLE
Notebook showing how to write gufuncs with vmap

### PR DESCRIPTION
**Pull request by shoyer**
There are a few bits that don't quite work yet, but this is a nice example of what you *should* be able to do with JAX.

### CODE REVIEW

**Comment by alexbw** [comment]
Thanks! A few comments.
For installation, please now use:
```
!pip install https://storage.googleapis.com/jax-wheels/cuda92/jaxlib-0.1-py3-none-any.whl
!pip install jax
```

Please remove mention of 'Google owned' near the top of the notebook.

What bits don't work? The whole notebook seems to run and looks good to me.

**Comment by shoyer** [comment]
> What bits don't work? The whole notebook seems to run and looks good to me.

Notice the commented out asserts under "Test cases" -- there seem to be a few edge cases for higher dimensional input with `dot`.

**Comment by mattjj** [comment]
Thanks so much for this! We were talking about this earlier today, and how great it would be to include.

We haven't written a dot_general batching rule yet. I should add that!

**Comment by mattjj** [comment]
Thanks so much for this! We were talking about this earlier today, and how great it would be to include.

We haven't written a dot_general batching rule yet. This is a great motivation to do it!

**Comment by shoyer** [comment]
@mattjj there's also the AssertionError I get with `assert vecvec(np.zeros((2, 3)), np.zeros((3,))).shape == (2,)`, which turns up an a line documented as "unreachable" :)

**Pull request merged**
