### PR TITLE
Fix a typo on the dynamic definition of __hash__.

### PR DESCRIPTION
**Pull request by jblespiau**

### CODE REVIEW

**Review by hawkinsp — COMMENTED** [review]
Seems fine, but are we missing a test?

**Comment by jblespiau** [comment]
> Seems fine, but are we missing a test?

Indeed, done.

**Review by hawkinsp — APPROVED** [review]

**Comment by hawkinsp** [comment]
There is a test failure.

**Comment by jblespiau** [comment]
Thanks, I fixed it (it was because jaxlib is not released yet, so `Buffer` does not behave like a DeviceArray just yet.

**Pull request merged**
