### PR TITLE
Canonicalize result dtype to fix double precision problem in ldexp

### PR DESCRIPTION
**Pull request by dav0dea**
Fixes issue #4053

### CODE REVIEW

**Comment by PhilippThoelke** [comment]
@googlebot I signed it!

**Comment by jakevdp** [comment]
Looks great! Can you add a regression test for this? (i.e. a test that fails currently, but passes with your fix). An example is here: https://github.com/google/jax/blob/394a33c82880953c46629aa6250245e1dc845640/tests/lax_numpy_test.py#L3728-L3740

**Comment by PhilippThoelke** [comment]
The current test for the `ldexp` function is simply skipped when 64 bit mode is not enabled:
https://github.com/google/jax/blob/394a33c82880953c46629aa6250245e1dc845640/tests/lax_numpy_test.py#L1868-L1870
Should I still add a completely new regression test for this issue or should I modify the existing test? The new test would basically be a copy of the existing one without the if statement.

**Comment by jakevdp** [comment]
I wonder if adding an `op_record` for `ldexp` would be sufficient now? https://github.com/google/jax/blob/394a33c82880953c46629aa6250245e1dc845640/tests/lax_numpy_test.py#L101

**Comment by PhilippThoelke** [comment]
Adding this line will generate tests that fail without the fix and work with it:
```python
op_record("ldexp", 2, int_dtypes, all_shapes, jtu.rand_default, [], check_dtypes=False)
```

**Comment by jakevdp** [comment]
That's perfect! I think we can delete the existing `testLdexp` function now, as it essentially does the same thing as this automatic tests (although it does cover some other corner cases, such as infs and nans)

**Comment by PhilippThoelke** [comment]
The automatic tests also don't cover cases where `x1` is a float, which are quite important I would say. I don't think it is possible to cover this with an `op_record` because `x2` must be an integer.

**Review by jakevdp — APPROVED** [review]
Looks great, thanks for digging-in on this!

**Pull request merged**
