### PR TITLE
Correct jax.numpy.pad signature

### PR DESCRIPTION
**Pull request by j-towns**
See https://docs.scipy.org/doc/numpy/reference/generated/numpy.pad.html.

### CODE REVIEW

**Comment by mattjj** [comment]
Thanks @j-towns!

**Comment by j-towns** [comment]
There's a test failing on travis. `ix_` doesn't appear to depend on pad, so I *think* it's unrelated.
```
_________ LaxBackedNumpyTests.testIx_Ix__int32[3]_float32[0]_int32[4] __________
[gw0] linux -- Python 3.6.9 /home/travis/miniconda/bin/python

self = <lax_numpy_test.LaxBackedNumpyTests testMethod=testIx_Ix__int32[3]_float32[0]_int32[4]>
rng = functools.partial(<function _rand_dtype at 0x7fa0179beea0>, <built-in method randn of numpy.random.mtrand.RandomState object at 0x7fa016cf5eb8>, scale=3)
shapes = ((3,), (0,), (4,))
dtypes = (<class 'numpy.int32'>, <class 'numpy.float32'>, <class 'numpy.int32'>)

    @parameterized.named_parameters(jtu.cases_from_list(
          {"testcase_name": jtu.format_test_name_suffix("ix_", shapes, dtypes),
           "rng": jtu.rand_default(), "shapes": shapes, "dtypes": dtypes}
          for shapes, dtypes in (
            ((), ()),
            (((7,),), (onp.float32,)),
            (((3,), (4,)), (onp.float32, onp.int32)),
            (((3,), (0,), (4,)), (onp.int32, onp.float32, onp.int32)),
          )))
    def testIx_(self, rng, shapes, dtypes):
      args_maker = lambda: [rng(shape, dtype)
                            for shape, dtype in zip(shapes, dtypes)]
      self._CheckAgainstNumpy(onp.ix_, lnp.ix_, args_maker,
>                             check_dtypes=True)

tests/lax_numpy_test.py:1506: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
jax/test_util.py:558: in _CheckAgainstNumpy
    atol=tol, rtol=tol)
jax/test_util.py:511: in assertAllClose
    self.assertAllClose(x_elt, y_elt, check_dtypes, atol=atol, rtol=rtol)
jax/test_util.py:516: in assertAllClose
    self.assertArraysAllClose(x, y, check_dtypes, atol=atol, rtol=rtol)
jax/test_util.py:485: in assertArraysAllClose
    self.assertDtypesMatch(x, y)
jax/test_util.py:498: in assertDtypesMatch
    self.assertEqual(x_dtype, y_dtype)
E   AssertionError: dtype('int64') != dtype('float32')
============ 1 failed, 12099 passed, 154 skipped in 1365.20 seconds ============
The command "pytest -n 1 tests examples -W ignore" exited with 1.

```

**Comment by j-towns** [comment]
It's possible the failure was triggered by a recent Numpy update: https://anaconda.org/conda-forge/numpy.

**Comment by mattjj** [comment]
Nice find! We're looking at it, will update here when we can.

**Pull request merged**
