### PR TITLE
Fixed _mapped_axis_size raising an uncaught TypeError

### PR DESCRIPTION
**Pull request by treyra**

### CODE REVIEW

**Comment by treyra** [comment]
Proposed fix to #16594

**Comment by treyra** [comment]
Not sure how to fix <no****ly​@google.com> being an author blocked by the cla check. (I think that is noreply@google.com). I can close this and try again from a fresh pull request.

**Comment by jakevdp** [comment]
Thanks for the fix! Something seems strange in the file diffs – there are changes unrelated to the issue you mention. Can you please try to fix that so we can review the change you have in mind? Thanks!

**Comment by treyra** [comment]
You're right, things looked weird. I made a clean pull request at #16645, since I think I made some mistakes in git when squashing the various commits to make this one.

**Pull request closed without merging**
