### PR TITLE
[Draft] Try reformatting with yapf

### PR DESCRIPTION
**Pull request by joaogui1**
For discussion in #1445.

### CODE REVIEW

**Comment by hawkinsp** [comment]
I suspect the most controversial part of this change would be the additional blank lines before each top-level definition. Some of the JAX authors find the PEP8 style very wasteful of vertical space, and have a strong preference for only one line before each top-level definition. I think yapf lets you configure this with `BLANK_LINES_AROUND_TOP_LEVEL_DEFINITION`?

**Comment by joaogui1** [comment]
Yes, it can be changed, gonna push a version where it's set to 0

**Comment by hawkinsp** [comment]
I suspect `1` is the right value, not `0` (closest to the current informal style.)

**Comment by joaogui1** [comment]
Good point, gonna fix it in a few minutes

**Comment by joaogui1** [comment]
So, what do you think @hawkinsp ?

**Comment by hawkinsp** [comment]
Well, it's less bad than I feared. Most of the changes I don't personally find that troubling; I suspect the 100-character lines helped there because if there are fewer line breaks there can be fewer poor line breaking decisions.

The worst examples of formatting I saw were in the parameterized test cases, where the expressions that build the test case parameters became much less readable. I wonder if we can fix that.

In principle I very much like the idea of automatic formatting (and I would never write C++ without clang-format these days), I'm still quite skeptical of the output of the Python formatters.

We should get other contributors to JAX to weigh in.

**Comment by joaogui1** [comment]
Huum, I will take a look at theparameterized tests later (I also need to work on the documentation PR). 
It would be great if more contributors weighted in indeed, and in fact there's an issue about about standardizing code style ( #1445 ) where @shoyer proposes using black instead of yapf, and we discuss a little the merits of each autoformatter.

**Comment by joaogui1** [comment]
Hey @hawkinsp I made a few changes that I believe help with the readability of the parameterized tests. 

> We should get other contributors to JAX to weigh in.

@mattjj @shoyer @skye @jekbradbury @levskaya @gnecula @j-towns @froystig what do you guys think?
(I think I messed up a little bit when I tried to fix a merge conflict, if it's too problematic tell me and I'll try to fix it ASAP)

**Comment by joaogui1** [comment]
Ok, it seems I messed up considerably, I'm going to open a new PR without the hundreds of commits

**Pull request closed without merging**
