### PR TITLE
jit lax_numpy.roll

### PR DESCRIPTION
**Pull request by shoyer**
This was making tracing slow for code with lots of rolls.

### CODE REVIEW

**Review by jekbradbury — APPROVED** [review]
Is it maybe time to try to figure out how to get `jit` to work well with the non-underscored versions of NumPy functions (with default args etc.)? Or are we pretty sure that's impossible?

**Comment by hawkinsp** [comment]
I'm still pretty confident that allowing the user to specify both static argument names *and* numbers would work. (We had an open issue where we are discussing this somewhere, but I can't find it right now.)

**Comment by shoyer** [comment]
> I'm still pretty confident that allowing the user to specify both static argument names _and_ numbers would work

Yeah, I think that could be done.

**Comment by shoyer** [comment]
See https://github.com/google/jax/issues/1936 for discussion on keyword arguments

**Pull request merged**
