### PR TITLE
Fix stale notebook.

### PR DESCRIPTION
**Pull request by gnecula**
The notebook fails with type errors, due to changes in XLA.
Use numpy.dtype for the xla_client.Shape.array_shape calls.

### CODE REVIEW

**Comment by mattjj** [comment]
Thanks, George!

**Comment by murphyk** [comment]
It seems the notebooks no longer render on github
eg
https://github.com/google/jax/blob/master/notebooks/neural_network_and_data_loading.ipynb

**Comment by mattjj** [comment]
Ah good catch! That's not an issue from this PR, but likely from one of us editing the notebooks as text at some point. I'll see if I can fix that...

**Comment by mattjj** [comment]
I opened and re-saved all our notebooks both locally using `jupyter notebook` and in my browser using cloud. Neither seems to make them renderable on GitHub. Maybe it's just a GitHub issue we can wait out...

**Pull request merged**
