### PR TITLE
Implement prototype for static keyword argument support while jitting

### LINKED ISSUE #1159: kwargs sometimes cannot work well with jit
Minimal repro:

```
from functools import partial
from jax import jit

@partial(jit, static_argnums=(3,))
def f(a, b, c, d):
  if d > 0:
    return a + b - c
  else:
    return d
```

`f(a=1, b=2, c=3, d=4)` would complain about `TypeError: Jitted function has static_argnums=(3,) but was called with only 0 positional arguments.`

but `f(1, 2, 3, 4)` works.

### PR DESCRIPTION
**Pull request by ziyadedher**
Quick (pretty unoptimized) prototype for static keyword argument support for jitted functions.

Works by converting the inputted arguments to have no keyword arguments and treating everything else the same. Most of the work is done by reading the signature of the to-be-jitted function `fun` using the [`inspect`](https://docs.python.org/3/library/inspect.html) module and manipulating the `*args` and `**kwargs` such that everything is aligned.

There is one caveat that might make the implementation seem a bit off: the standard way would not support keyword-only arguments without diving deeper into the compilation of the function since the technique works by converting all arguments to positional arguments; instead, I create a surrogate function that emulates `fun` while having no keyword arguments.

So all-in-all here is what happens, for example, when trying to jit a function `f(x, y, *, z)` with `static_argnums=(1, 2)`:
- Function `_f(x, y, z) = _f(x, y, z=z)` is constructed.
- When calling the functions with some `args` and `kwargs` we project the arguments onto the parameters of the original `f` and extract a positional `args` representation of the union of `args` and `kwargs`.
- We jit `_f` instead of `f` with only positional arguments.

Still a few things that need to happen before this CL is ready to go:
- [ ] Profile the overhead of using all this extra stuff while jitting (i.e. `inspect`).
- [ ] Possibly explore other approaches such as modifying `linear_utils` to support keyword arguments.
- [ ] Write tests.
- [ ] Raise errors where the function signature is not sufficient to map keyword arguments to positional arguments.

Here is an example of its usage that would error previously:
```python
@functools.partial(jit, static_argnums=(1, 3, 5))
def f1(a1, a2, a3=100., a4=200., *, kw1=300., kw2=400.):
  return 10000.

print(f1(1., 2.))
print(f1(a1=1., a2=2.))
print(f1(1., 2., 3.))
print(f1(1., 2., 3., 4.))
print(f1(1., 2., a3=3., a4=4.))
print(f1(1., 2., a4=4.))
print(f1(1., 2., kw1=5.))
print(f1(1., 2., kw2=6.))
print(f1(1., 2., kw1=5., kw2=6.))
```

Possibly closes #1159 
Related to #1936 

Would love to hear what people think of this issue.

### CODE REVIEW

**Comment by ziyadedher** [comment]
Well, this breaks everything as it is right now. Going to investigate tomorrow.

**Comment by mattjj** [comment]
Thanks for investigating! This is tricky stuff (I remember from [playing with this in Autograd](https://github.com/HIPS/autograd/blob/c6f630a5ec18bd30f1485bc0dbbccb8664c77510/autograd/differential_operators.py#L149-L190), though that had to be Python 2-compatible), and it's worth exploring.

Maybe the goal could be something like: either find a sound-but-not-complete approach to map keyword arguments to positional parameters, or else identify once and for all the reason we can't. WDYT?

Also, what do you think about just using `inspect.signature(f).bind(*args, **kwargs).args`? That seems to handle some simple cases:

```python
In [2]: inspect.signature(lambda x, y: x + y).bind(y=2, x=3).args
Out[2]: (3, 2)

In [3]: inspect.signature(lambda x, y: x + y).bind(2, y=3).args
Out[3]: (2, 3)
```

We could throw in some `apply_defaults` if we want:

```python
In [5]: ba = inspect.signature(lambda x, y=3: x + y).bind(2)

In [6]: ba.apply_defaults()

In [7]: ba.args
Out[7]: (2, 3)
```

IIUC that would already let us handle more cases than we do now, since it effectively turns more args into positional ones.

I'd like to red-team this to make sure we can never be misled by reasonable metadata values though, and produce silently wrong results... Is there any way to make a wrapper that would, instead of just obscuring the signature (causing us to error when keyword arguments are passed), actually make us bind incorrect values? Or is that only possible with malicious setting of `__wrapped__` or something like that?

**Comment by mattjj** [comment]
Ah, I misread the code, maybe using `sig.bind` is exactly your strategy; I didn't understand the need for the rest of the code (ie why define `_fun`), but maybe it's to handle keyword-only args (which are new to me, coming from py2).

**Comment by mattjj** [comment]
By the way, linear_util.py already supports keyword arguments everywhere AFAIK.

+1 to profiling this. Perhaps we only need to call into this when keyword arguments are actually used.

Also +1 to raising errors: we don't need to have a complete solution, and just handling more cases than we currently do would be an improvement!

Here's one way we might write this in a linear_util.py style:

```python
from inspect import signature
from functools import partial

from jax import jit
import jax.linear_util as lu

def make_args_positional(f):
  return _make_args_positional(lu.wrap_init(f), signature(f)).call_wrapped

@lu.transformation
def _make_args_positional(sig, *args, **kwargs):
  ba = sig.bind(*args, **kwargs)
  ba.apply_defaults()
  ans = yield ba.args, ba.kwargs
  yield ans

@make_args_positional
@partial(jit, static_argnums=(1,))
def f(x, y):
  return x + y

f(2, y=3)  # fails if @make_args_positional is removed
```

**Comment by ziyadedher** [comment]
@mattjj Thanks for taking a look at this! Yes, the reason I had to make a new function was to get around the keyword-only argument issue; however, doing that breaks the caching system since we are now constructing a new function object at every `jit` call and using that as our `jitted` function. To get around this, I used a very hacky wrapper class that emulates (to the greatest extent possible in vanilla Python) the inputted function while still converting the arguments correctly:

```python
  class Fun:
    def __init__(self, fun):
      self.fun = fun

    def __call__(self, *args):
      fun_params = list(fun_sig.parameters.values())
      new_args = []
      new_kwargs = {}
      for arg, param in zip(args, fun_params):
        if param.kind is inspect.Parameter.KEYWORD_ONLY:
          new_kwargs[param.name] = arg
        else:
          new_args.append(arg)
      return self.fun(*new_args, **new_kwargs)

    def __hash__(self):
      return hash(self.fun)

    def __eq__(self, other):
      return self.fun == other

    def __getattr__(self, name):
      if name == "fun":
        return super().__getattribute__("fun")
      else:
        return self.fun.__getattribute__(name)

    def __getattribute__(self, name):
      if name == "__init__":
        return functools.partial(Fun.__init__, self)
      elif name == "__call__":
        return functools.partial(Fun.__call__, self)
      elif name == "__hash__":
        return functools.partial(Fun.__hash__, self)
      elif name == "__eq__":
        return functools.partial(Fun.__eq__, self)
      else:
        return Fun.__getattr__(self, name)
  _fun = Fun(fun)
```
However, this then raised a new issue where since we are using a `WeakKeyRef` dictionary and the instance of this class is created within the `jit` function, all strong references are lost and the function is dropped from cache anyway.

---

I will be playing around with the code example you gave today and see where it takes me.

**Pull request closed without merging**
