### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by rickwierenga**

### CODE REVIEW

**Comment by gnecula** [comment]
Hi, 

Thank you for noticing this problem. As you can see there are [failing tests](https://travis-ci.org/google/jax/jobs/654044502?utm_medium=notification&utm_source=github_status). I think that your fix is correct, but these failing tests are wrong. The `dtype` field of the ShapedDtypeStruct should be a `numpy.dtype`. Confusingly, `jax.numpy.float32` is not the same as `numpy.float32`. 

The two tests that use `np.float32` (`test_shape_dtype_struct` and `test_shape_dtype_struct_scalar`) should be changed to use `onp.float32` and along with your fix, this should make everything work.

**Comment by gnecula** [comment]
@tomhennigan FYI

**Comment by gnecula** [comment]
This is a duplicate of #2253. Perhaps let's wait for that one to be resolved.

**Comment by rickwierenga** [comment]
Thanks, I should have checked. I will close this for now.

**Pull request closed without merging**
