### PR TITLE
Fix #3883 by special casing scalar dynamic_slice and dynamic_update_slice

### LINKED ISSUE #3883: vmap of dynamic_slice of a scalar fails
Specifically, doing
```python
In [1]: import jax.numpy as np

In [2]: from jax import lax

In [3]: import jax

In [4]: jax.vmap(lambda x: lax.dynamic_slice(x, [], []))(np.array([1, 2, 3, 4]))
```
gives the following error
```text
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-ae0083eeb242> in <module>
----> 1 jax.vmap(lambda x: lax.dynamic_slice(x, [], []))(np.array([1, 2, 3, 4]))

~/dev/jax/jax/api.py in batched_fun(*args)
    878     _ = _mapped_axis_size(in_tree, args_flat, in_axes_flat, "vmap")
    879     out_flat = batching.batch(flat_fun, args_flat, in_axes_flat,
--> 880                               lambda: flatten_axes("vmap out_axes", out_tree(),
    881                                                    out_axes))
    882     return tree_unflatten(out_tree(), out_flat)

~/dev/jax/jax/interpreters/batching.py in batch(fun, in_vals, in_dims, out_dim_dests)
     32   # executes a batched version of `fun` following out_dim_dests
     33   batched_fun = batch_fun(fun, in_dims, out_dim_dests)
---> 34   return batched_fun.call_wrapped(*in_vals)
     35
     36 @lu.transformation_with_aux

~/dev/jax/jax/linear_util.py in call_wrapped(self, *args, **kwargs)
    148     gen = None
    149
--> 150     ans = self.f(*args, **dict(self.params, **kwargs))
    151     del args
    152     while stack:

<ipython-input-4-ae0083eeb242> in <lambda>(x)
----> 1 jax.vmap(lambda x: lax.dynamic_slice(x, [], []))(np.array([1, 2, 3, 4]))

~/dev/jax/jax/lax/lax.py in dynamic_slice(operand, start_indices, slice_sizes)
    734   start_indices = _dynamic_slice_indices(operand, start_indices)
    735   return dynamic_slice_p.bind(operand, *start_indices,
--> 736                               slice_sizes=tuple(slice_sizes))
    737
    738 def dynamic_update_slice(operand: Array, update: Array,

~/dev/jax/jax/core.py in bind(self, *args, **kwargs)
    276
    277     tracers = map(top_trace.full_raise, args)
--> 278     out_tracer = top_trace.process_primitive(self, tracers, kwargs)
    279     if self.multiple_results:
    280       return map(full_lower, out_tracer)

~/dev/jax/jax/interpreters/batching.py in process_primitive(self, primitive, tracers, params)
    132       # TODO(mattjj,phawkins): if no rule implemented, could vmap-via-map here
    133       batched_primitive = get_primitive_batcher(primitive)
--> 134       val_out, dim_out = batched_primitive(vals_in, dims_in, **params)
    135       if primitive.multiple_results:
    136         return map(partial(BatchTracer, self), val_out, dim_out)

~/dev/jax/jax/lax/lax.py in _dynamic_slice_batching_rule(batched_args, batch_dims, slice_sizes)
   3696   dnums = GatherDimensionNumbers(offset_dims=dims, collapsed_slice_dims=(),
   3697                                  start_index_map=dims)
-> 3698   index, index_bdim = _batch_dynamic_slice_indices(start_indices, start_idx_bds)
   3699   return _gather_batching_rule(
   3700     [operand, index], [operand_bd, index_bdim], dimension_numbers=dnums,

~/dev/jax/jax/lax/lax.py in _batch_dynamic_slice_indices(indices, bdims)
   3676   size = next((x.shape[i] for x, i in zip(indices, bdims) if i is not None), -1)
   3677   if size < 0:
-> 3678     return concatenate([broadcast(i, (1,)) for i in indices], 0), None
   3679   indices = concatenate(
   3680     [broadcast_in_dim(x, (size, 1),

~/dev/jax/jax/lax/lax.py in concatenate(operands, dimension)
    446     An array containing the concatenation.
    447   """
--> 448   return concatenate_p.bind(*operands, dimension=dimension)
    449
    450 Precision = xla_client.PrecisionConfig.Precision

~/dev/jax/jax/core.py in bind(self, *args, **kwargs)
    273     top_trace = find_top_trace(args)
    274     if top_trace is None:
--> 275       return self.impl(*args, **kwargs)
    276
    277     tracers = map(top_trace.full_raise, args)

~/dev/jax/jax/interpreters/xla.py in apply_primitive(prim, *args, **params)
    222 def apply_primitive(prim, *args, **params):
    223   """Impl rule that compiles and runs a single primitive 'prim' using XLA."""
--> 224   compiled_fun = xla_primitive_callable(prim, *unsafe_map(arg_spec, args), **params)
    225   return compiled_fun(*args)
    226

~/dev/jax/jax/interpreters/xla.py in xla_primitive_callable(prim, *arg_specs, **params)
    238     return _xla_callable(lu.wrap_init(prim_fun), device, None, "prim", donated_invars,
    239                          *arg_specs)
--> 240   aval_out = prim.abstract_eval(*avals, **params)
    241   if not prim.multiple_results:
    242     handle_result = aval_to_result_handler(device, aval_out)

~/dev/jax/jax/lax/lax.py in standard_abstract_eval(prim, shape_rule, dtype_rule, *args, **kwargs)
   1845   assert all(isinstance(arg, UnshapedArray) for arg in args), args
   1846   least_specialized = _max(
-> 1847       map(type, args), key=operator.attrgetter('array_abstraction_level'))
   1848   if least_specialized is ConcreteArray:
   1849     return ConcreteArray(prim.impl(*[x.val for x in args], **kwargs))

ValueError: max() arg is an empty sequence
```
I'm just writing a test for this now and will have a go at fixing it.

### PR DESCRIPTION
**Pull request by j-towns**

### CODE REVIEW

**Comment by j-towns** [comment]
I _think_ the failing test (in [`tests/generated_fun_test.py`](https://github.com/google/jax/blob/master/tests/generated_fun_test.py)) is unrelated to this pr, since that file doesn't appear to touch `dynamic_slice` or `dynamic_update_slice`.

**Comment by j-towns** [comment]
https://github.com/google/jax/pull/3885 should fix the flaky test.

**Comment by mattjj** [comment]
Good idea!

Though it seems a little weird to always act as an identity on scalars, and not ever raise an error regardless of what `start_indices` and `slice_sizes` look like. My understanding of the analogous NumPy case is that it'd still raise an error if too many indices are given for the rank of the operand, as in errors `np.zeros(())[2:2]`.

How about we check that the lengths of `start_indices` and `slice_sizes` are both zero, return operand if they are, and error otherwise?

**Comment by j-towns** [comment]
>How about we check that the lengths of start_indices and slice_sizes are both zero, return operand if they are, and error otherwise?

I think `_dynamic_slice_indices` (called just above the lines inserted by this PR) already does that check.
https://github.com/google/jax/blob/7506a3e5f0137f48415def878bea71c5977dfbd0/jax/lax/lax.py#L5732-L5735

**Comment by j-towns** [comment]
Well, it checks the length of start_indices, although doesn't check the length of slice_sizes. I could add that?

**Comment by j-towns** [comment]
I'm actually not sure about this strategy in general. It might be reasonable for a user to expect that calling `lax.dynamic_slice` would result in the primitive being called, even in trivial cases. I might try a bit harder to fix the batching rule that is actually causing this issue rather than trying to avoid it.

**Pull request closed without merging**
