### PR TITLE
Fixes minor typo in the document "How JAX primitives work"

### PR DESCRIPTION
**Pull request by joaogui1**

### CODE REVIEW

**Comment by gnecula** [comment]
Hi, If I look at the diff, I get a huge one, I cannot tell really what the changes are. Was really the small fix that you suggest in the description? Are the large diffs due to re-running the notebook and then saving it?

**Comment by joaogui1** [comment]
@gnecula yeah, the huge diff is due to changing a notebook. In the original [How JAX primitives work
](https://jax.readthedocs.io/en/latest/notebooks/How_JAX_primitives_work.html) we have 

> Below is another use of jit where we differentiate only with respect...
It's after the 12th cell.
I changed differentiate to compile, as it is talking about JIT

**Comment by joaogui1** [comment]
Should I also rebuild the docs, as I changed the notebooks? Or is that part of the CI?

**Comment by gnecula** [comment]
If that is the only thing you have changed, do you mind changing the commit to just edit that word in the .ipynb file, without rebuilding the notebook. The [rebuilding](https://jax.readthedocs.io/en/latest/notebooks/How_JAX_primitives_work.html) is automatic. 

Thanks

**Comment by joaogui1** [comment]
Done

**Review by gnecula — APPROVED** [review]

**Pull request merged**
