### PR TITLE
Add np.intc to the set of valid jaxtypes.

### PR DESCRIPTION
**Pull request by hawkinsp**
Fixes a number of test failures on Windows.

### CODE REVIEW

**Comment by hawkinsp** [comment]
@cloudhan

**Comment by jakevdp** [comment]
Is there any reasonable regression test we can add for this that will run on our CI?

**Comment by hawkinsp** [comment]
> Is there any reasonable regression test we can add for this that will run on our CI?

I don't think so. We'd need a windows CI build (which we should add, but not yet...)

**Comment by hawkinsp** [comment]
> > Is there any reasonable regression test we can add for this that will run on our CI?
> 
> I don't think so. We'd need a windows CI build (which we should add, but not yet...)

To add some detail to this, `np.int32 is np.intc` is true on Mac and Linux but false on Windows. So there's no way to distinguish `np.int32` and `np.intc` on our current CI platforms as far as I can tell.

**Pull request merged**
