### PR TITLE
Fix common typo: Tuple[X] -> Tuple[X, ...]

### PR DESCRIPTION
**Pull request by NeilGirdhar**

### CODE REVIEW

**Comment by NeilGirdhar** [comment]
@sharadmv This touches code that you recently committed, but I don't understand it well enough to be sure you didn't actually mean `Tuple[int]`.  Would you mind quickly taking a look?

**Comment by sharadmv** [comment]
Yea your changes to those files LGTM, that was a mistake on my part.

**Comment by NeilGirdhar** [comment]
@sharadmv No worries, thanks for the quick replay!  I really don't understand the Jax internals at all.

**Review by jakevdp — APPROVED** [review]
Looks good, thanks!

**Comment by NeilGirdhar** [comment]
@jakevdp YVW, let me know if I'm bugging you too much with insignificant commits...

**Comment by jakevdp** [comment]
Keep 'em coming, it's really helpful!

**Comment by jakevdp** [comment]
(I personally always forget the ellipses in `Tuple`, so I need all the help I can get)

**Pull request merged**
