### PR TITLE
Skip tests that are failing without omnistaging (which will not be an…

### PR DESCRIPTION
**Pull request by chr1sj0nes**
… option shortly).

Enable tests on all platforms that were unnecessarily skipped.

### CODE REVIEW

**Review by mattjj — APPROVED** [review]
Thanks!

**Comment by chr1sj0nes** [comment]
Thanks Matt. Is there anything blocking this from being merged?

**Comment by mattjj** [comment]
No, sorry!

**Comment by mattjj** [comment]
I'm not sure, but I think you can start merges too, by applying the 'pull ready' label and then sending the resulting CL to jax-merges@. If not, ping me on chat and we'll sort out the permissions so that you can.

**Pull request merged**
