### PR TITLE
DOC: add references for haskell-style signatures

### LINKED ISSUE #8355: non-Python type signatures in docs are confusing for a Python package
The docs include confusing type signatures, using what I assume is Haskell syntax (please correct me if I'm wrong---I never learned Haskell). Two examples I found are:
https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.scan.html#jax.lax.scan
https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.fori_loop.html#jax.lax.fori_loop

PS: sorry, I didn't see an option to report an issue with the docs, so just used the "bugs" issue template.

### PR DESCRIPTION
**Pull request by jakevdp**
Fixes #8355

See the rendered version e.g. here: https://jax--10700.org.readthedocs.build/en/10700/_autosummary/jax.lax.scan.html

### CODE REVIEW

**Comment by ngam** [comment]
This is beautifully done!!! 😻

**Comment by ngam** [comment]
(but why is it not applied everywhere...?)

**Comment by jakevdp** [comment]
I thought I was applying it everywhere... if you notice any places I've missed, please point them out to me.

**Comment by ngam** [comment]
Oh, sorry I was only noticing the highlighting which I thought was a pretty good way of doing this stuff. 

Comparing 

https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.scan.html#jax.lax.scan 

against

https://jax--10700.org.readthedocs.build/en/10700/_autosummary/jax.lax.scan.html?highlight=scan#jax.lax.scan

and I liked how `scan` was yellow-highlighted throughout the whole page:

Screen Shot 2022-05-13 at 17 48 19

**Comment by ngam** [comment]
Now looking more closely, I am not certain how this was produced in this PR!

**Comment by jakevdp** [comment]
Your URL has `?highlight=scan#jax.lax.scan`

**Comment by jakevdp** [comment]
Sorry about that - removed it from my pasted link.

**Comment by jakevdp** [comment]
If you use the search box on the doc page, it will highlight the term you searched for in the result. I found the correct page to link to by searching for `"scan"`, and then I didn't remove this metadata from the URL

**Comment by ngam** [comment]
Ah, wow, I am so old school, I didn't even think that was possible! Thanks for taking the time to explain that :)

**Review by mattjj — APPROVED** [review]
Great idea!

I wonder if we should add Python type signatures (which weren't so popular when these docstrings were first written). The syntax may be a bit uglier and that may obscure the meaning... but at least it'd be familiar. We can ponder on that later!

In the meantime this is a great idea for an improvement.

**Pull request merged**
