### PR TITLE
fix debug_nans for multiple-result primitives

### LINKED ISSUE #1401: jax.numpy.linalg.eig - 'jax_debug_nans' related bug
Reproducing the error with a simple matrix: (same issue with `np.linalg.eigh`)
```
A = np.array([[1.,2.],[2.,3.]])
D, V = np.linalg.eig(A)
```
Output
```
TypeError                                 Traceback (most recent call last)
<ipython-input-171-c4c8dbbffe17> in <module>
      1 A = np.array([[1.,2.],[2.,3.]])
----> 2 V,D = np.linalg.eig(A)

~/RESEARCH/jax/jax/numpy/linalg.py in eig(a)
     95 def eig(a):
     96   a = _promote_arg_dtypes(np.asarray(a))
---> 97   w, vl, vr = lax_linalg.eig(a)
     98   return w, vr
     99 

~/RESEARCH/jax/jax/lax_linalg.py in eig(x)
     47 
     48 def eig(x):
---> 49   w, vl, vr = eig_p.bind(x)
     50   return w, vl, vr
     51 

~/RESEARCH/jax/jax/core.py in bind(self, *args, **kwargs)
    128     top_trace = find_top_trace(args)
    129     if top_trace is None:
--> 130       return self.impl(*args, **kwargs)
    131 
    132     tracers = map(top_trace.full_raise, args)

~/RESEARCH/jax/jax/lax_linalg.py in eig_impl(operand)
    153 
    154 def eig_impl(operand):
--> 155   return xla.apply_primitive(eig_p, operand)
    156 
    157 def eig_translation_rule(c, operand):

~/RESEARCH/jax/jax/interpreters/xla.py in apply_primitive(prim, *args, **params)
    122   abstract_args = map(abstractify, args)
    123   compiled_fun = xla_primitive_callable(prim, *abstract_args, **params)
--> 124   return compiled_fun(*args)
    125 
    126 @cache()

~/RESEARCH/jax/jax/interpreters/xla.py in _execute_compiled_primitive(prim, compiled, backend, result_handler, *args)
    172   input_bufs = [device_put(x, device_num, backend=backend) for x in args]
    173   out_buf = compiled.Execute(input_bufs)
--> 174   if FLAGS.jax_debug_nans: check_nans(prim, out_buf)
    175   return result_handler(out_buf)
    176 

~/RESEARCH/jax/jax/interpreters/xla.py in check_nans(prim, bufs)
    177 def check_nans(prim, bufs):
    178   if prim.multiple_results:
--> 179     for buf in bufs:
    180       _check_nans(prim.name, buf.shape(), buf)
    181   else:

TypeError: 'jaxlib.xla_extension.PyLocalBuffer' object is not iterable
```

### PR DESCRIPTION
**Pull request by jekbradbury**
Fixes #1401. This case was missed in #1324.

### CODE REVIEW

**Review by skye — COMMENTED** [review]
Test case? (up to you, feel free to skip if it's a pain)

**Comment by jekbradbury** [comment]
I think the "right way" to test debug_nans would probably be to run a whitelisted subset of the JAX test suite with the flag enabled, but that sounds like a lot of work :stuck_out_tongue: and isn't really justified by the implementation (which has only three code paths). Added more direct tests for those instead.

**Review by froystig — COMMENTED** [review]
Although minor, would it be an improvement to use `setUp` and `tearDown` methods for the config read/restore that's currently duplicated in each method?

**Comment by jekbradbury** [comment]
Thanks; I didn't know about those.

**Review by skye — APPROVED** [review]

**Comment by jekbradbury** [comment]
Skye and I found that `config.update` wasn't actually updating the config when absl was enabled (e.g. during tests) so the first tests I added here weren't actually testing anything.

**Review by skye — APPROVED** [review]
Nice!

**Review by froystig — APPROVED** [review]

**Pull request merged**
