### PR TITLE
Fix shape checking rule for conv_general_dilated.

### LINKED ISSUE #4316: Bug in Jax shape checking rules
Hello,

I encountered a bug with a stacktrace pointing me to report it.

Reproduction code: 

```python
import jax
import jax.numpy as jnp
import functools
from jax.interpreters import ad

lin_primitive = jax.lax.lax.conv_general_dilated_p
backward_primitive = ad.get_primitive_transpose(lin_primitive)

cts_in = jnp.ones((1, 2, 1, 1, 1, 1, 1))

vmap_inaxes = (1, 1, None)
vmap_outaxes = (1, None)
kwargs = {'window_strides': (1, 1), 
          'padding': ((0, 0), (0, 0)),
          'lhs_dilation': (1, 1), 
          'rhs_dilation': (1, 1),
          'dimension_numbers': jax.lax.lax.ConvDimensionNumbers(lhs_spec=(0, 3, 1, 2), rhs_spec=(3, 2, 0, 1), out_spec=(0, 3, 1, 2)),
          'feature_group_count': 1,
          'batch_group_count': 1,
          'lhs_shape': (1, 2, 2, 1),
          'rhs_shape': (2, 2, 1, 1),
          'precision': None}

backward_op = functools.partial(backward_primitive, **kwargs)
vmap_backward_op = jax.vmap(backward_op, in_axes=vmap_inaxes,
                            out_axes=vmap_outaxes)
arg0 = ad.UndefinedPrimal(jnp.zeros((1, 2, 1, 1, 2, 2, 1)))
arg1 = jnp.ones((2, 2, 1, 1))

vmap_backward_op(cts_in, arg0, arg1)
```

Resulting Error:

```
RuntimeError: Invalid argument: Convolution arguments must have same number of dimensions. Got: f32[2,1,1,1,1,1] and f32[2,2,1,1]:     @     0x5616141822ee  xla::ConvGeneralDilated()
    @     0x56160ae21dac  pybind11::cpp_function::initialize<>()::{lambda()#1}::__invoke()
    @     0x5615f726ab1e  pybind11::cpp_function::dispatcher()
    @     0x5615f580fc40  _PyCFunction_FastCallDict
    @     0x5615f5cc4618  _PyEval_EvalFrameDefault
    @     0x5615f58e0a92  _PyEval_EvalCodeWithName.llvm.13210891564059904676
    @     0x5615f5cbf3a3  _PyEval_EvalFrameDefault
    @     0x5615f58e0a92  _PyEval_EvalCodeWithName.llvm.13210891564059904676
    @     0x5616213c5c65  _PyFunction_FastCallDict
    @     0x5615f5776afe  _PyObject_FastCallDict
    @     0x5615f13816e7  partial_call
    @     0x5615f5cbfee9  _PyEval_EvalFrameDefault
    @     0x5615f58e0a92  _PyEval_EvalCodeWithName.llvm.13210891564059904676
    @     0x5615f9d2faa2  function_call
    @     0x5615f6d48f7f  PyObject_Call
    @     0x5615efde4951  bounded_lru_cache_wrapper
    @     0x5615f5cbfee9  _PyEval_EvalFrameDefault
    @     0x5615f58e0a92  _PyEval_EvalCodeWithName.llvm.13210891564059904676
    @     0x5615f9d2faa2  function_call
    @     0x5615f6d48f7f  PyObject_Call
    @     0x5615efde4951  bounded_lru_cache_wrapper
    @     0x5615f5cbfee9  _PyEval_EvalFrameDefault
    @     0x5615f58e0a92  _PyEval_EvalCodeWithName.llvm.13210891564059904676
    @     0x5615f9d2faa2  function_call
    @     0x5615f6d48f7f  PyObject_Call
    @     0x5615f13816b0  partial_call
    @     0x5615f5cbfee9  _PyEval_EvalFrameDefault
    @     0x5615f5cbf17d  _PyEval_EvalFrameDefault
    @     0x5615f58e0a92  _PyEval_EvalCodeWithName.llvm.13210891564059904676
    @     0x5615f5cbf899  _PyEval_EvalFrameDefault
    @     0x5615f58e0a92  _PyEval_EvalCodeWithName.llvm.13210891564059904676
    @     0x5615f5cbf899  _PyEval_EvalFrameDefault

This is a bug in JAX's shape-checking rules; please report it!
https://github.com/google/jax/issues
```

(This situation was due to a bug in my code, which is now fixed, I just thought I'd report the shape checking bug)

### PR DESCRIPTION
**Pull request by bchetioui**
This closes google/jax#4316.

### CODE REVIEW

**Review by mattjj — APPROVED** [review]
LGTM, thanks for fixing this!

**Comment by mattjj** [comment]
Could you add a test that covers the case shown in #4316?

**Comment by SIben** [comment]
@mattjj added! Thanks!

**Comment by mattjj** [comment]
Nice!

**Comment by mattjj** [comment]
Internal tests pass!

**Pull request merged**
