### PR TITLE
Cleanup: avoid jnp.prod & np.prod on array shapes

### PR DESCRIPTION
**Pull request by jakevdp**
No need to push these to the device.

### CODE REVIEW

**Comment by shoyer** [comment]
It would probably be an even better idea to use the equivalent of `math.prod` (from Python 3.8) for array shapes. We have a backport of that in `jax.util`.

`np.prod()` returns NumPy integer scalars, which have their own minor inconsistencies (e.g., they round differently with the built-in `round()`).

**Comment by jakevdp** [comment]
> It would probably be an even better idea to use the equivalent of math.prod (from Python 3.8) for array shapes. We have a backport of that in jax.util.

Good idea – done.

**Comment by mattjj** [comment]
@shoyer I didn't know that about `np.prod`, thanks for explaining!

**Comment by jakevdp** [comment]
One important difference: `np.prod` will handle integer shapes, while `jax.utils.prod` raises a `TypeError` if the shape is not iterable. I looked through all the changes and I *think* there are no issues with that (it's used in places where iterable shapes are already required) but it would be worth a second look.

**Review by shoyer — APPROVED** [review]

**Pull request merged**
