### PR TITLE
Allow transpose axes to be negative to match (undocumented) NumPy behavior

### PR DESCRIPTION
**Pull request by kho**

### CODE REVIEW

**Review by hawkinsp — APPROVED** [review]

**Comment by jakevdp** [comment]
One comment here: `jax.lax` is often deliberately more strict than `jax.numpy`. I think requiring positive indices for `jax.lax.transpose` is consistent with the overall philosophy of the package. `jax.numpy.transpose` is what we expect to have a similar API to numpy.

**Review by hawkinsp — CHANGES_REQUESTED** [review]
I think Jake is right: the change should be in the numpy layer.

**Comment by kho** [comment]
Done. PTAL.

I was following `lax.squeeze` and `lax.expand_dims` which used `canonicalize_axis`. Now I see that the majority of `canonicalize_axis` calls indeed happen in `lax_numpy.py`.

**Review by jakevdp — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
