### PR TITLE
Relax tolerance for new test on TPU

### PR DESCRIPTION
**Pull request by gnecula**

### CODE REVIEW

**Comment by gnecula** [comment]
@jakevdp FYI. This kind of stuff is necessary now and then because of numeric differences on TPUs (we detect these when we import the code in Google)

**Comment by jakevdp** [comment]
Thanks - I'm surprised to see tolerance set to 0.5 regardless of dtype – is TPU really that imprecise for the higher-precision data types?

**Comment by mattjj** [comment]
That's probably a little loose; the rtol shouldn't have to be that high. But it's not fun to spend too much time tweaking tolerances to be just-tight-enough when the implementation errors we really want to guard against would likely lead to big deviations. That's how I currently think about it anyway!

**Comment by jakevdp** [comment]
Got it, thanks!

**Comment by gnecula** [comment]
I tried the test several times and this is the only number that made it pass consistently. I agree it seems very high.

**Pull request merged**
