### PR TITLE
Implement and make use of `jnp.asanyarray`.

### PR DESCRIPTION
**Pull request by tomhennigan**
`asanyarray` converts the input to an `ndarray`, but passes `ndarray` subclasses through.

PiperOrigin-RevId: 286240448

### CODE REVIEW

**Comment by hawkinsp** [comment]
I'm trying to understand the intent of the change. Can you say a bit more about what problem the wider use of `asanyarray` solves? Is there a concrete example of why it is preferable?

**Comment by tomhennigan** [comment]
So originally I just wanted to add `jnp.asanyarray` since it was missing.

Apologies for the very lacking PR message on the other change.

The main difference in my mind is that `jnp.asarray(a)` **always** returns a `DeviceArray` in JAX (compatible with numpy), while `asanyarray(a)` will pass through compatible `ndarray` subclasses (e.g. `onp.ndarray`, `ShardedDeviceArray`). I figured that in all of the replaced usages we just wanted a thing that implemented the `ndarray` API rather than specifically a `DeviceArray` so `asanyarray` was the right choice.

I'm not sure if it's actually important to do this for performance (since we likely just copy subclasses later in these functions so I am probably not saving a copy). I would be happy to split this into two PRs (adding the new API in one change and following up if replacing `asarray` with `asanyarray` is actually important performance wise in some specific case) if you would prefer.

**Comment by shoyer** [comment]
It seems to me that `jnp.asarray()` should also probably pass through `ShardedDeviceArray` objects. In which case I would guess `asanyarray` could simply be an alias to `asarray`.

I am hesitant to introduce different semantics between `asarray()` and `asanyarray()`. At least in NumPy, this function is there to support subclassing, but supporting external subclassing of JAX arrays feels like a dark path to go down...

**Comment by tomhennigan** [comment]
I agree that supporting user subclassing of JAX arrays is not a good idea today. I also think `asarray(a: ShardedDeviceArray) -> ShardedDeviceArray` is probably the correct behavior (e.g. asarray should pass through "builtin" array types). I'll drop this PR and follow up with that change instead (we can debate the details of that FR on there).

I don't think we should alias `asanyarray = asarray` since this sends a signal that users can expect subclassing to work (which we are not promising).

Thanks for the feedback!

**Pull request closed without merging**
