### PR TITLE
[ROCm] add build file.

### PR DESCRIPTION
**Pull request by Ruturaj4**
@dfm could you please take a look?

### CODE REVIEW

**Comment by dfm** [comment]
Thanks! It's not totally obvious to me that it makes sense for this to live in the JAX repo. For example, the helpers for installing and uninstalling packages seem a little overfit to a particular workflow. I think that it might make more sense for these functions to be described as part of the README in the `build/rocm` directory rather than a script like this, but if you feel strongly that it is important to add to JAX core, could you update the PR description with a more detailed argument for why? Thanks again!

**Comment by Ruturaj4** [comment]
@dfm thanks for you comments, and sorry for not clearly explaining the purpose of this script.
Initially, we had a version of build script ->  https://github.com/google/jax/blob/690dba546c03462bea8bc859e1900e6003f2ad60/build/rocm/build_rocm.sh. However, in recent versions it has been change and now it essentially does nothing (but prints some debugging info for logs) -> https://github.com/google/jax/blob/main/build/rocm/build_rocm.sh (However, we had to keep it regardless because our internal CI processes/ scripts still use this and it is not feasible to completely remove this sooner).

Now, we need a build script like in this commit, is because ->
1) Some of our internal repositories need to use something like this.
2) Some of our clients still use the previous version and appreciate an automated script like this up streamed in the main JAX repo.

Therefore, we decided to put this in jax/build/rocm directory and upstream. I will fix the readme to reflect this in another commit.

**Comment by mrodden** [comment]
This is meant to replace the dev_build script that some internal folks were using for building on their development machines. It was a direct request, otherwise I would agree, I am not sure why it would be needed :/

**Comment by dfm** [comment]
Thanks for the clarification @Ruturaj4 and @mrodden! I'll review and get this integrated ASAP.

**Review by dfm — APPROVED** [review]

**Pull request merged**
