### PR TITLE
Create JAX Enhancement Proposals (JEPs).

### PR DESCRIPTION
**Pull request by hawkinsp**
Migrate existing design documents to JEPs.

### CODE REVIEW

**Comment by jakevdp** [comment]
I think there are a few remaining places in the JAX package where `design_notes` URLs are references; we should update these to the new locations.

**Comment by jakevdp** [comment]
e.g. https://github.com/google/jax/blob/022fedde98ed23bf4ea636e2f8a396ede68f82c9/jax/random.py#L69

**Review by froystig — APPROVED** [review]
Thanks for getting this started!

**Comment by hawkinsp** [comment]
> I think there are a few remaining places in the JAX package where `design_notes` URLs are references; we should update these to the new locations.

Done.

**Pull request merged**
