### PR TITLE
Rm two unused lines of code from lax_parallel.psum_bind

### PR DESCRIPTION
**Pull request by j-towns**

### CODE REVIEW

**Comment by j-towns** [comment]
I'm attempting to repro the dependency install test failures on my own fork and hopefully fix them.

**Comment by jakevdp** [comment]
installation failures are likely due to a timeout from pypi.org: we've seen a number of these recently. Are you able to restart the github actions jobs?

**Review by jakevdp — APPROVED** [review]

**Comment by j-towns** [comment]
It looks like a mismatched hash on the tf-nightly whl. The wheel is a large-ish file (~320 MB), so maybe the download is too slow or is interrupted for some reason.

I can't see an obvious way to restart the jobs :(

**Comment by jakevdp** [comment]
I've restarted them. The change looks fine – I'll merge it once CI is green.

**Comment by mattjj** [comment]
This was a bad merge on my part! I believe this passes internal tests.

**Pull request merged**
