### PR TITLE
Fix #396 by updating the comment in README.md

### LINKED ISSUE #396: clarification to README
First, thanks a lot for this amazing package. 

I noted that in the README.md there is an example that says: 

```
In [5]: print(np.dot(x, x.T) / 2)  # fast!
[[  2.52727051e+03   8.15895557e+00  -8.53276134e-01 ...,  # ...

In [6]: print(np.dot(x, x.T) / 2)  # even faster!
[[  2.52727051e+03   8.15895557e+00  -8.53276134e-01 ...,  # ...
```
Given that both examples are exactly the same, maybe there is a mistake here in saying the other is "even faster". 

Thanks again for JAX, I feel that this will be a gift that keeps giving. Bonus points for a funky and very well crafted logo!

### PR DESCRIPTION
**Pull request by bharatr21**
Fix #396 by updating the comment in README.md

### CODE REVIEW

**Comment by mattjj** [comment]
Awesome, thanks for tying off this loose end!

The only downside is that now the text overflows the GitHub-rendered text box, making it scroll horizontally.  Two ideas for fixing that:

1. delete the "in the second call" part, or
2. shorten it to "in the 2nd call".

What do you think? Can you make it not overflow?

**Comment by Bharat123rox** [comment]
@mattjj in case you do plan to follow an 80-chars convention, may I just go ahead and put the remaining part on the next line?

**Comment by mattjj** [comment]
No 80 char convention here. It looks like GitHub supports ~105 characters before overflowing its code box element. Since this comment is so close to fitting on one line, I think it's better just to delete a few characters, but if you'd rather wrap it to a second line then make that change and let's take a look!

**Comment by Bharat123rox** [comment]
@mattjj IMHO this feels neater than just deleting a few characters on the same line, but if you want it on the first line, I'll do it anyway :+1:

**Comment by mattjj** [comment]
Looks good to me! I like the way you did it.

**Pull request merged**
