### PR TITLE
Adding an option to return the output tree in make_jaxpr

### PR DESCRIPTION
**Pull request by botev**

### CODE REVIEW

**Comment by mattjj** [comment]
Thanks!

Could we make this match `xla_computation`'s `return_shape` option? (Both in parameter name and in what gets returned.)

**Comment by botev** [comment]
I think this should now be in that format - e.g. returning the out_avals in the correct tree format.

**Comment by mattjj** [comment]
Awesome, thanks! I should've also suggested adding a simple test. I pushed a commit that did that, and also returned ShapeDtypeStruct instances rather than ShapedArrays (to match `xla_computation` better).

**Review by mattjj — APPROVED** [review]
LGTM!

**Comment by botev** [comment]
Oh, sorry I did not noticed that the leaves are `ShapeDtypeStruct`, but thanks for making this ready to merge :)

**Pull request merged**
