### PR TITLE
Add Github Actions supported wheel-builds for CPU-only jaxlib on Winx64 

### PR DESCRIPTION
**Pull request by mlxd**
**Context:** This PR aims to build CPU-only x64 wheels for Windows platforms. Since the current jaxlib wheel support for Windows is community-oriented with no officially-supported builds, this causes problems for platforms that need a cross-platform way to depend on jax, of which has become a recent issue for us on [PennyLane](https://github.com/PennyLaneAI/pennylane). Our goal to to fully replace autograd (our default AD framework) in PennyLane with jax, and we require officially supported Windows wheels to allow this. This PR follows a recent discussion between Xanadu (@mlxd @trbromley) and the JAX team (@hawkinsp @yashk2810 ) on Xanadu preliminary exploring and adding the support.

**Description of the Change:** This PR adds a Github Actions workflow to make use of the `windows-2019` runner and Visual Studio Enterprise 2019 to build jaxlib wheels, targeting CPU-only execution under Windows. This has been validated on 16GB private instances, though may require additional configuration to ensure memory walls are not hit on the 7GB free instances.

**Benefits:** Adds native support for CPU-only jaxlib under Windows.

**Possible Drawbacks:** Additional maintenance may be required for further development and extensions. May require a larger CI runner to compile end-to-end.

### CODE REVIEW

**Comment by hawkinsp** [comment]
You'll need to sign the CLA first.

**Comment by mlxd** [comment]
> You'll need to sign the CLA first.

Thanks @hawkinsp . Just checking for internal approval, will sign when confirmed.

**Comment by mlxd** [comment]
Hey @hawkinsp just dropping in to say the CLA is signed. Feel free to reach out if anything else is needed.

**Comment by jlperla** [comment]
Is this really the dream it seems?  CPU-only JAX available which can be added with standard pip requirements/etc?  If there is any chance this is available in the next few months as an official release it would make JAX a feasible alternative for teaching ML to students in fall coursework.

**Comment by madhavajay** [comment]
Can someone at Google please merge this?

**Comment by cloudhan** [comment]
Address this https://github.com/google/jax/issues/15907, then we will be able build CPU and CUDA natively on Windows.

@jlperla At the moment, you can use https://github.com/cloudhan/jax-windows-builder for old version jaxlib builds.

The idea that use free tier Github Actions to build jaxlib is actually executed poorly in https://github.com/cloudhan/jax-windows-builder. The problem is not disk space and RAM space. The OS SSD is ~120GB and tmp HDD disk is 16GB. You can mount a 32GB swap disk for RAM. The root problem is 2 cores for building without caching. Debugging and rebuilding is a pain in the ass and it is unmaintainable for community (but possible for individual). The CPU jaxlib will take ~5 hours and CUDA jaxlib will take ~6 hours, where 6 hours is the hard limit for a single job in github actions. To enable windows build, some inc, say Google, MS or maybe some other startups that advocate Bazel, need to donate some resource to it.

**Review by hawkinsp — APPROVED** [review]

**Comment by mlxd** [comment]
> I'm going to merge this and see how it goes. I believe we may be able to budget for a larger runner, but I'll make that change in a subsequent PR.

Sounds good, thanks @hawkinsp 
Feel free to tag me if I can help out in any further way.

**Comment by hawkinsp** [comment]
Ok, we're making some progress here.

I forked this config to make a new "Windows CI" config (https://github.com/google/jax/actions/workflows/windows_ci.yml
) that is triggered:
* nightly
* when manually triggered.

This action builds jaxlib and runs the tests for one Python version (3.9, at the moment).

After a bit of iteration, we can build jaxlib and run the tests:
https://github.com/google/jax/actions/runs/5259225418/jobs/9504483477

It took around 57 minutes on a 16 core Windows 2019 VM. Since a 16 core VM costs $0.125 per minute, this means the build cost about $7.25. So it's a bit too expensive and slow to run as a presubmit at the moment.

Most tests pass:
`========= 12 failed, 17357 passed, 2138 skipped in 747.98s (0:12:27) ==========`

I've actually already fixed a few of those, namely https://github.com/openxla/xla/pull/3544 fixes `LaxTest.testRngBitGeneratorReturnedKey` and https://github.com/google/jax/pull/16373 fixes `MetadataTest.test_source_file_prefix_removal`.

PRs to fix any of the other problems welcome!

**Pull request merged**
