### PR TITLE
Add a bot that adds kokoro:run label when the PR is approved automati…

### PR DESCRIPTION
**Pull request by yashk2810**
…cally.

We can also add pull-ready label via this bot. But I want to test kokoro:run first.

If this doesn't work, I'll revert the changes.

### CODE REVIEW

**Review by froystig — COMMENTED** [review]
Could this be simplified if we used github's built-in [labeler action](https://github.com/marketplace/actions/labeler)?

**Comment by yashk2810** [comment]
There's this too: https://github.com/marketplace/actions/label-approved-pull-requests. Can you use this?

**Comment by yashk2810** [comment]
So I used the github script action and modified the bot. I think this should work.

**Review by froystig — APPROVED** [review]
Approving to test.

Separately: can we rename the workflow config file to something along the lines of `pull-request-review.yaml`?

**Review by froystig — APPROVED** [review]
approving just to test, again.

**Comment by yashk2810** [comment]
Test comment

**Review by froystig — CHANGES_REQUESTED** [review]
It seems review approval is a tricky event to listen for. I also think that the `pull ready` label is a more appropriate event. Let's try gating on that instead?

**Pull request closed without merging**
