### PR TITLE
[ROCm] ROCm specific fixes.

### PR DESCRIPTION
**Pull request by rsanthanam-amd**

### CODE REVIEW

**Comment by hawkinsp** [comment]
Thanks for the PR, sorry for the breakage. (I did my best to update the AMD GPU path, but I have no way to test it.)

I suspect we should merge more of the Python code in jaxlib between the AMD and NVidia paths, given they are almost copy-and-paste clones with only renaming substitutions.

**Review by hawkinsp — APPROVED** [review]

**Comment by rsanthanam-amd** [comment]
@hawkinsp gentle ping.  please merge this when you get a chance.  thanks!

**Comment by hawkinsp** [comment]
Thanks for the fix, I apologize it got lost in my list of PRs.

**Comment by rsanthanam-amd** [comment]
Soon after I left that comment, the copybara-service bot merged it.  I guess it runs once a week.

**Comment by hawkinsp** [comment]
Actually, no, it needs action on our side. (The PR gets a final review to check it's safe to merge.) So you did the right thing in pinging me!

**Pull request merged**
