### PR TITLE
Add population_count primitive to lax

### LINKED ISSUE #2263: Feature request: enable XLA PopulationCount op
I think XLA has a PopulationCount op, listed [here](https://www.tensorflow.org/xla/operation_semantics#element-wise_unary_functions). Is it straightforward for JAX to expose it in lax.py? @hawkinsp I'm thinking you might be the right person to ask.

### PR DESCRIPTION
**Pull request by j-towns**
Fixes https://github.com/google/jax/issues/2263.

### CODE REVIEW

**Comment by j-towns** [comment]
Will see if I can fix the test failures Monday.

**Comment by mattjj** [comment]
I think the mypy failure was from master and has since been fixed. I'll try doing a merge from master into this branch.

**Comment by mattjj** [comment]
Internal tests pass, Travis mypy passes, I think this is safe to merge.

**Review by mattjj — APPROVED** [review]
Also, LGTM!

**Pull request merged**
