### PR TITLE
Prevent nans in scale_and_translate

### LINKED ISSUE #6780: nans in gradient of scale_and_translate
I'd like to take gradients of `scale_and_translate` wrt the translation parameters.  Currently the gradients are `nan` whenever the translation is >1.  Example: 

```python
import jax
import jax.numpy as jnp
from jax.image import scale_and_translate

xin = jnp.r_[:16].reshape(4, 4) + 1.
xin = jax.device_put(xin)

def f(x):
    out = scale_and_translate(xin, shape=xin.shape, spatial_dims=(0, 1),
                              scale=jnp.array([1.0, 1.0]),
                              translation=jnp.array([x[0], x[1]]),
                              method='linear', antialias=True)
    return out

f((1.1, 1.2))  # raises an error if JAX_DEBUG_NANS=1

g = lambda x: jnp.sum(f(x))

print(jax.grad(g)( (1.1, 1.2)))  # nans
```

If `JAX_DEBUG_NANS=1` is set, the script throws an exception at the evaluation of `f`:
```
Traceback (most recent call last):
  File "resize.py", line 15, in <module>
    f((1.1, 1.2))  # raises an error if JAX_DEBUG_NANS=1
  File "resize.py", line 9, in f
    out = scale_and_translate(xin, shape=xin.shape, spatial_dims=(0, 1),
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/_src/image/scale.py", line 219, in scale_and_translate
    return _scale_and_translate(image, shape, spatial_dims, scale, translation,
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/_src/image/scale.py", line 92, in _scale_and_translate
    w = compute_weight_mat(m, n, scale[i], translation[i],
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/_src/image/scale.py", line 69, in compute_weight_mat
    weights / total_weight_sum, 0)
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 5666, in deferring_binary_op
    return binary_op(self, other)
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 569, in true_divide
    return lax.div(x1, x2)
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/_src/lax/lax.py", line 352, in div
    return div_p.bind(x, y)
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/core.py", line 264, in bind
    out = top_trace.process_primitive(self, tracers, params)
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/core.py", line 606, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/interpreters/xla.py", line 232, in apply_primitive
    return compiled_fun(*args)
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/interpreters/xla.py", line 351, in _execute_compiled_primitive
    check_special(prim.name, out_bufs)
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/interpreters/xla.py", line 370, in check_special
    _check_special(name, buf.xla_shape(), buf)
  File "/home/pfister/miniconda3/envs/scico/lib/python3.8/site-packages/jax/interpreters/xla.py", line 376, in _check_special
    raise FloatingPointError(f"invalid value (nan) encountered in {name}")
FloatingPointError: invalid value (nan) encountered in div
```

The issue is in this block: 
https://github.com/google/jax/blob/c85e835951c68b4383dbc9ef25bef99ea996fd84/jax/_src/image/scale.py#L66-L69
in particular, the computaiton `weights/total_weight_sum` can involve a divide by 0, even though those locations get set to zero in the course of the `jnp.where`.

I'll submit a PR shortly with the "where inside of where" fix.

### PR DESCRIPTION
**Pull request by lukepfister**
fixes #6780

### CODE REVIEW

**Comment by lukepfister** [comment]
@googlebot I signed it!

**Comment by hawkinsp** [comment]
The fix looks plausible: would you mind also adding a test that would exhibit the problem? `tests/image_test.py` seems like a good place for it.

**Comment by lukepfister** [comment]
Sure, it might take a day or two. 

I noticed that running `image_test.py` with `JAX_DEBUG_NANS=1` yields 12 test failures involving NaNs.  This fix takes care of two of them.

Would you prefer them all to be fixed in a single PR or are multiple PRs okay?

**Comment by hawkinsp** [comment]
Multiple PRs are fine — whatever works best for you!

**Comment by lukepfister** [comment]
Adding the "double where" division to `_fill_lanczos_kernel` fixed the remaining test failures when `JAX_DEBUG_NANS=1` is set.  I'll add dedicated tests soon.

**Comment by hawkinsp** [comment]
I suspect the `_fill_lanczos_kernel` warnings are more in the line of false-positives from the NaN checker. We don't differentiate through the kernel generation function. That said, suppressing the warnings seems like a fine thing to do!

**Comment by lukepfister** [comment]
Pushed a test; sorry for the delay!

**Review by hawkinsp — APPROVED** [review]

**Pull request merged**
