### PR TITLE
[NVIDIA] Fix unsupported dbias in bwd batcher of cudnn sdpa API

### PR DESCRIPTION
**Pull request by kaixih**
Stemmed from the [issue](https://github.com/jax-ml/jax/issues/23701).

This PR fixes the segfault issue. When the bias batch size > 1 during the batching, we shouldn't expect the d_bias, instead an all-zero gradient should be returned. This behavior then is consistent with the non-batching (no vmap) version.

cc. @superbobry @Cjkkkk

### CODE REVIEW

**Comment by superbobry** [comment]
Can you add a test case for the new behavior, please?

**Comment by kaixih** [comment]
@superbobry Done. PTAL.

**Comment by superbobry** [comment]
Thanks, the comment in the test case is very helpful as well.

Wouldn't it be less surprising (and possibly more useful) to fail instead of silently setting `dbias` to all zeros?

**Comment by kaixih** [comment]
I believe this PR aims to make the vmap behavior consistent with the non-vmap version, where dbias returns all zeros when B is not 1. However, I'm unsure if we want to maintain this behavior for the non-vmap version (see the discussion below).

> Wouldn't it be less surprising (and possibly more useful) to fail instead of silently setting dbias to all zeros?

I've heard there are models that don't use dbias, so changing this behavior might break their usage. If we truly want to implement an error-out behavior (i.e., throwing an error when we encounter an unsupported dbias shape, regardless of whether the user actually uses it), I think a separate PR is needed to implement this logic in https://github.com/jax-ml/jax/pull/23740. We would then remove the `has_dbias` check. @Cjkkkk, any thoughts?

We also had a similar discussion in [the original issue](https://github.com/jax-ml/jax/issues/23701), where we agreed that we don't want such silent all-zero dbias in the public SDPA API and we don't care about how the private SDPA API does. That is also why I have this PR (https://github.com/jax-ml/jax/pull/23740) for the public API to work around this issue.

@Cjkkkk for comments.

**Comment by superbobry** [comment]
Thanks for the extra context @kaixih. I think this can go in as is.

**Review by superbobry — APPROVED** [review]

**Pull request merged**
