### PR TITLE
Glorot uniform, kalmning normal and kalming uniform initializer

### PR DESCRIPTION
**Pull request by joaogui1**
An implementation of some commonly used initializers following the stax coding style.

### CODE REVIEW

**Comment by joaogui1** [comment]
Hey @mattjj can someone from the jax team review this PR? Is there any interest in it?

**Comment by jekbradbury** [comment]
We're looking to include more initializers soon, but we're taking the opportunity to align initializer definitions with Sonnet and Keras for consistency (and because the implementations can be subtle). Can you take a look at https://github.com/google/jax/blob/jb/initializers/jax/nn/initializers.py and see if there are initializers missing that you'd like to see included?

**Comment by joaogui1** [comment]
Oh, that seems good, except that (in jax at least) the uniform with standard arguments is from 0 to 1, so multiplying it by sqrt(scale) will get you the uniform from 0 to sqrt(scale), and I believe what you really you want is the uniform from -sqrt(scale) to sqrt(scale), so you should use 
`random.uniform(key, shape, minval=-1, dtype) * onp.sqrt(3 * scale)`
or something similar, istead of:
`random.uniform(key, shape, dtype) * onp.sqrt(3 * scale)`
Should I close this PR then?

**Comment by jekbradbury** [comment]
Good catch! Yes, I hope #1262 includes the functions you need.

**Comment by mattjj** [comment]
@joaogui1 thanks for this work, which @jekbradbury incorporated into #1262, merged with his other cleanup efforts! (And apologies for not responding to the PR sooner; our response times can be pretty uneven, depending on purely exogenous factors!)

**Pull request closed without merging**
