### PR TITLE
Simplify util.py

### PR DESCRIPTION
**Pull request by YouJiacheng**
And cover #10274

### CODE REVIEW

**Comment by jakevdp** [comment]
Thanks for the contribution! For reasons why we don't want to simplify some of these, see the discussion in https://github.com/google/jax/pull/6758

**Comment by YouJiacheng** [comment]
Thanks for nice explanation! But maybe some of changes doesn't break error message.

**Comment by YouJiacheng** [comment]
@jakevdp could you please have a look again? I revert change on `unzip2` and `unzip3` and add a comment.

**Comment by jakevdp** [comment]
Since this overlaps work in #10274, let's wait for a review there before making any decisions here.

**Comment by jakevdp** [comment]
I think we want to keep these utilities as-is. Sorry we weren't able to merge this!

**Pull request closed without merging**
