### PR TITLE
Use custom_jvp for lax.custom_root.

### PR DESCRIPTION
**Pull request by shoyer**
This gives us a batching rule, for free!

### CODE REVIEW

**Comment by shoyer** [comment]
@mattjj gentle ping here

**Comment by mattjj** [comment]
I wish someone would send me a "forceful ping" someday.

**Review by mattjj — APPROVED** [review]
Wow, really nice!

We should put our heads together about making derivative rules for higher-order functions so that we don't require tracing to a jaxpr. I think dougalm figured out a plan.

**Comment by shoyer** [comment]
> We should put our heads together about making derivative rules for higher-order functions so that we don't require tracing to a jaxpr. I think dougalm figured out a plan.

Yes, this would be really exciting!

**Pull request merged**
