### PR TITLE
Simplify and encapsulate `PartialVal`.

### PR DESCRIPTION
**Pull request by chr1sj0nes**

### CODE REVIEW

**Comment by jekbradbury** [comment]
I would like to see this change (I can never remember which one goes first in the existing tuple), and it's probably a bit of a pain to keep rebased. I might be missing possible downsides, though? Either way pinging @mattjj for his gut feeling about it.

**Comment by mattjj** [comment]
Thanks for the ping.

My gut feeling is this seems fine, though one decision seems flipped: it seems like the `PartialVal` constructor should be the general thing that takes two arguments, and `make_pval` should be the convenience wrapper that takes only one.

Other than that (which lmk if you have another opinion on), seems like a good utility function cleanup!

**Comment by chr1sj0nes** [comment]
I'm hoping to remove the tuple pair representation of `PartialVal` (and therefore also `make_pval`) entirely. I'm not sure if that's realistic, though.

**Comment by mattjj** [comment]
What alternative do you have in mind? I think we need a sum type here, like

```haskell
PartialVal = Known Const | Unknown AbstractValue
type Const = MaybeTraced JaxType
```

We're simulating that with tags, and with a pair instead of a (tag, optional const, optional aval) triple.

It seems pretty simple, as in there isn't any extra information being maintained AFAICT. Maybe it could be abstracted or rearranged?

**Comment by chr1sj0nes** [comment]
As demonstrated in this PR, I don't think the tag is necessary as `JaxType != AbstractValue`. There are several places in the code where `PartialVal`s are split into the `pv, const` pair, then reassembled later. I wonder if those can be eliminated by just passing the `PartialVal`s through.

**Comment by jekbradbury** [comment]
Yeah, I believe the tuple-as-sum-type might have been needed when JaxTypes could themselves be tuples, but now there’s no ambiguity in a non-tupled pval about whether it’s a aval or a const?

**Comment by hawkinsp** [comment]
Closing as stale.

**Pull request closed without merging**
