### PR TITLE
Support for non-scalar np.repeat arguments (fixes #1233)

### LINKED ISSUE #1233: Support for non-scalar np.repeat arguments.
Hello, 

I noticed that jax.numpy.repeat does not support non-scalar repeats.

```
np.repeat(np.array([[1, 2, 3]]), np.array([2, 3, 1]))

NotImplementedError                       Traceback (most recent call last)
<ipython-input-120-c0c19bd58e3a> in <module>()
----> 1 np.repeat(np.array([[1, 2, 3]]), np.array([2, 3, 1]))

google3/third_party/py/jax/numpy/lax_numpy.py in repeat(a, repeats, axis)
   1539   if not isscalar(repeats):
   1540     raise NotImplementedError(
-> 1541         "np.repeat implementation only supports scalar repeats")
   1542   if axis is None or isscalar(a):
   1543     a = ravel(a)
```

The expected results with numpy:
```
array([1, 1, 2, 2, 2, 3])
```

Note that the documentation indicates that this is supported:
https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.repeat.html

Is it possible to add support for this in jax, and/or is there a workaround?

### PR DESCRIPTION
**Pull request by xysun**
This PR fixes #1233 

It largely used the same logic and test suite from numpy. 

Tested with jit compile too.

### CODE REVIEW

**Comment by xysun** [comment]
@googlebot I signed it!

**Comment by xysun** [comment]
Hi @mattjj can you or anyone in your team take a look at this PR please? (Sorry to @ you directly -- I took the liberty as you commented on the original issue 😃 )

**Comment by jekbradbury** [comment]
I think this implementation is correct, but it's likely suboptimal on accelerators ("a triply-nested loop of `dynamic_update_slice` and `dynamic_slice`" is among the scariest things the XLA compiler can hear). Is there an equivalent implementation using indexing or gather/scatter? In general, implementations similar to NumPy's Python code (using vectorization and as few primitive calls as possible) are likely to be more performant than those that are based on NumPy's C routines (which tend to be nested loops of imperative, scalar code).

**Comment by xysun** [comment]
Thanks for the pointers. I'll take a look.

**Comment by mattjj** [comment]
(By the way, I certainly don't mind direct pings. Actually I appreciate them!)

**Comment by mattjj** [comment]
Using `scatter`/`gather` is pretty tough. [The wrappers in `jax.ops`](https://jax.readthedocs.io/en/latest/jax.ops.html) are much easier to use, though we might have to avoid a circular dependence problem since [that file imports lax_numpy.py](https://github.com/google/jax/blob/master/jax/ops/scatter.py#L28).

In particular, `index_update` should let us express something similar to this logic, and the API is essentially NumPy indexing.

**Comment by mattjj** [comment]
Actually, can we just call `lax.broadcast_in_dim` here?

**Comment by mattjj** [comment]
Maybe not: I was hoping we could do a `lax.broadcast_in_dim` followed by some reshaping, but this example from the `np.repeat` docstring suggests it won't be so simple:

```
>>> x = np.array([[1,2],[3,4]])
>>> np.repeat(x, [1, 2], axis=0)
array([[1, 2],
       [3, 4],
       [3, 4]])
```

In particular, we go from a `(2, 2)` array to a `(3, 2)` array.

Still, maybe we can just do some logic with `np.concatenate` instead of doing any index-updating. Using index-updating seems harder to write and maybe less performant.

**Comment by mattjj** [comment]
Take a close look at `np.tile` if you haven't already! That may have some helpful clues.

**Comment by xysun** [comment]
@mattjj @jekbradbury I managed to come up with a way using `tile`, `split` and `concatenate`. 
No more nested loops of `dynamic_update_slice`. Please review 😃

**Review by jekbradbury — APPROVED** [review]

**Comment by xysun** [comment]
hey @jekbradbury @mattjj I see you both approve of the changes. Thanks! What do I need to do to get this merged? :)

**Comment by jekbradbury** [comment]
Thanks, @xysun!

**Pull request merged**
