### PR TITLE
fix wording

### PR DESCRIPTION
**Pull request by jsebestyen**
pmap not used so it's not the "whole"

### CODE REVIEW

**Comment by jsebestyen** [comment]
@googlebot I signed it!

**Review by ayaka14732 — APPROVED** [review]

**Comment by jakevdp** [comment]
Sorry, not sure how I lost track of this.

**Comment by jakevdp** [comment]
We'll need to make the same change in the accompanying notebook before we can merge this. That's covered by the lint test that failed to run because our test suite was broken when you opened this PR.

If you're still interested in contributing this fix, please rebase on the main branch and follow the instructions at https://jax.readthedocs.io/en/latest/developer.html#update-notebooks

If not, please let me know and I can make the fix. Thanks!

**Comment by ayaka14732** [comment]
@jakevdp I think you can make the fix since the OP is no longer active on GitHub within 1 year.

**Comment by jakevdp** [comment]
Replaced by #18376

**Pull request closed without merging**
