### PR TITLE
cosmetic edits in docs

### PR DESCRIPTION
**Pull request by ngam**
minor edits to clarify docs:
- consistent `<code>` vs '<text>' blocks
- always lowercase `pjit` and adopt `pjit`ted instead of pjit'd (following convention from earlier 101 tutorials with "jitted")

No substantial edits in content.

### CODE REVIEW

**Comment by ngam** [comment]
> Thanks for your pull request! It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> For more information, open the [CLA check for this pull request](https://github.com/google/jax/pull/10626/checks?check_run_id=6341052854).

If the maintainers want to adopt this minor (unsolicited) PR, I will sign the CLA. If not, there is no point in signing it _for now_.

**Comment by hawkinsp** [comment]
Thanks for the PR. At a quick glance, this looks like something we should merge. But you'd have to sign the CLA for us to do so.

**Comment by ngam** [comment]
> Thanks for the PR. At a quick glance, this looks like something we should merge. But you'd have to sign the CLA for us to do so.

Since this is just minor stuff, I didn't bother with re-rendering stuff, assuming the CI will take care of that. But let me know if you'd like me to change things or do things differently.

**Review by hawkinsp — APPROVED** [review]

**Comment by hawkinsp** [comment]
@jakevdp reminded me that we need to also update the corresponding notebook: https://jax.readthedocs.io/en/latest/developer.html#update-notebooks

**Review by hawkinsp — CHANGES_REQUESTED** [review]
Notebook needs updating also.

**Comment by ngam** [comment]
`jupytext --sync docs/jax-101/*` ([as here](https://jax.readthedocs.io/en/latest/developer.html#update-notebooks)) fails because of an rst file 

```
$ jupytext --sync docs/jax-101/*
...
jupytext.paired_paths.InconsistentPath: 'docs/jax-101/index.rst' is not a notebook.
```

The fix is to run `jupytext --sync docs/jax-101/*.md` and then `jupytext --sync docs/jax-101/*.ipynb` (not sure while more wildcards didn't work, e.g. `jupytext --sync docs/jax-101/*.{ipynb,md}` or maybe I was doing something wrong locally)

**Comment by jakevdp** [comment]
Try running this:
```
jupytext --sync docs/jax-101/08-pjit.md
```

**Comment by jakevdp** [comment]
Once you've done this, you'll have to add and commit the ipynb updates and push to this branch.

**Comment by ngam** [comment]
> Try running this:
> 
> ```
> jupytext --sync docs/jax-101/08-pjit.md
> ```


```
~/Repos/jax$ git checkout patch-1
Already on 'patch-1'
Your branch is up to date with 'origin/patch-1'.
~/Repos/jax$ jupytext --sync docs/jax-101/08-pjit.md
[jupytext] Reading docs/jax-101/08-pjit.md in format md
[jupytext] Updating the timestamp of docs/jax-101/08-pjit.md
~/Repos/jax$ git status
On branch patch-1
Your branch is up to date with 'origin/patch-1'.

nothing to commit, working tree clean
~/Repos/jax$ 
```

😅

**Review by jakevdp — APPROVED** [review]

**Comment by ngam** [comment]
Ah, I was just also curious why I couldn't find `08-pjit.ipynb`! Makes sense, I was getting really confused. Thanks for your help!!

**Pull request merged**
