### PR TITLE
Default lax.scan XS value as None

### PR DESCRIPTION
**Pull request by LouisGobert**
See #20855

### CODE REVIEW

**Comment by LouisGobert** [comment]
@jakevdp Here's a PR that defines a default None value for the xs parameter of lax.scan.

**Comment by jakevdp** [comment]
The diff is surprisingly large – could you try rebasing against an updated `main` branch?

**Comment by jakevdp** [comment]
Oh, it looks like you ran some sort of autoformatter on the file. Let's avoid that here, please.

**Comment by LouisGobert** [comment]
@jakevdp Yes, sorry. I have fixed the format

**Comment by jakevdp** [comment]
Thanks! Part of this change will be adding a test of the new default. Probably a new test in `lax_control_flow_test.py` would be the best option.

**Comment by jakevdp** [comment]
I think we're going to go with #20901 on this, as that is the user who initially raised the issue and offered to create the PR – thanks!

**Pull request closed without merging**
