### PR TITLE
Fix pmap compilation cache regressions from #4904.

### PR DESCRIPTION
**Pull request by apaszke**
AD didn't use `HashableFunction` enough, tripping up the compilation cache.
I've also used the occasion to make the hashing a little safer by tagging
each place that `HashableFunction` with a unique tag in its key.

### CODE REVIEW

**Review by mattjj — CHANGES_REQUESTED** [review]
Can we add some tests here? In the review on #4904 I mentioned some ideas for tests we could add, and it sounds like there is a specific issue that prompted this change for which we should add a test too.

**Comment by mattjj** [comment]
In particular, it seems like this fix may have been prompted by a grad-of-pmap caching bug. If so, such a test could be similar to the [`test_grad_of_jit_compilation_caching`](https://github.com/google/jax/blob/087b7b81ac356cb9c246354fcf51ddeef6387a3c/tests/api_test.py#L1766) test.

**Comment by skye** [comment]
There's an even better way to test caching: `jtu.count_jit_and_pmap_compiles()`! See the test case I added in https://github.com/google/jax/pull/5037/files (I'll also update that PR to add the extra cache key assuming this goes in first).

**Comment by apaszke** [comment]
So I thought about adding a test, but honestly I would like to make this a bit more structured.

This directly touches upon our discussion about #4923, which fixes the situation with vmap, but not AD. This patch should make AD better, but not vmap... I'd really like us to sketch out what kind of compositions do we expect to preserve the compilation cache, because without it we might just end up with a bunch of random cases in the tests, and that's not a good way to design API semantics. This is why I've skipped the test for now, but I can add it if you _really_ think that it's a good idea to evolve it in such an ad-hoc way.

**Review by mattjj — APPROVED** [review]

**Pull request merged**
