### PR TITLE
nightly multiprocess test: create issue on failure

### PR DESCRIPTION
**Pull request by jakevdp**
Pushed from a branch on the main repo in order to test issue creation on forced failure (which is prevented from branches on forks)

Added a failure to the test so we can see the automatic issue creation.

### CODE REVIEW

**Comment by jakevdp** [comment]
@sudhakarsingh27 any idea why the SLURM process is not terminating?

**Comment by jakevdp** [comment]
We had a successful failure! The SLURM job failed on my `assert False` test: https://github.com/google/jax/runs/7756398222?check_suite_focus=true

And it led to the creation of this issue: https://github.com/google/jax/issues/11820

**Comment by jakevdp** [comment]
It might be better if we paste the contents of the artifacts to the issue description... I might give that a try.

**Comment by sudhakarsingh27** [comment]
> It might be better if we paste the contents of the artifacts to the issue description

I think it's a good idea, although there's output from multiple nodes in the artifacts. I guess uploading `output*0.txt` contents should be sufficient since if one of the processes failed, it's highly probable that the others would've failed too.

**Comment by jakevdp** [comment]
I just added an attempt to put the formatted logs in the issue description... let's see if it works

**Comment by jakevdp** [comment]
Reporting works! https://github.com/google/jax/issues/11822

I'm going to clean up and get ready to submit this.

**Review by sudhakarsingh27 — APPROVED** [review]
LGTM. Thanks for doing this!

**Pull request merged**
