### PR TITLE
README.md correct typo

### PR DESCRIPTION
**Pull request by chrisfcarroll**

### CODE REVIEW

**Comment by mattjj** [comment]
Thanks for looking over the readme! This actually isn't a typo though: we set the value of `inputs` to be used on the subsequent loop iteration (by the line above this one). I read it as "produce the inputs to the next layer."

I really appreciate you looking for and suggesting fixes to typos; it's better to have some false alarms than to miss any detections!

**Comment by chrisfcarroll** [comment]
👍

**Comment by jakevdp** [comment]
This is at least the second time someone has flagged this particular line in the README as confusing - perhaps it would be useful to add a comment in the code describing the intent?

**Comment by chrisfcarroll** [comment]
Then the solution would be to change the variable names `input` & `output` to express the intent, but alas I cannot divine from the snippet what the intent is. Is it something like this?

```
def predict(params, activations_accumulator):
  for W, b in params:
    layer_activation = jnp.dot(activations_accumulator, W) + b
    activations_accumulator = jnp.tanh(outputs)
  return layer_activation

def sum_squared_error(params, activations_accumulator, targets):
  preds = predict(params, activations_accumulator)
  return jnp.sum((preds - targets)**2)

gradients_fun = jit(grad(sum_squared_error))  # compiled gradient evaluation function
perex_gradients = jit(vmap(gradients_fun, in_axes=(None, 0, 0)))  # fast per-example grads
```

**Comment by mattjj** [comment]
Well, nothing's being accumulated, so maybe not `activations_accumulator`. Using `activations` seems okay but I'm not sure if it's much more descriptive than `inputs`, and moreover (1) I forget if "activations" is meant to refer to the values before or after the nonlinearity, and (2) it's a bit jargon-y.

@jakevdp We could just add the comment "inputs = jnp.tanh(outputs)  # inputs for the next layer" or something.

**Comment by jakevdp** [comment]
chrisfcarroll@ I think the intent is "outputs from one layer become inputs to the next". Do you think that comment would have been sufficient to help you understand the intent?

**Comment by chrisfcarroll** [comment]
I would hate to be responsible for introducing a comment to explain a variable name into even a dummy piece of code. I think that if a function mutates a parameter, then calling that parameter an input is a muddle; that if an example piece of code in a readme file uses `input` for a function's input & `output` for its output then I leap to the conclusion they are dummy names used just because it's an simple example function; and that if a comment is needed to explain a name then you should turn the comment into the name. So for all those reasons I'd go with activations rather than inputs. (Yes `activation` in an NN usually refers to _after_ the activation function, not before).

But it's not my code, so allow me to defer to your standards.

**Comment by mattjj** [comment]
There's no mutation here. It's just rebinding the name `input` locally.

**Comment by chrisfcarroll** [comment]
Then the line `inputs = jnp.tanh(outputs)` must be redundant and can be removed?

**Comment by chrisfcarroll** [comment]
Sorry, please accept my apologies. My misreading, of course. I read and failed to see the loop.

Yes, I can see how the name inputs is correct. 

So to your question, “what is least likely to trigger somebody else thinking it's a typo”, my best and serious suggestion is still either (a) `activations` or (b) add an explanatory variable called either `activations` or `current`

```
def predict(params, inputs):
  activations=inputs
  for W, b in params:
    outputs = jnp.dot(activations, W) + b
    activations = jnp.tanh(outputs)
  return outputs
```

**Comment by chrisfcarroll** [comment]
Matt, Jake : I'm really sorry I turned this into a poor experience for you both when you were both trying hard to be positive. Thankyou for your patience. Next time I'll aim to read more carefully and react more slowly. Thanks, Chris.

**Pull request closed without merging**
