### PR TITLE
chore(ci) : setup dependabot for pip and github-actions

### PR DESCRIPTION
**Pull request by mmorel-35**
Hi! This allows you to receive pr to keep your dependencies up-to-date.
See https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

### CODE REVIEW

**Comment by jakevdp** [comment]
I think this is probably not a good fit for JAX, because all contributions require a CLA to be signed by the commit author: because of that, I don't think dependabot-authored commits will be able to be merged.

**Comment by mmorel-35** [comment]
Take a look at go-github, here https://github.com/google/go-github/pull/2053, is there a different configuration on Jax?

**Comment by jakevdp** [comment]
I think that's the same CLA configuration, so it might work after all.

One question, since I couldn't find any info in the docs: for pip mode, what files does dependabot look at to find outdated dependencies? Does it parse `setup.py`?

**Comment by mmorel-35** [comment]
When I go in Insight > Dependency  graph, it is able to work with "setup.py, docs/requirements.txt, and build/test-requirements.txt"  (concerning JAX)

**Comment by jakevdp** [comment]
Sounds good - let's give it a try!

**Pull request merged**
