### PR TITLE
Propagate raw __name__ of functions wrapped by jit and sharded_jit.

### PR DESCRIPTION
**Pull request by BuddenD**

### CODE REVIEW

**Comment by mattjj** [comment]
Thanks! Can you make the analogous update to `pmap` in api.py as you did to `jit`?

**Comment by BuddenD** [comment]
Done

**Comment by jekbradbury** [comment]
Can you remind me (and also note for posterity) what your motivation was behind dropping the name wrappers? I remember it seemed sensible in context.

**Review by jekbradbury — APPROVED** [review]

**Review by mattjj — APPROVED** [review]
LGTM!

**Comment by mattjj** [comment]
@jekbradbury I'm not sure if the motivation was noble or not, but in any case this seems like kinda weird string munging to do on our parts.

**Pull request merged**
