### PR TITLE
Combine GPU multiprocess tests

### PR DESCRIPTION
**Pull request by sudhakarsingh27**
1. Single file `multiprocess_gpu_test.py` for all gpu distributed tests.
2. Use `pytest --forked ...` to launch each test in a separate subprocess
to workaround conflicting multiple `jax.distributed.init` within a single
file/process.

### CODE REVIEW

**Review by yashk2810 — APPROVED** [review]

**Comment by sudhakarsingh27** [comment]
@yashk2810 curious if there's anything I could do on my side to help?

**Comment by yashk2810** [comment]
Looks like the CPU tests are failing. It says that it can't find the target. You need to change this too: https://github.com/google/jax/blob/main/tests/BUILD#L102

I couldn't pull it in because of failing tests.

**Comment by sudhakarsingh27** [comment]
Ah right, makes sense. Let me fix that

**Comment by sudhakarsingh27** [comment]
It looks like there's a merge conflict too. Should I rebase and raise another PR?

**Comment by sudhakarsingh27** [comment]
Trying again in https://github.com/google/jax/pull/12113

**Comment by yashk2810** [comment]
Just FYI: You don't have to create a new PR whenever there is a merge conflict. You can just rebase this PR on top of main.

**Comment by sudhakarsingh27** [comment]
Thanks! I'll keep that in mind the next time

**Pull request closed without merging**
