### PR TITLE
Adds font fallbacks

### PR DESCRIPTION
**Pull request by barnesjoseph**

### CODE REVIEW

**Review by jakevdp — APPROVED** [review]
Thanks!

**Comment by barnesjoseph** [comment]
Thanks for the approval, I'm not authorized to merge, so feel free to merge when ready.

**Comment by jakevdp** [comment]
Thanks! Confirming that on Linux this now falls back to Roboto for the title text.

Is there anything we can do to ensure that Google Sans is loaded in this case?

**Comment by barnesjoseph** [comment]
I think the only thing we can do to guarantee Google Sans would be to add the font via the template or in the HTML somehow.

**Pull request merged**
