### PR TITLE
Implement cross product and test cases

### PR DESCRIPTION
**Pull request by kroq-gar78**
Cross product isn't implemented, as per #70. This commit includes test cases.

### CODE REVIEW

**Comment by mattjj** [comment]
Thanks for this contribution!

It looks like the tests that failed had 64-bit mode enabled. Some of them may stem from expressions like `zeros(a_shape[:-1])`, which will create float zeros arrays. You might want to use `zeros_like`, or else set the dtype manually.

I'm not sure about the test that failed based on accuracy, but maybe its tolerance just needs to be loosened.

**Comment by kroq-gar78** [comment]
Got it, thanks!

It looks like that test is failing on accuracy again, though.

**Comment by mattjj** [comment]
Oh, and that test is unrelated to this code change, right?

Looks like it's borderline enough that it's failing stochastically. I can take care of that; in this PR, can you just comment out that one test and leave a `# TODO(mattjj): loosen tolerance on this test`?

**Comment by kroq-gar78** [comment]
Correct, I don't change anything related to that test case. I'll comment it out and add that note. It's at `tests/lax_scipy_test.py:71`.

**Review by mattjj — APPROVED** [review]
Thanks so much for this clean and well-tested code!

**Comment by kroq-gar78** [comment]
No worries, thanks for being so responsive!

**Pull request merged**
