### PR TITLE
Rocm dockerfile and test updates

### PR DESCRIPTION
**Pull request by rahulbatra85**
Dockerfile updates
Test script updates

### CODE REVIEW

**Comment by rahulbatra85** [comment]
@hawkinsp Please review. Thanks!

**Comment by rahulbatra85** [comment]
@hawkinsp @jakevdp  @yashk2810  Any feedback on this? Can we please merge this? Thanks!

**Comment by rahulbatra85** [comment]
@skye @hawkinsp 
Can we please merge this? Thanks!

**Review by hawkinsp — APPROVED** [review]

**Comment by rahulbatra85** [comment]
@hawkinsp  Should be fixed now. Please review. Thanks!

**Comment by hawkinsp** [comment]
New lint failure that needs fixing.

**Comment by rahulbatra85** [comment]
Done as part of this
https://github.com/google/jax/pull/22600

**Pull request closed without merging**
