### PR TITLE
Add Hilbert matrix to jax.scipy.linalg

### PR DESCRIPTION
**Pull request by rajasekharporeddy**
This PR implements the hilbert function which returns a Hilbert matrix of order `n`.

### CODE REVIEW

**Review by jakevdp — APPROVED** [review]
Looks good!

**Comment by jakevdp** [comment]
Thanks for the update - we'll need to squash the commits again. This involves rewriting your git history and force-pushing to your upstream branch. I typically do it with something like this:
```
$ git remote -v  # note that upstream points to the main repo and origin to your fork
origin	git@github.com:jakevdp/jax.git
upstream	git@github.com:google/jax.git
$ git branch  # confirm you're on your special_matrices branch
$ git rebase main  # rebase your commits on the current main branch
$ git reset --soft main  # undo all the commits after main
$ git commit -m "Add Hilbert matrix to jax.scipy.linalg" # re-add a single commit
$ git push origin +special_matrices  # force-push to the origin, where it will be reflected in this PR
```

**Comment by rajasekharporeddy** [comment]
Thank you @jakevdp. Squashed all the commits into single commit.

**Review by jakevdp — APPROVED** [review]

**Comment by jakevdp** [comment]
It looks like you still have lint errors. It will be faster if you iterate locally rather than relying on pushing changes and testing via github CI. See the `pre-commit` instructions here: https://jax.readthedocs.io/en/latest/contributing.html#contributing-code-using-pull-requests

**Pull request merged**
