### PR TITLE
Add sp.multigammaln, sp.entr

### PR DESCRIPTION
**Pull request by fehiepsi**
This PR adds some utilities from scipy.special which I found them helpful.

### CODE REVIEW

**Comment by mattjj** [comment]
Thanks for this!

**Comment by hawkinsp** [comment]
Just a heads up: the gradient test for `entr` was yielding NaNs so I disabled it (https://github.com/google/jax/commit/f8fa1a60f4611a5fefe0cea690841644717f9195)

(You might need to use the environment variable `JAX_NUM_GENERATED_CASES=100` or similar to see the test failure.)

**Comment by fehiepsi** [comment]
Hi @hawkinsp , thanks for the heads up. The flag `JAX_NUM_GENERATED_CASES=100` is pretty cool!

It looks like that the actual grad is correct but the expected numerical grad is `nan`. The reason is we are getting `(-inf) - (-inf) = nan` at [numerical jvp test](https://github.com/google/jax/blob/master/jax/test_util.py#L126) when the input is less than 0. I guess it is fine to disable the grad test as you did. :)

**Comment by mattjj** [comment]
JAX's parameterized test style means it has a _lot_ of test cases that it randomly subsamples, so if you set `JAX_NUM_GENERATED_CASES` to a big number you'd better be ready to run tests for a while ;) We have Travis CI run with `JAX_NUM_GENERATED_CASES=25`, but internally we run with `JAX_NUM_GENERATED_CASES=100` and against Python 2 and 3 as well as on all CPU / GPU / TPU backends (all parallelized over many machines!).

(Actually if you count [generated_fun_test.py](https://github.com/google/jax/blob/master/tests/generated_fun_test.py), which generates random programs, JAX will generate an unbounded number of tests!)

**Comment by fehiepsi** [comment]
Thanks for explaining, @mattjj !

**Pull request merged**
