### PR TITLE
Create lax.polygamma with native HLO lowering

### PR DESCRIPTION
**Pull request by jakevdp**
~Trying this out... not sure whether `polygamma` is implemented on all backends.~ Tests pass on CPU, GPU & TPU... let's ship it!

Inspired by #16076

### CODE REVIEW

**Comment by NeilGirdhar** [comment]
I guess the same thing would need to be added for `gamma_grad` primitive?

**Comment by jakevdp** [comment]
No, this won't solve #16076. The issue there is that there is no autodiff rule for `gamma_grad`.

**Comment by NeilGirdhar** [comment]
Okay, but it's possible to write one?  Should I invest some time in doing what you did for the `gamma_grad` primitive?

**Comment by jakevdp** [comment]
See https://github.com/google/jax/issues/16076#issuecomment-1681273130 – let's keep discussions of #16076 in #16076

**Review by skye — APPROVED** [review]
I'm not sure I'm the best person to review (this is my first encounter with polygamma) but LGTM!!

**Pull request merged**
