### PR TITLE
Bump minimum jaxlib version to 0.4.10.

### PR DESCRIPTION
**Pull request by hawkinsp**
The minimum xla_extension_version is 153, and mlir_api_version is 49.

### CODE REVIEW

**Comment by yashk2810** [comment]
What's the reason to bump?

**Comment by hawkinsp** [comment]
> What's the reason to bump?

The reason is that we think it might make https://github.com/google/jax/pull/16145 work, which is needed to resolve a JAX/plugin versioning problem.

**Comment by yashk2810** [comment]
Ok, is there a way to test before we do this? 

Note that I want to bump after the next release too. We can bump now too but you should verify if it actually fixes the problem

**Review by yashk2810 — APPROVED** [review]

**Comment by yashk2810** [comment]
https://github.com/google/jax/pull/16219 should subsume this PR

**Pull request closed without merging**
