### PR TITLE
for custom_jvp/vjp nondiff_argnums, call stop_gradient

### LINKED ISSUE #2784: Forward-mode differentiation rule for 'custom_lin' not implemented
Running this code produces the above error.

```
@partial(jax.custom_vjp, nondiff_argnums=(0, 1))
def _clip_gradient(lo, hi, x):
  return x  # identity function

def clip_gradient_fwd(lo, hi, x):
    # return x, None
    return x, (hi, ) 

def clip_gradient_bwd(lo, hi, _, g):
    return (np.clip(g, lo, hi),)

_clip_gradient.defvjp(clip_gradient_fwd, clip_gradient_bwd)

def clip_gradient(x):
    lo = -1
    hi = x + 1  # causes things to break
    return _clip_gradient(lo, hi, x)

print(jax.grad(clip_gradient)(1.))
```

Replacing the residual with `None` (see commented out line in `clip_gradient_fwd`) makes the output

```
Traced<ConcreteArray(1.0)>with<JVPTrace(level=1/0)>
  with primal = DeviceArray(1., dtype=float32)
       tangent = Traced<ShapedArray(float32[]):JaxprTrace(level=0/0)>
```

I was also able to get a mismatched tracer levels  error on a more complex example.

To my understanding setting `hi = x + 1` is the issue as it creates a trace of `hi` with `x`.

This example may seem a bit contrived, but I originally came across this trying to set an initial step size for `odeint` (see #2604).

IIUC we want to make concrete all `JVPTracer` instances that are in static args [here](https://github.com/google/jax/blob/master/jax/custom_derivatives.py#L441).

### PR DESCRIPTION
**Pull request by mattjj**
fixes #2784

### CODE REVIEW

**Comment by mattjj** [comment]
Travis didn't seem interested in running tests, but internal tests pass!

**Comment by jekbradbury** [comment]
Do we maybe want to expose this `stop_gradient` (with pytree support etc.) as `jax.stop_gradient` or even `lax.stop_gradient`?

**Comment by mattjj** [comment]
I think [`jax.lax.stop_gradient` handles pytrees](https://github.com/google/jax/blob/3ee8a7be1f5fabc81473a8b6125b2531dd093c48/jax/lax/lax.py#L1306).

**Comment by mattjj** [comment]
The different logic here is "apply `stop_gradient` to all leaves that are Tracers, leave others untouched."

**Pull request merged**
