### PR TITLE
Implement np.average

### PR DESCRIPTION
**Pull request by kroq-gar78**
Working towards #70.

### CODE REVIEW

**Comment by kroq-gar78** [comment]
Hah, looks like @sharadmv had the same idea in #686! I'll have to look into what's different, but let me know if I should close this PR in the meantime.

**Comment by sharadmv** [comment]
That's hilarious! I think you actually cover a few more cases than I do, so I think I'll close mine.

**Review by mattjj — APPROVED** [review]
Really nice! Great use of utility functions, and super thorough coverage of cases. Great tests too.

**Comment by mattjj** [comment]
Thanks @kroq-gar78 for the contribution! And thanks @sharadmv for your work too, and for sorting out which to merge.

**Pull request merged**
