### PR TITLE
Add np.triu_indices_from numpy function

### PR DESCRIPTION
**Pull request by ashridh**
Part of #70

### CODE REVIEW

**Comment by ayush-1506** [comment]
Uh, the failure looks unrelated to my changes.

**Comment by gnecula** [comment]
You are right that the failure was not due to your change. I have restarted the testing.

**Comment by ayush-1506** [comment]
Ok great, tests seem to pass now. Would love a review.

**Comment by jakevdp** [comment]
This looks good. The remaining missing piece is a test of the new functionality – you can use the other tests in ``tests/lax_numpy_test.py`` as a template. Please let me know if you have questions!

**Comment by ayush-1506** [comment]
@jakevdp Yep. Also, I couldn't find tests for `triu_indices`, `tril_indices` and other similar functions that have already been implemented. Perhaps we missed adding tests for these?

**Comment by jakevdp** [comment]
Yes, if you're willing to add tests for any untested functions as part of this PR, that would be much appreciated!

**Comment by ayush-1506** [comment]
@jakevdp Cool, I've added tests for `triu_indices`, `tril_indices` and `triu_indices_from`.

**Comment by jakevdp** [comment]
Thanks! Rather than directly comparing jax and numpy outputs, please use the `self._CheckAgainstNumpy` function as in the other tests in the file: this does further checks around dtypes & other considerations.

In this case we can skip the ``self._CompileAndCheck`` function, because these particular functions are implemented in terms of the standard numpy functions and will not compile.

**Comment by ayush-1506** [comment]
@jakevdp Thanks, I figured it might be easier to use `np.testing.assert_equal`, but I've replaced it now.

**Review by jakevdp — APPROVED** [review]

**Comment by ayush-1506** [comment]
@jakevdp Thanks again! Would be great if you could also check the recent additions in the checklist in #70 to avoid confusion later on.

**Pull request merged**
