### PR TITLE
Remove extraneous information from wrapped docstrings

### PR DESCRIPTION
**Pull request by jakevdp**
This is an overhaul of our numpy docstring rewriting code.

The main issue with the current approach is that we include the full numpy docstring in the docstring of wrapped functions; via sphinx autodoc this gets propagated to our HTML documentation. This is problematic because the numpy examples don't always work with their associated JAX functions; for example the [`jnp.sum` docs](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.sum.html) include this set of examples:
```python
>>> np.sum([0.5, 1.5])
2.0
>>> np.sum([0.5, 0.7, 0.2, 1.5], dtype=np.int32)
1
>>> np.sum([[0, 1], [0, 5]])
6
>>> np.sum([[0, 1], [0, 5]], axis=0)
array([0, 6])
>>> np.sum([[0, 1], [0, 5]], axis=1)
array([1, 5])
>>> np.sum([[0, 1], [np.nan, 5]], where=[False, True], axis=1)
array([1., 5.])
```
All of these error with `jnp.sum()`, because lists are not valid inputs to JAX reductions. This has caused some confusion for users in the past (e.g. #4199, #5706)

The fix here is to remove all sections except the opening summary, `Parameters`, `Returns`, and `References`. This may remove relevant information from some docstrings, but I think that's preferable to having incorrect information in the documentation.

Note that the sphinx documentation build provides a good set of tests that validate the correctness of the rewritten docstrings: if any are misformatted, the documentation build will fail.

Related to #5539

### CODE REVIEW

**Comment by jakevdp** [comment]
This is failing in Python 3.6 because the ability to split a string on an empty regex was added in Python 3.7: https://docs.python.org/3/library/re.html#re.split

**Review by mattjj — APPROVED** [review]
Wow, phenomenal! This is a great idea.

**Comment by mattjj** [comment]
Should we prune `out` from `Parameters`? And/or mention in our docstring prefix that not all NumPy features are supported, and give `out` as an example?

**Comment by jakevdp** [comment]
> Should we prune out from Parameters?

That would happen automatically, except we include `out` in the signature of JAX reductions (erroring if it's anything other than `None`). If we left it out of the signature, then the current approach would leave it out of the parameter list as well.

**Pull request merged**
