### PR TITLE
Restrict JAX2TF tests to cases supported by TF2 ops.

### PR DESCRIPTION
**Pull request by cheshire**
The test is currently running on XLA devices, which support more types.
With deprecation and removal of XLA devices, it will run on "stock" TF
device, which does not support fp16 for some operations.

### CODE REVIEW

**Comment by cheshire** [comment]
Presubmits show failure while installing dependencies (?)

**Comment by cheshire** [comment]
@gnecula

**Comment by cheshire** [comment]
@hawkinsp

**Comment by hawkinsp** [comment]
I'll let @gnecula review this one. The presubmit problem is a known issue that probably is related to something in our CI and not your change. I restarted the jobs, which may help.

**Comment by gnecula** [comment]
LGTM, Thanks!

**Pull request merged**
