### PR TITLE
Add jax.ops.index_min/max.

### PR DESCRIPTION
**Pull request by jlebar**
These are analogous to index_add.

### CODE REVIEW

**Comment by jlebar** [comment]
cc @hawkinsp.  Note that I have no idea what I'm doing.

**Review by mattjj — APPROVED** [review]
Beautiful!

**Comment by jlebar** [comment]
This included an accidental revert of jaxlib due to my apparently suboptimal google3 -> git workflow, https://github.com/google/jax/pull/904/commits/d5ba04b79e37c6f5dbb9df58d701b19b9523770a#diff-e512abedc01637b70a5b9f6781cc964e.  I will revert this.

Also, did I actually get away with this IIDFE (immediately invoked dict of functions expression) I invented at https://github.com/google/jax/pull/904/commits/d5ba04b79e37c6f5dbb9df58d701b19b9523770a#diff-187c87257f2bf51832ed8bd64c35ea85R734??  :D

**Comment by jlebar** [comment]
Fixing this in https://github.com/google/jax/pull/906.

**Comment by jekbradbury** [comment]
> Also, did I actually get away with this IIDFE (immediately invoked dict of functions expression) I invented at [d5ba04b#diff-187c87257f2bf51832ed8bd64c35ea85R734](https://github.com/google/jax/commit/d5ba04b79e37c6f5dbb9df58d701b19b9523770a#diff-187c87257f2bf51832ed8bd64c35ea85R734)?? :D

Python without a style guide is a hell of a drug, but I'm a fan

**Pull request merged**
