### PR TITLE
Fix hessian logic

### LINKED ISSUE #9969: jax.hessian uses positional argument `holomorphic` where it should be `has_aux`
EDIT: Fixed a Typo.

Hi, this is a bit of a minor issue, but the jax source implementation of `hessian` has a slight mixup (or misses) in the function arguments. It uses `holomorphic` in place of `has_aux`, which is slightly confusing.

As shown below (see https://jax.readthedocs.io/en/latest/_modules/jax/_src/api.html):
```python
def hessian(fun: Callable, argnums: Union[int, Sequence[int]] = 0,
            holomorphic: bool = False) -> Callable:
  """Doc ... """
  return jacfwd(jacrev(fun, argnums, holomorphic), argnums, holomorphic)
```

However, the argument `holomorphic` is used in the positional arg of `has_aux` for both jacfwd and jacrev:
```python
def jacfwd(fun: Callable, argnums: Union[int, Sequence[int]] = 0,
           has_aux: bool = False, holomorphic: bool = False) -> Callable:
    ...
```

Current behaviour:
```python
import jax


def f(x):
    return jax.numpy.sin(x)


def f_aux(x):
    return f(x), x


print(jax.hessian(f)(10.))
# 0.5440211
print(jax.hessian(f_aux, holomorphic=True)(10.))
# (DeviceArray(0.5440211, dtype=float32, weak_type=True), 10.0)
print(jax.hessian(f, holomorphic=True)(10.))
# TypeError: expected function with aux output to return a two-element tuple, but got type ...
```

Should be:
```python
import jax


def f(x):
    return jax.numpy.sin(x)


def f_aux(x):
    return f(x), x


print(jax.hessian(f)(10.))
# 0.5440211
print(jax.hessian(f_aux, has_aux=True)(10.))
# (DeviceArray(0.5440211, dtype=float32, weak_type=True), 10.0)
print(jax.hessian(f, has_aux=True)(10.))
# TypeError: expected function with aux output to return a two-element tuple, but got type ...
```

Fix:
```python
def hessian(
        fun: Callable,
        argnums: Union[int, Sequence[int]] = 0,
        has_aux: bool = False,
        holomorphic: bool = False
) -> Callable:
    """Doc ..."""
    return jacrev(jacfwd(fun, argnums, has_aux=has_aux, holomorphic=holomorphic),
                  argnums, has_aux=has_aux, holomorphic=holomorphic)
```

### PR DESCRIPTION
**Pull request by YouJiacheng**
Fix #9969 
Maybe a regression test should be added.

### CODE REVIEW

**Review by jakevdp — COMMENTED** [review]
Looks good – are you interested in adding a regression test as part of this PR?

**Comment by YouJiacheng** [comment]
Okay. I add a regression test. (not sure it works)

**Review by jakevdp — APPROVED** [review]
Looks great, thanks!

**Comment by YouJiacheng** [comment]
Ok, holomorphic need a complex inputs, I will fix it

**Comment by YouJiacheng** [comment]
Done.

**Pull request merged**
