### PR TITLE
Use XLA AllGather op for GPU (when supported).

### PR DESCRIPTION
**Pull request by chr1sj0nes**
My benchmarks suggest a speed-up of ~2-2.5x for larger inputs.

### CODE REVIEW

**Comment by mattjj** [comment]
Woohoo, awesome!

How come the tests need to be skipped? (Sorry if this is obvious.)

**Comment by chr1sj0nes** [comment]
Same issue as the `all_to_all` tests - the fallback implementation calls `axis_index`, which causes an error when omni-staging is disabled. I don't exactly understand why but, as discussed internally, probably not worth spending the time to investigate with omni-staging becoming mandatory in the near future.

**Comment by mattjj** [comment]
We had an idea (copying here from chat): we can switch on `config.omnistaging_enabled` in the `all_gather` function, and basically call into the new primitive-based code only if omnistaging is enabled. That way we don't have to disable any tests (until we get rid of disable_omnistaging entirely).

**Comment by chr1sj0nes** [comment]
I've changed it so we fall back to the old behaviour when omni-staging is disabled and re-enabled the tests.

**Review by mattjj — APPROVED** [review]
Awesome work, and a welcome speedup!

**Pull request merged**
