### PR TITLE
Update jax.scipy.special.ndtri to return NaN for the values outside of the range [0, 1]

### LINKED ISSUE #20430: `jax.scipy.special.ndtri` edge case behavior
### Description

`jax.scipy.special.ndtri` returns positive infinity when the argument exceeds `1.0` and negative infinity when the argument is less than `0.0`.

```python3
from jax import numpy as jnp
from jax.scipy.special import ndtri
ndtri(jnp.asarray(-1.))  # Array(-inf, dtype=float32)
ndtri(jnp.asarray(2.))  # Array(inf, dtype=float32)
```

It seems that it would be more appropriate to return NaN in these cases (as `scipy.special.ndtri`, `torch.special.ndtri`, etc. do). 

This came up when adding support for JAX as an array API backend in SciPy. For more information, please see scipy/scipy#20085.

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.23
jaxlib: 0.4.23
numpy:  1.25.2
python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
jax.devices (1 total, 1 local): [cuda(id=0)]
process_count: 1

$ nvidia-smi
Tue Mar 26 04:33:34 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   70C    P0              32W /  70W |  11447MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by rajasekharporeddy**
Fixes #20430

### CODE REVIEW

**Review by pearu — CHANGES_REQUESTED** [review]
Thanks for the PR!

See comment:
https://github.com/google/jax/blob/main/jax/_src/scipy/special.py#L539-L541
that suggest there exists multiple attempts to avoid nan-s in ndtri output (just after the comment and at the end of this function) while one attempt ought to be enough.

That said, the current behavior for p < 0 and p > 1 cases can be changed be updating the existing code without introducing another `jnp.where` instruction. I suggest applying the following patch:
```
$ git diff
diff --git a/jax/_src/scipy/special.py b/jax/_src/scipy/special.py
index d4aced143..bee70cc63 100644
--- a/jax/_src/scipy/special.py
+++ b/jax/_src/scipy/special.py
@@ -540,7 +540,7 @@ def _ndtri(p: ArrayLike) -> Array:
   # later on. The result from the computation when p == 0 is not used so any
   # number that doesn't result in NaNs is fine.
   sanitized_mcp = jnp.where(
-      maybe_complement_p <= dtype(0.),
+      maybe_complement_p == dtype(0.),
       jnp.full(shape, dtype(0.5)),
       maybe_complement_p)
 
@@ -571,9 +571,9 @@ def _ndtri(p: ArrayLike) -> Array:
 
   x = jnp.where(p > dtype(1. - np.exp(-2.)), x, -x)
   infinity = jnp.full(shape, dtype(np.inf))
-  x_nan_replaced = jnp.where(
-      p <= dtype(0.0), -infinity, jnp.where(p >= dtype(1.0), infinity, x))
-  return x_nan_replaced
+  x_fix_boundaries = jnp.where(
+      p == dtype(0.0), -infinity, jnp.where(p == dtype(1.0), infinity, x))
+  return x_fix_boundaries
 
 
 @partial(custom_derivatives.custom_jvp, nondiff_argnums=(1,))
```

**Comment by rajasekharporeddy** [comment]
Hi @pearu 

Thanks for the review. I have made the suggested changes.

**Review by pearu — CHANGES_REQUESTED** [review]
The changes look good. Thanks, @rajasekharporeddy!

Could you also add a new test to tests/lax_scipy_special_functions_test.py that covers the ndtri input values such as negative, zero, one, and larger than one as well? Test against scipy.special.ndtri at these values ought to be fine.

**Comment by rajasekharporeddy** [comment]
Hi @pearu 

Thanks! Added the test as suggested.

**Review by pearu — APPROVED** [review]
LGTM! Thanks, @rajasekharporeddy!

**Comment by rajasekharporeddy** [comment]
Closed this PR and opened a new PR #20528 since this PR got conflicts with other branches. Sorry for the inconvenience.

**Pull request closed without merging**
