### PR TITLE
Implement np.cbrt

### PR DESCRIPTION
**Pull request by Squadrick**
Adding np.cbrt listed in #70

### CODE REVIEW

**Comment by mattjj** [comment]
The test breakage looks like it's on our side. Will fix!

**Comment by mattjj** [comment]
It's because we moved the `lax._safe_mul` name so that it's no longer available. We could make that name publicly available outside `lax`, but that made me wonder if you had a particular reason for calling `lax._safe_mul` here rather than `lax.mul`. Is there a reason not to use `lax.mul`?

**Comment by Squadrick** [comment]
If `x` is 0, then `lax.div(x, abs_x)` is `nan`. Using `lax.mul` will return `nan` as well, but `lax._safe_mul` will return 0.

**Comment by mattjj** [comment]
Ah, but that expression is just to get the sign of `x`, right? Instead of dividing, can you use `lax.sign` / `np.sign` there instead? Maybe something like `sign(x) * power(abs_x, _constant_like(x, 1. / 3.))` ?

**Comment by Squadrick** [comment]
Yup, you're right, that's far nicer. Didn't know `lax.sign` existed.

**Review by mattjj — APPROVED** [review]
LGTM! Thanks for this contribution. Will merge when the Travis tests finish.

**Comment by mattjj** [comment]
Thanks again!

**Pull request merged**
