### PR TITLE
Allow Var to be a key in a JAX tree

### PR DESCRIPTION
**Pull request by tomhennigan**

### CODE REVIEW

**Comment by gnecula** [comment]
Is the main goal to be able to use Var in a pytree as inputs to transformed functions? How do you envision this being used?

**Comment by tomhennigan** [comment]
I'm prototyping something that requires evaluating subsets of eqns in jaxprs. It is quite convenient to model this as functions from `f(x: Mapping[core.Var, Value]) -> Mapping[core.Var, Value]` but I can't trace the resulting `f` (e.g. for gradients or jit) since `core.Var` is not orderable.

I can currently work around this by passing `Sequence[Tuple[core.Var, Value]]` but that is more boilerplatey.

**Comment by tomhennigan** [comment]
Actually the workaround I mentioned (using `Seq[Tupl[..]]`) doesn't work when I `jit` :) I'll need to make something that wraps `core.Var` and adds compare by count for now.

**Comment by mattjj** [comment]
Thanks for explaining! We're happy to help with prototypes. Our dream is for JAX to make it easy to stand up new prototypes and experiments, not just for ML but for systems and languages too.

For prototypes it might also be feasible to rely on things like monkey-patching JAX. But in this case the change is lightweight enough that there's little reason not to merge it speculatively.

Do let us know if you stop needing this, though!

**Comment by gnecula** [comment]
Somehow I find it strange that something as internal as Var needs to be used in the API of user functions. Would an alternative be to define your functions as taking Sequence[Value] where the order is based on the ordering of the jaxpr.invars? This is what we do for the traceable evaluators of jaxpr.

**Pull request merged**
