### PR TITLE
Cleaned some test warnings.

### PR DESCRIPTION
**Pull request by gnecula**
Specifically:
* lax_control_flow_test.py:...: DeprecationWarning: invalid escape sequence \(
* Deprecated assertRaisesRegexp, replace with assertRaisesRegex

### CODE REVIEW

**Comment by gnecula** [comment]
There are also lots of warnings about:
UserWarning: Explicitly requested dtype <class 'numpy.float64'> requested in array is not available, and will be truncated to dtype float32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.

Also for int64, float64.

It seems that np.array([1]).dtype = int64 (on my Mac laptop). Should we clean the tests to use np.array([1], dtype=np.int32)?

**Comment by mattjj** [comment]
I often ignore warnings by running `pytest -n auto tests -W ignore`. We could clean up the tests not to generate any warnings, but I'm not sure how much work that will take. We might also want to wait until the dust settles on @hawkinsp 's dtype-handling changes.

**Review by mattjj — APPROVED** [review]
Nice!

**Comment by mattjj** [comment]
I often ignore warnings by running `pytest -n auto tests -W ignore`. We could clean up the tests not to generate any warnings, but I'm not sure how much work that will take. We might also want to wait until the dust settles on @hawkinsp 's dtype-handling changes.

**Pull request merged**
