### PR TITLE
Defer to unrecognized types in arithmetic

### PR DESCRIPTION
**Pull request by shoyer**
This is useful for building higher level array libraries around JAX, because it
makes it possible to override operations like `jax_array + other`.

I think I covered all the array types that JAX should be able to handle:
- Python builtin numbers int, float and complex
- NumPy scalars and arrays
- JAX array types and tracers

Did I miss anything? Maybe bfloat16 scalars?

### CODE REVIEW

**Comment by mattjj** [comment]
Do you have a use case for this right now?

Since we're already monkey-patching objects here, it occurs to me that `_defer_to_unrecognized_arg` could live in the downstream higher level array library itself. How should we think about the tradeoffs here? If this feature is only ever used in one downstream library, would it make sense to keep this logic in that library, rather than in JAX? Do we have a sense for how often this feature may be needed (e.g. from experience with other libraries in the NumPy ecosystem)?

**Comment by shoyer** [comment]
> Do you have a use case for this right now?

Yes :)

We wrote a little custom array object that adds metadata to JAX arrays. Currently, operations like `custom_array + jax_array` work fine, but not `jax_array + custom_array`.

> Since we're already monkey-patching objects here, it occurs to me that `_defer_to_unrecognized_arg` could live in the downstream higher level array library itself. How should we think about the tradeoffs here? If this feature is only ever used in one downstream library, would it make sense to keep this logic in that library, rather than in JAX?

I don't think we could easily put this into a downstream library, unless we want to encourage downstream libraries monkey-patching JAX (which could lead to conflicts).

> Do we have a sense for how often this feature may be needed (e.g. from experience with other libraries in the NumPy ecosystem)?

Basically every use-case for NumPy duck arrays or subclasses needs to override arithmetic like this. Example use cases from NumPy that could also make sense for JAX:
- dataframe libraries, like pandas
- arrays with units, like pint
- arrays with builtin uncertainty
- arrays with labeled dimensions, like xarray
- domain specific libraries that override arithmetic on special objects, like Qutip (quantum physics) or Iris (climate data)

We probably wouldn't want to build this functionality in JAX proper, but deferring to unrecognized types is useful for enabling these sorts of higher level libraries.

**Comment by shoyer** [comment]
This is also something you see in non-array libraries that want arithmetic or comparisons to be extensible, e.g., in Python's own `datetime.datetime` class:
https://github.com/python/cpython/blob/e02ab59fdffa0bb841182c30ef1355c89578d945/Lib/datetime.py#L2070

There's also a (google internal) Python tip of the week about this: go/pytotw/009

**Comment by shoyer** [comment]
note: tests are failing on Python 2, but I'm hoping we can drop Python 2 support before we merge this :)

**Comment by shoyer** [comment]
Tests are passing, now that we no longer support Python 2!

It would be great to get another look here :)

**Review by mattjj — APPROVED** [review]
Does this add any overhead? Worth a quick micro-benchmark?

Otherwise LGTM. I guess it adds one more stack frame, but might be worthwhile.

**Comment by shoyer** [comment]
My microbenchmark shows `x + 1` on a trivial array `x` weighing in at ~150 µs, even without bothering to compute the result. The extra type checking and function call weights in at perhaps ~300 ns, so it's entirely lost in the noise.

(We should definitely improve the situation here -- NumPy computes `x + 1` in less than 1 µs -- but I suspect it would be pretty challenging to do short of a rewrite in C++.)

**Comment by mattjj** [comment]
Thanks for checking! I agree 300ns is noise.

I measure ~100us for this:

```
x = device_put(1)
timeit x + 1
```

and ~50us for this:

```
timeit x + x
```

I think staying in pure Python we can probably bring that down a lot. Especially on CPU, we can avoid copies of Python integers and even ndarrays (like NumPy does) IIUC. That's for another day though :)

**Comment by shoyer** [comment]
> I think staying in pure Python we can probably bring that down a lot. Especially on CPU, we can avoid copies of Python integers and even ndarrays (like NumPy does) IIUC. That's for another day though :)

Absolutely, though I suspect 10 us a more realistic target for us than 1 us :)

**Comment by shoyer** [comment]
thanks for the review!

**Pull request merged**
