### PR TITLE
DOC: ensure that _wraps() generates correct links to wrapped functions

### LINKED ISSUE #11492: jax.numpy.reciprocal/remainder docstring
In https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.reciprocal.html#jax.numpy.reciprocal, the link to the numpy implementation actually self-references the jax version.

Instead, it should point to https://numpy.org/doc/stable/reference/generated/numpy.reciprocal.html

The same applies for remainder: https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.remainder.html#jax.numpy.remainder

### PR DESCRIPTION
**Pull request by jakevdp**
The issue here is that numpy ufuncs do not have a `__module__` attribute, so we must pass the correct module explicitly.

Fixes #11492

### CODE REVIEW

**Review by yashk2810 — APPROVED** [review]

**Comment by ilemhadri** [comment]
Now there is no numpy hyperlink anymore?

e.g. https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.reciprocal.html#jax.numpy.reciprocal, as of July 22nd, 10:31AM UTC.

**Comment by jakevdp** [comment]
Yeah, I noticed that. I'm not sure there's anything we can do: the intersphinx reference is generated correctly, but the links don't work. Poking around the numpy documentation, I see the same behavior there for sphinx references to ufuncs (e.g. https://numpy.org/neps/nep-0013-ufunc-overrides.html#list-of-operators-and-numpy-ufuncs)

I think it's either a sphinx bug or a numpy bug of some sort, perhaps related to the fact that ufuncs don't define `__module__`. I don't have plans to look into this further, but if numpy/sphinx ever fixes the issue then the fix should propagate to the JAX documentation.

**Comment by ilemhadri** [comment]
Very curious - on some links [like this one](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.reciprocal.html) there is no hyperlink at all, whereas on others [like this one](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.linalg.matrix_rank.html), there is!

**Comment by jakevdp** [comment]
I believe these links are missing because there's not `.. module :: numpy` declaration at the top of https://github.com/numpy/numpy/blob/main/doc/source/reference/routines.math.rst

**Comment by ilemhadri** [comment]
Created a pull request to see if it would be possible to change the numpy `routines.math.rst` accordingly: https://github.com/numpy/numpy/pull/22162

**Comment by ilemhadri** [comment]
the discussion in https://github.com/numpy/numpy/pull/22162 is insightful!

rossbar (and myself) are not 100% confident that the other fix will work, and TBH I don't have an easy way to test it locally. I would welcome instructions though!

Alternatively, @jakevdp would it be fine to simply modify the role linking the numpy ufuncs in the jax docs to `:py:data:` as an easy fix and move on?

**Comment by ilemhadri** [comment]
@jakevdp

**Pull request merged**
