### PR TITLE
Fix minor bug in bernoulli.pmf

### PR DESCRIPTION
**Pull request by slinderman**
np.exp(pmf(...)) -> np.exp(logpmf(...))

### CODE REVIEW

**Comment by slinderman** [comment]
@googlebot I signed it!

**Comment by gnecula** [comment]
@fehiepsi Can you please take a look, it looks like you wrote this code originally. Thanks!

**Comment by fehiepsi** [comment]
Yes, that is a bug. Thanks for the fix!

**Comment by mattjj** [comment]
Thanks, Professor Scott!

**Comment by mattjj** [comment]
Does the existence of this bug mean this code is untested? Probably. But I'd rather not block this obvious fix on adding a test.

**Comment by fehiepsi** [comment]
@mattjj Current tests for scipy_stats only deal with `log...`. :D

**Pull request merged**
