### PR TITLE
Simplify `jnp.isclose`

### PR DESCRIPTION
**Pull request by soraros**

### CODE REVIEW

**Comment by jakevdp** [comment]
What does the new implementation return for `jnp.allclose(1, jnp.inf)`?

**Comment by soraros** [comment]
@jakevdp It returns `False`. Do you expect something else?

**Comment by jakevdp** [comment]
> Do you expect something else?

No, just thinking about corner cases. I'm not confident that the test suite covers all cases, so I'm trying to think through how this logic may go wrong.

**Comment by jakevdp** [comment]
One example we should check: what if `rtol` is infinity and `b` is zero? Then `rtol * b` returns `NaN`. Does the new logic match the old logic in this case for all possible values of `a`?

**Comment by soraros** [comment]
@jakevdp You are right, they indeed don't match.

<details>
<summary>z3</summary>

```python
import math
import z3

def fpIsFinite(x):
  return ~(z3.fpIsInf(x) | z3.fpIsNaN(x))

def isclose_new(a, b, rtol, atol, equal_nan):
  same_value = z3.fpEQ(a, b)
  both_nan = z3.fpIsNaN(a) & z3.fpIsNaN(b)
  both_finite = fpIsFinite(a) & fpIsFinite(b)
  is_close = z3.fpAbs(a - b) <= atol + rtol * z3.fpAbs(b)
  out = same_value | both_finite & is_close
  return z3.If(equal_nan, out | both_nan, out)

def isclose_old(a, b, rtol, atol, equal_nan):
  out = z3.fpAbs(a - b) <= atol + rtol * z3.fpAbs(b)
  a_inf = z3.fpIsInf(a)
  b_inf = z3.fpIsInf(b)
  any_inf = a_inf | b_inf
  both_inf = a_inf & b_inf
  out = out & ~any_inf
  same_value = z3.fpEQ(a, b)
  same_inf = both_inf & same_value
  out = out | same_inf

  a_nan = z3.fpIsNaN(a)
  b_nan = z3.fpIsNaN(b)
  any_nan = a_nan | b_nan
  out = out & ~any_nan
  return z3.If(equal_nan, out | a_nan & b_nan, out)

fp_sort = z3.Float32()

a, b = z3.FPs('a b', fp_sort)
rtol, atol = z3.FPs('rtol atol', fp_sort)
equal_nan = z3.Bool('equal_nan')

new = isclose_new(a, b, rtol, atol, equal_nan)
old = isclose_old(a, b, rtol, atol, equal_nan)

s = z3.Solver()
s.add(new == old)
if s.check() == z3.sat:
  print(s.model())  # sad
```

</details>

**Pull request closed without merging**
