### PR TITLE
Add link to XLA header in jax_to_hlo

### PR DESCRIPTION
**Pull request by rjeli**
It took me ~10 minutes of googling to find this header, hopefully this saves someone else the time

### CODE REVIEW

**Comment by rjeli** [comment]
I signed it!

**Comment by rjeli** [comment]
cla bot bump

**Comment by rjeli** [comment]
cla bump..

**Comment by rjeli** [comment]
waiting for corporate cla to go through.

**Comment by mattjj** [comment]
Thanks for this contribution!

Just to double-check, did you sign the CLA with the email you used on the commit (i.e. your.name@pronto.ai)?

**Comment by rjeli** [comment]
Yep, all the same email, on the CLA, commit, my public github email, etc. Just signed the CLA on behalf of Pronto, but the CLA manager says no CLA on file - according to the docs somewhere it takes a few days for corporates to go through, perhaps it's being faxed to a lawyer shaped entity somewhere in south bay

**Comment by hawkinsp** [comment]
Ok, it looks like the CLA bot is now happy. Sorry that took so long! However now there's a merge conflict because the text was edited by another PR in the meantime. @jlebar might have opinions about the right resolution; I'm not sure why the text was deleted.

**Comment by jlebar** [comment]
I think the merge resolution should be straightforward, i.e. it seems clear to me where to put this line in the new code.  But ping if you need help.

**Comment by mattjj** [comment]
I put the link in the docstring; hopefully its position makes some sense.

This will be useful for anyone trying to figure out how to use this tool. Thanks for this documentation improvement!

**Pull request merged**
