### PR TITLE
Fix typo np.bool -> np.bool_

### PR DESCRIPTION
**Pull request by NeilGirdhar**
np.bool is just bool.  This was probably meant to be np.bool_, which is numpy's Boolean type.

### CODE REVIEW

**Comment by jakevdp** [comment]
Thanks! The failures here have been fixed on master. If you rebase, they should go away.

**Comment by NeilGirdhar** [comment]
@jakevdp Thanks, but I can't seem to find the commit?  I'm on master and I still get the warnings, e.g., https://github.com/google/jax/blob/master/jax/numpy/lax_numpy.py#L631

**Comment by jakevdp** [comment]
Oh, I meant that the test failures reported by github above are fixed in master. If you rebase your branch on master, the tests will pass, and we will be able to merge your pull request.

**Comment by NeilGirdhar** [comment]
@jakevdp Oh, got it, I'll do that tonight.

**Comment by NeilGirdhar** [comment]
https://github.com/google/jax/pull/3525

**Comment by jakevdp** [comment]
Thanks! For future reference, there is no need to open a new pull request. Any modifications made to the original branch will be reflected in the original pull request.

**Pull request closed without merging**
