### PR TITLE
[WIP] Batch norm moving average

### PR DESCRIPTION
**Pull request by joaogui1**

### CODE REVIEW

**Comment by joaogui1** [comment]
I saw folks are already fixing this in stax2

**Comment by joaogui1** [comment]
They are already fixing it in stax2 (and with a much more elegant solution)

**Comment by joaogui1** [comment]
They are already fixing it in stax2 (and with a much more elegant solution)

**Comment by tvogels** [comment]
Hi, I'd be curious how the much more elegant solution in Stax 2 looks like. Can we find it somewhere?

**Pull request closed without merging**
